### ISSUE TITLE
There is a problem connecting to the server 

### ISSUE THREAD

**Issue by JoaoMXN** [bitwarden/mobile#334] opened 2018-06-28 23:07 UTC
I can't log into my Bitwarden account through the Android app. It keeps loading for several minutes and gives the error. I can login via web vault in Chrome for Android and I can log in to other apps, only Bitwarden gives errors. I already deleted and redownloaded the app and restarted my phone (Galaxy S5) as well.

**Comment by kspearrin** [comment] 2018-06-28 23:39
Are the permissions issues with the app? Check under Android settings.

**Comment by JoaoMXN** [comment] 2018-06-29 03:43
It didn't work, unfortunately. I also changed my DNS and nothing. Funny that the first day when I downloaded the app it worked normally and today it doesn't want to log in anymore.

**Comment by kspearrin** [comment] 2018-06-29 03:44
Unfortunately I don't have any other ideas at this time. Please let me know if you figure anything out.

**Comment by kspearrin** [comment] 2018-06-29 03:45
Also, is this on the regular Bitwarden cloud servers or are you using your own server?

**Comment by JoaoMXN** [comment] 2018-06-29 03:49
It is on the regular Bitwarden servers. By the way, my phone is rooted, could that be it?

**Comment by kspearrin** [comment] 2018-06-29 03:50
It could be anything. Does logcat report any kind of errors when logging in?

**Comment by JoaoMXN** [comment] 2018-06-29 04:15
I don't know how to read it properly, but I don't see any errors.

[bitwarden log.txt](https://github.com/bitwarden/mobile/files/2147725/bitwarden.log.txt)

**Comment by x11x** [comment] 2018-07-20 12:55
I am also having problems logging in on a rooted phone.
There is no delay, just a dialog "An error has occurred. Not connected to the internet." It appears instantly when I try to log in.
I have verified that I am connected to the internet, other apps have connectivity, tried all different connections, I'm sure its not a connectivity problem.
I am running Afwall+ (firewall), and I have checked that it is configured correctly for Bitwarden (allowed full access). I have also tried disabling Afwall+.
It is an unusual setup, Chinese firmware (ZUI, based on Android 7.0) and does not have Google Play services. However, most apps work. I realise this app uses Firebase, Google push messaging etc.
[bitwarden-logcat.txt](https://github.com/bitwarden/mobile/files/2213953/bitwarden-logcat.txt)
 I read #6 that it should still work without push messaging. I tried the Fdroid apk,.
My theory is that the connectivity check has some requirement (Google play services?) and is causing it to fail even though there is connectivity. Is there any way to disable that connectivity check? It would be good if the connectivity check could be skipped if Google play services is not detected.
I have not had a chance to try building myself and probably will not for some time. My first thought was to try removing the check https://github.com/bitwarden/mobile/blob/master/src/App/Repositories/ApiRepository.cs#L26 but I am not familiar with the code at all so have no idea if this is the right track or not.
A bit of logcat is attached (`adb logcat | grep -i bitwarden`), I can't see any exceptions in there. I can post another complete logcat if you need.

**Comment by kspearrin** [comment] 2018-07-20 13:05
@x11x This is the library we use for connectivity testing on Android:

https://github.com/jamesmontemagno/ConnectivityPlugin/blob/master/src/Connectivity.Plugin.Android/ConnectivityImplementation.cs

We updated it recently and pushed it to the beta track on Google Play. Could you re-test it with these updates and see if the problem was fixed perhaps?

https://play.google.com/apps/testing/com.x8bit.bitwarden

Or download the raw APK here:
https://ci.appveyor.com/project/bitwarden/mobile/build/artifacts

**Comment by x11x** [comment] 2018-07-20 13:20
@kspearrin I tried with the updates and it works!
Thanks very much for your quick response, I'm impressed.
Really love this app and service, very happy with it.
That solves my issue but I think my issue was different to the OP.
Hoping the Fdroid release will work out soon and I can install from there, although I know they can make it difficult to get apps in that have nonfree components.

**Comment by kspearrin** [comment] 2018-07-20 17:29
@JoaoMXN Can you try latest beta please?

**Comment by JoaoMXN** [comment] 2018-07-20 21:35
@kspearrin Still has the problem. It doesn't show the error right away like with x11x, but stays at the login loading for several minutes before the server error.

**Comment by kspearrin** [comment] 2018-07-22 12:03
@road42 Sounds like a separate issue. Your LE cert probably doesn't have a full trust chain, which is required on Android.

**Comment by kspearrin** [comment] 2018-07-24 12:17
@andre1808  Sounds like a separate issue. Your LE cert probably doesn't have a full trust chain, which is required on Android. Check on https://www.digicert.com/help/

**Comment by road42** [comment] 2018-07-24 17:17
@kspearrin 
If I call my Bitwarden Local Site via Android Chrome everything is valid including the certificate. Chrome seems to bring its own CertificateChain.

I checked the Settings -> DeviceSecurity -> Certificates if anything sounds like "LE" and did not find anything.
1. Then I went to: https://letsencrypt.org/certificates/ and
2. downloaded the two "active intermediate" certificates.
3. Renamed them to .pem (instead of .txt) and
4. imported them to the UserCertificates.

Now I can successfully connect to my own bitwarden server.

**Comment by Joshndroid** [comment] 2018-07-27 08:02
@road42 


```
    Then I went to: https://letsencrypt.org/certificates/ and
    downloaded the two "active intermediate" certificates.
    Renamed them to .pem (instead of .txt) and
    imported them to the UserCertificates.

```

Are you self hosting?
I see with your method that there is no private.key listed as you have just downloaded .pem files are you converting them to .crt to place in your bwdata for self hosting?

**Comment by andre1808** [comment] 2018-07-27 08:18
@Joshndroid 
You first have to create certificates (with lets encrypt) for your server. You need to integrate those to your bitwarden installation.
When you did that you can download the intermediate certificates from letsencrypt and import them on your mobile.

**Comment by Joshndroid** [comment] 2018-07-27 10:13
@andre1808

Im running local instance and not allowing outside access (use VPN for that) so I'm lead to nieve let's encrypt won't work in that fashion

**Comment by phantomjinx** [comment] 2018-07-28 21:17
Same problem as original bug report.

Created new account for my wife.
Installed bitwarden on the desktop and logs in fine.
Installed firefox extension on android and logs in fine.
Installed android app and fails to login, eventually timing out after a minute or so.

* Tried changing permissions for the app and makes no difference.
* Tried logging into my own account using the app on my phone and it works fine.
* Tried logging into my own account using the app on wife's phone and fails.
* Tried logging into my wife's account using the app on my phone and works fine.
* Tried logging into my either account with my wife's tablet and fails.
* Both phones are running the same version although I installed bitwarden to my phone originally 6 months ago.
* Upgraded to the beta and still failed to connect.

Specs
* Wife's Phone: Android 7.0
* Wife's Tablet: Android 5.0.1
* My Phone: Android 8.0

Conclusions:
* Not related to account but the communication of the app with the servers. 
* Some regression bug with older Android versions?

**Comment by ende124** [comment] 2018-08-17 18:16
Same issue for me, running non-rooted Android 8.0.

**Comment by FoxBJK** [comment] 2018-08-27 02:11
I'm having this same issue, and it sounds like the core issue is that the certificate chain isn't available. My question - is there a way to add the chain.pem file from LE into NGINX's config, or do I need to create a new cert file with the cert and full chain together?

**Comment by phantomjinx** [comment] 2018-08-29 09:26
Just to clarify, the issue I am facing has nothing to do with a standalone/local installation of bitwarden. My devices are failing to connect to the main Bitwarden server (and failing).

**Comment by kspearrin** [comment] 2018-08-29 12:02
@phantomjinx Maybe you have internet permissions blocked for the app?

**Comment by FoxBJK** [comment] 2018-08-29 13:27
Just to rule this out, does your connection use any kind of proxy or network filtering that might interfere with certificate delivery? Is your Android device modified to not include the root CA and intermediate certs that Bitwarden uses? Android's _really_ picky about certificates in general.

**Comment by phantomjinx** [comment] 2018-08-29 13:57
@FoxBJK 
No proxy. Straight to home network router and on to internet. If anyone could let me know the ports that Bitwarden talks to I could log the packets coming in and out of the router. At least then I can confirm connectivity. My LG6 phone has no issues connecting (instantaneous). Yet still the case that my wife's tablet, phone and my own tablet (LineageOS 14.1 / Android 7.1.2) all fail to connect.

**Comment by FoxBJK** [comment] 2018-08-29 15:37
I only needed to open up the standard HTTPS port (443) for my self-hosted instance, so I'd assume all communication is done through there.

**Comment by phantomjinx** [comment] 2018-08-30 20:49
Good news!
Yesterday Bitwarden app just wouldn't connect. Today, I have borh my tablet and the wifs's phone up n running. Made no changes to either in last 24 hours so presumably something has been fixed on the server? Anyway, thanks!

**Comment by kspearrin** [comment] 2018-08-30 20:50
@phantomjinx No changes were made recently.

**Comment by phantomjinx** [comment] 2018-08-30 20:57
@kspearrin 
Well that's juat plain weird. I made my original comment on the 28th July. Intermittently, I have tried logging in ever since both on my tablet and my wifes phone. Both failed as I have reported. Yet this evening both connect without a hitch. Clearly something has changed.

**Comment by kspearrin** [comment] 2018-08-30 20:58
Who knows. We haven't made any server changes since last week.

**Comment by JoaoMXN** [comment] 2018-08-30 21:02
Still the same problem here. Timeout error at login.

**Comment by phantomjinx** [comment] 2018-08-30 21:06
@JoaoMXN 
What version are you running. Only possibility I can think of is BW apl upgraded to 1.18.1 yesterday and I have rebooted.

**Comment by JoaoMXN** [comment] 2018-08-30 21:13
@phantomjinx I downloaded the latest one from google play. I already give up trying a solution, just waiting some patch to solve it. Impossible to be a device issue since ALL apps work normally and the Bitwarden site in the browser works as well. It's 100% a Bitwarden server issue with the app.

**Comment by andre1808** [comment] 2018-10-19 02:31
I have no idea why, but it stopped working again :(
Even adding the certificates manually to Android doesn't resolve the issue for me any longer. 

Any idea how I can sort this?

**Comment by andre1808** [comment] 2018-10-25 17:49
Hi.
Can you maybe help me please?
Because my QNAP is stressing me out since I've updated to QTS4.3.5 I was fiddling with my DNS and stuff and for some reason also renewed my SSL certificate. I've got my bitwarden back running, but I still can't use the Android app to connect to the server.

When creating the certficate from the QTS admin panel I was able to extract the following files:
cert
chain
combine
csr
intermediate.pem
key
local_post_content

Since you were mentioning a ssl chain issue, can you help me in resolving this using above files?

Thanks
André

**Comment by andre1808** [comment] 2018-11-05 14:43
I finally got it working... (also without adding any certs to Android)
In the config.yml I've removed the CA script since it's optional anyway.

I've figuired out that from all files above (cert; chain; combine; csr; intermediate.pem; key; local_post_content) the 
cert = server certificate
chain = ca certificate
key = private.key

I've combined them: cat cert chain >> certificate.crt
copy certificate.crt + private.key into bwdata/ssl/domain/

./bitwarden.sh rebuild
./bitwarden.sh start

Done. Android App working, ssl check (https://www.digicert.com/help/) is completely green, browser is working - everything is working like charm - at least at the moment :D

**Comment by JoaoMXN** [comment] 2019-01-09 10:51
Update of my problem: After changing the router, apparently my problem was solved. Without any relation to the problem, my provider changed my router after a speed upgrade and with the new router (Tp-Link Archer C5 V4) the problem doesn't happen anymore. Now the question is what the problem was with the other router since most of the apps and the browser worked normally.

**Closed** 2019-01-09 10:51 UTC
