### ISSUE TITLE
iOS - Bitwarden crashes in full screen web apps

### ISSUE THREAD

**Issue by jacopo-j** [bitwarden/mobile#431] opened 2019-01-01 17:00 UTC
If Bitwarden is called from the keyboard in a full screen web app on iOS, the interface crashes before performing Face ID authentication. 

Note that, in a full screen web app, Bitwarden cannot be called in any other way since the extensions UI is hidden. I have to quit the web app, open Bitwarden app, copy the password and paste it back into the web app, which is quite annoying. Also, username and password cannot be both copy-pasted into the web app since web apps do not run in the background and they reset each time they are re-opened.

[Demo](https://imgur.com/SI3Wsdp)

**Comment by kspearrin** [comment] 2019-01-02 04:36
How do I create a full screen web app? Just add a website to the homescreen?

**Comment by jacopo-j** [comment] 2019-01-02 08:01
Yes, but it only works if the website is "web app capable". This means that the website must have this HTML meta tag in the `head` section:

```<meta name="apple-mobile-web-app-capable" content="yes">```

**Comment by jacopo-j** [comment] 2019-01-03 13:21
I quickly made a page: https://www.jacopojannone.com/bitwarden_test.php

**Comment by kspearrin** [comment] 2019-01-03 15:55
This appears to be a bug with iOS. I can reproduce the same issue with autofill in other password manager apps.

**Comment by kspearrin** [comment] 2019-01-03 15:55
Closing since I don't think there is anything I can do about it. Thanks for the test page.

**Closed by kspearrin** 2019-01-03 15:55 UTC
