### ISSUE TITLE
Passwords owned by organizations not available in mobile app

### ISSUE THREAD

**Issue by jkriegshauser** [bitwarden/mobile#922] opened 2020-05-23 17:49 UTC
## Describe the Bug
A password that is owned by an organization that one belongs to does not appear in the searchable list of passwords that pops up when the app is asked to provide a password on demand.

## Steps To Reproduce

1. Create a password owned by an organization that you are a member of
2. Go to the website or app that requires said password
3. On iOS, choose 'Passwords ...' from the above-keyboard context menu
4. Note that the password does not exist in the list and there does not appear to be an intuitive way of accessing it.

## Expected Result

The password should appear in the list

## Actual Result

The password does not appear in the list

## Environment

- Device: iPhone X
- Operating system: iOS 13.4.1
- Build Version (go to "Settings" → "About" in the app): iOS 13.4.1
- Is this a Beta release? N

**Comment by tgreer-bw** [comment] 2020-05-23 18:24
Have you tried assigning that item to a collection?

**Comment by jkriegshauser** [comment] 2020-05-23 18:49
> Have you tried assigning that item to a collection?

Yes, you *have* to assign to a collection when it's created. I only have one collection called "Default collection"

**Comment by tgreer-bw** [comment] 2020-05-23 18:54
Org passwords are only synced every 30 minutes or so, but I can confirm they are definitely presented within the app as long as they’re in a collection and your user has access to that collection.

If you can, try and sync your vault to make sure all the vault information has been loaded.

**Comment by kspearrin** [comment] 2020-05-24 00:43
@tgreer-bw Looks like he is specifically referring to the autofill listing on iOS. Did you check that?

**Comment by tgreer-bw** [comment] 2020-05-24 00:45
Yep, auto fill looks good for org items on my end.

**Comment by MattTheDev** [comment] 2020-07-14 20:07
Hiya @jkriegshauser - 

I'm looking to help resolve this issue for you. I've been attempting to repro the issue, and I'm having some problems making the same thing occur. My initial question is going to be - is this still an issue for you? It's been a bit, just wanting to make sure the problem is still occurring.

**Comment by jkriegshauser** [comment] 2020-07-14 23:33
Hi Matt, I am still having issues. Let me attach some screenshots. Here is a brand new fake login I created for github in the Bitwarden app owned by the organization
![8D0F779A-57F2-4943-8D92-B553455DEF00](https://user-images.githubusercontent.com/1697375/87486196-9bcd4c80-c5ef-11ea-8239-2e8c640bd0ed.png)

When I visit the website and tap on the passwords here’s what I see (just the legit login):
![CB47115C-D8A5-432F-9623-AB7F5CD3F1AB](https://user-images.githubusercontent.com/1697375/87486260-bbfd0b80-c5ef-11ea-887a-8b78eef3bd3c.jpeg)

**Comment by jkriegshauser** [comment] 2020-07-14 23:37
Note that if I tap on the `Bitwarden...` button shown in the last pic it will overlay the app and show a list that includes the fake one as well. But it's not popping up here.

**Comment by MattTheDev** [comment] 2020-07-15 16:37
I understand @jkriegshauser - so if you hadn't created the fake github account, it would've never prompted and suggested the org github account, you'd have to choose Bitwarden, and choose it from the list. I am able to repro this :) 

Digging in and taking a look for you.

**Comment by clayadams5226** [comment] 2020-12-31 03:59
Hi @jkriegshauser , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by clayadams5226** 2020-12-31 03:59 UTC
