### ISSUE TITLE
Android 14 - crashes on vault export

### ISSUE THREAD

**Issue by artproject-2004** [bitwarden/mobile#2827] opened 2023-10-15 13:53 UTC
### Steps To Reproduce

1. Go to Settings>Export vault>.json or encrypted .json
2. Click on Export vault>confirm export

### Expected Result

Show place to choose for daving files and export them.

### Actual Result

App crashes. Sometimes immediately, sometimes with error popup (log). Clear cache doesn't help.

The last log:
````
type: crash
osVersion: google/panther/panther:14/UP1A.231005.007/2023101300:user/release-keys
package: com.x8bit.bitwarden:8002
process: com.x8bit.bitwarden
processUptime: 20868 + 553 ms
installer: com.android.packageinstaller

android.runtime.JavaProxyThrowable: System.ArgumentNullException: Value cannot be null.
Parameter name: masterKey
  at Bit.Core.Services.CryptoService.HashMasterKeyAsync (System.String password, Bit.Core.Models.Domain.MasterKey masterKey, Bit.Core.Enums.HashPurpose hashPurpose) [0x000d6] in <1a29e85fbe204ac0942840df4d1d2d1d>:0 
  at Bit.Core.Services.CryptoService.CompareAndUpdateKeyHashAsync (System.String masterPassword, Bit.Core.Models.Domain.MasterKey key) [0x00139] in <1a29e85fbe204ac0942840df4d1d2d1d>:0 
  at Bit.Core.Services.UserVerificationService.VerifyUser (System.String secret, Bit.Core.Enums.VerificationType verificationType) [0x00284] in <1a29e85fbe204ac0942840df4d1d2d1d>:0 
  at Bit.App.Pages.ExportVaultPageViewModel.ExportVaultAsync () [0x0021e] in <a579518fbb6742b3b93077386e29584a>:0 
  at Bit.App.Pages.ExportVaultPage.ExportVault_Clicked (System.Object sender, System.EventArgs e) [0x00084] in <a579518fbb6742b3b93077386e29584a>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <51b898a83b75465fbfeffa1c610b07a8>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <a4ce7c62bc97496f8481f731fa95dba2>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <a4ce7c62bc97496f8481f731fa95dba2>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <a4ce7c62bc97496f8481f731fa95dba2>:0 
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V (_JniMarshal_PP_V callback, System.IntPtr jnienv, System.IntPtr klazz) [0x00005] in <a4ce7c62bc97496f8481f731fa95dba2>:0 
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

````

### Operating System

Android

### Operating System Version

14

### Device

Pixel7

### Build Version

2023.9.2 (8002)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment] 2023-10-15 15:29
Duplicate of #2793

**Comment by djsmith85** [comment] 2023-10-15 15:29
Hi there!

Thank you for your report, it seems like it is a duplicate of this one #2793 .

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2023-10-15 15:29 UTC
Labels: bug
