### ISSUE TITLE
Bitwarden doesn't respect the vault timeout time "Never" and locks the vault every few hours

### ISSUE THREAD

**Issue by FaviFake** [bitwarden/mobile#2856] opened 2023-11-04 07:26 UTC
### Steps To Reproduce

1. Set the vault timeout to Never
2. Wait a few hours
3. When you reopen Bitwarden, you're promoted to unlock your vault again

### Expected Result

The vault doesn't get locked

### Actual Result

The vault gets locked after a few hours of the app being closed

### Operating System

Android

### Operating System Version

One UI 5.1

### Device

Samsung Galaxy A72

### Build Version

Version: 2023.9.2 (8002)

### Beta

- [X] Using a pre-release version of the application.

**Comment by alexandrubaciu9** [comment] 2023-11-04 15:20
Same problem

**Comment by alexandrubaciu9** [comment] 2023-11-04 15:21
I got the same problem, It bother's me everytime I need to acces my vault.

**Comment by SergeantConfused** [comment] 2023-11-04 20:33
Hi @FaviFake,

Thank you for your report. It seems that this is a duplicate of this report (https://github.com/bitwarden/mobile/issues/2787); This matter has been addressed in version 2023.10.0.

This issue here will now be closed.

Thank you again,

**Closed by SergeantConfused** 2023-11-04 20:33 UTC
Labels: bug
