### ISSUE TITLE
Show password hides characters

### ISSUE THREAD

**Issue by MyGGaN** [bitwarden/mobile#3405] opened 2024-10-05 11:08 UTC
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Create a login item
2. Set the password to eg. "hello<3", save
3. When viewing the password (clicking the eye button) the "<" will not show

### Expected Result

hello<3

### Actual Result

hello3

### Operating System

Android

### Operating System Version

14

### Device

Galaxy S24Uultra

### Build Version

2024.7.1 (11086)

**Comment by jtodddd** [comment] 2024-10-07 13:23
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/mobile/issues/3110 . 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by jtodddd** 2024-10-07 13:23 UTC
Labels: bug
