### ISSUE TITLE
Lock Screen can be bypassed on iOS

### ISSUE THREAD

**Issue by atheler** [bitwarden/mobile#65] opened 2017-04-28 10:07 UTC
It is possible to bypass entering the master password by closing the app (home button double-click / app switching) and then restarting it. This is only possible with Auto-Lock set to anything but „intermediate“ and not when the app was locked manually.

Bitwarden Version 1.0.0 (7), iOS 10.3.1

**Comment by kspearrin** [comment] 2017-04-28 12:17
Testing and I am not able to reproduce. Are you waiting past the amount of time selected from the option?

**Comment by atheler** [comment] 2017-04-28 12:41
Yes, I am waiting past the amount of time selected (e.g. 1 minute). The app will then also correctly ask me for my password. However, in this state it is then possible to restart the app. After this it will not ask for my password anymore and I can then simply access my keychain.

A friend of mine was also able to reproduce this bug on his iPhone.

**Comment by kspearrin** [comment] 2017-04-28 12:42
Ok, I got it to work now. It requires you to restart from the actual lock screen. Thanks.

**Comment by kspearrin** [comment] 2017-04-28 15:15
This should be resolved in the next version.

**Closed by kspearrin** 2017-04-28 15:15 UTC
