### ISSUE TITLE
No option to generate passphrase when creating an entry upon lookup in iOS

### ISSUE THREAD

**Issue by netvl** [bitwarden/mobile#793] opened 2020-03-22 21:56 UTC
## Describe the bug

If you want to create an item in the vault when you use the iOS feature for password lookup in the browser/any application (the button over the keyboard which appears when typing in a password field), then Bitwarden does not give an option to generate a passphrase, only a regular password.

## Steps To Reproduce

1. Open any application or a site in any browser where you can enter a password.
2. Select the password field and tap the “Passwords” button over the keyboard to bring up Bitwarden.
3. Tap the + button to add a new item
4. Tap the “Generate password” button to open the password generation UI

## Expected Result

Bitwarden shows the regular password generation UI, with an option to create a passphrase.

![51DA780D-6205-47E7-B4E7-1F7EC215F683](https://user-images.githubusercontent.com/280456/77261544-67064580-6c4c-11ea-8c6e-9db5b6eab2af.png)

## Actual Result

Bitwarden shows another, more limited UI with no option to generate a passphrase.

![35FEE5C2-E03C-4E1A-9671-56F01E96EF28](https://user-images.githubusercontent.com/280456/77261571-974de400-6c4c-11ea-99cb-89380fe8a3da.png)

Also, the overall UI  for creating an entry this way looks different from the main app, maybe it hasn’t been updated to match the main app?

## Screenshots or Videos

See above.

## Environment

- Device: iPhone Xs Max
- Operating system: iOS 13.3.1
- Build Version: 2.3.1 (64)
- Is this a Beta release? N

## Additional Context

 N/A

**Comment by onefellsloop** [comment] 2020-07-19 03:48
+1 - Also experiencing the same behavior.

Environment

Device: iPhone 6s
Operating system: iOS 14.0
Build Version: 2.5.0 (193)
Is this a Beta release? N

The message “option details are set from the main Bitwarden app’s password generation tool” hopefully means that this worked at one time?

Thanks!

**Comment by eliykat** [comment] 2021-01-19 20:23
Thanks for reporting this issue. This screen does look a bit different due to the nature of iOS app extensions - it doesn't mean it's out of date, but it does mean that the passphrase feature was not implemented in this part of the app.

This is a duplicate of #620, so please refer to that issue for any future updates.

**Closed by eliykat** 2021-01-19 20:23 UTC
