### ISSUE TITLE
iOS - Autofill doesn't work well on iPhone Appstore,sometimes it just can't autofill.

### ISSUE THREAD

**Issue by igotyoubaby** [bitwarden/mobile#1176] opened 2020-12-14 05:32 UTC
## Describe the Bug
Autofill doesn't work well on iPhone Appstore,sometimes it just can't autofill.

## Steps To Reproduce
Step 1:Open appstore on iPhone

Step 2:Log out Apple ID

Step 3:Tap the Apple ID blank

Step 4:The password and the key icon comes out on the top of keyboard

Step 5:Hit the "password" and Bitwarden is pulled up

Step 6:Unlock the Bitwarden with Face ID

Step 7:Tap the Apple ID account information in Bitwarden

Step 8:Apple ID and password weren’t auto-filled in AppStore

Step 9:Tap the empty ID blank once, auto-fill works.

## Expected Result
Autofill works more stably

## Actual Result
When I try to login my Apple ID on iPhone Appstore,after I choose the User information from Bitwarden，there is nothing to be auto-filled.

## Environment

- Device: iPhone12 Pro
- Operating system: iOS14.2.1
- Build Version (go to "Settings" → "About" in the app): 2.7.0(358)
- Is this a Beta release?No

## Additional Context
I've already reported this problem to your team by Email

**Comment by anmolsjoshi** [comment] 2021-01-27 07:30
Would really like this figured out!!

**Comment by kendratodd** [comment] 2021-03-11 23:23
We can't seem to reproduce this issue on the latest App store version (2.8.0). @igotyoubaby, @anmolsjoshi, are you still experiencing this issue? If so, could you provide the latest details about your app and operating system versions? Thanks!

**Comment by kendratodd** [comment] 2021-03-25 14:50
Hi @igotyoubaby – since we haven't been able to reproduce this issue on our side and we haven't received any additional info, I'm going to close this issue for now. 

If it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further. Thank you!

**Closed by kendratodd** 2021-03-25 14:50 UTC
