### ISSUE TITLE
Crashing on iOS 14 beta 

### ISSUE THREAD

**Issue by BobbyMcWho** [bitwarden/mobile#1055] opened 2020-08-30 21:34 UTC
## Describe the Bug  
App crashes on iOS 14 Beta build 6 (still occurring on build 7)

## Steps To Reproduce  
1. Open Bitwarden
2. Unlock using either Master Password or FaceID

## Expected Result  
App opens to main screen

## Actual Result  
App crashes

## Screenshots or Videos  

https://youtu.be/Y5vI2aYJ_Lo

## Environment

- Device: iPhone 11 Pro
- Operating system: 14.0 (18A5357e)
- Build Version (go to "Settings" → "About" in the app): 2.5.0
- Is this a Beta release? Yes for iOS, no for the app

## Additional Context  
I can still use the app through the iOS keyboard password manager’s auto fill, but if I try and open the app it crashes no matter where I open it from.

**Comment by itsrishabh** [comment] 2020-09-10 12:28
+1, same issue here on the latest beta (September 9, 2020)

**Comment by mportune-bw** [comment] 2020-09-10 13:19
I'm unable to reproduce this using the same config (iPhone 11 Pro running iOS 14 beta 8, public release of Bitwarden app, fresh install, logged in with Face ID unlock enabled).  Can you try re-installing the app?  Are there additional settings/features you have enabled in Bitwarden beyond the defaults?

**Comment by BobbyMcWho** [comment] 2020-09-10 13:51
I can confirm that a fresh install of the app seems to have fixed the issue on iOS 14 Beta Release 7. Thanks @mportune-bw for the idea, I didn't realize that I may have to do that.

**Comment by mportune-bw** [comment] 2020-09-10 14:03
No problem, though technically you _shouldn't_ have to do it, so I suspect we still have an issue.  Let us know if it starts happening again.  I'll leave this issue open until iOS 14 final is released.

**Comment by robinbisping** [comment] 2020-09-14 16:15
I experienced the same after upgrading iOS from 13.6 to 13.7, when trying to unlock with both touchID and my passphrase. A fresh install fixed it for me as well.

**Comment by simonpjcox** [comment] 2020-09-16 21:23
Just to confirm I had the same problem when I upgraded my iPad Pro (MTXQ2B/A model) to iOS 14 today; opening the Bitwarden app triggered the FaceID unlock (as expected) but upon completing the unlock it crashed me back out to the iPad home screen.  Following the above advice of deleting and reinstalling appears to have fixed it though so I'll see if I have a similar issue with my iPhone shortly!

**Comment by Arrow2thekn33** [comment] 2020-09-17 17:15
I’ve had the same issue on the iPhone 11 Pro since the beginning of the iOS 14 beta, and it continued after leaving the beta program for the general iOS 14 release. It would crash to home screen after login in any circumstance, whether it be faceID or my password and after 2FA. The crash also occurred when accessing the auto fill from the keyboard. Reinstalling the app fixed the issue.

**Comment by mportune-bw** [comment] 2020-09-23 16:57
Update will be released shortly

**Closed by mportune-bw** 2020-09-23 16:57 UTC

**Comment by smnbbrv** [comment] 2020-10-04 05:04
Any plans on release date? The issue is still in place

**Comment by sbhal** [comment] 2020-11-15 13:07
I am still observing crash on starting app

**Comment by smnbbrv** [comment] 2020-11-15 13:29
What helped me is uninstalling the app and installing it again. Otherwise could not get it working
