### ISSUE TITLE
Unable to use biometrics to autofill on iPadOS

### ISSUE THREAD

**Issue by manicminer** [bitwarden/mobile#1214] opened 2021-01-11 11:11 UTC
## Describe the Bug

> "Biometric unlock for autofill disabled pending verification of master password"

Getting this error message when auto filling on iPadOS, and unable to autofill using biometric authentication (fingerprint in this case).

I have tried the following:

1. Sign out of Bitwarden and in again
2. Disable and re-enable biometric auth
3. Disable and re-enable PIN (in addition to biometric)
4. Disable PIN, lock vault, enter master password to unlock
4. Deleted and reinstalled the app, then retried the above.

## Steps To Reproduce

1. Sign in to Bitwarden
2. Enable biometric (e.g. Touch ID)
3. Try to fill on iPadOS
4. Get the above message

## Expected Result

Signing into Bitwarden and enabling biometrics should permit use of biometrics to authenticate during autofill.

## Actual Result

See the above error message and biometric auth is not available during autofill.

## Screenshots or Videos

![Screenshot 2021-01-11 at 11 06 33](https://user-images.githubusercontent.com/251987/104173152-4090e100-53fd-11eb-8854-4e23e111bcc6.png)

## Environment

- Device: iPad 6th Gen
- Operating system: iPadOS 14.3
- Build Version: 2.7.2 (401)
- Is this a Beta release? N

## Additional Context

This is conceivably by design / a feature, however it's not obvious how to overcome the issue since signing into the app doesn't appear to resolve.

**Comment by SergeantConfused** [comment] 2021-01-11 11:24
Hi there,

Did you try to enter your PIN and tap Submit on this message?
If that didn't help, please open your Bitwarden client and disable your PIN, then try to autofill again and enter your master password and tap Submit.

Please keep me posted on your progress, and let me know if you have any further questions.

**Comment by manicminer** [comment] 2021-01-11 11:30
Hi @SergeantConfused, I did also try entering the PIN on the autofill popup, and also tried disabling PIN, then locking vault and unlocking with master password, both to no avail.

However, I did just try disabling PIN, then entering the master pass on the autofill popup, and that seems to have done the trick! Thanks for the tip.

I'd maybe suggest usability could be improved a lot here. Perhaps entering a PIN should be sufficient to enable biometrics? Or if not, maybe the app should disable PIN and ask for master password instead of requiring the user toggle the setting and retry the fill (unlocking the vault in-app should also work really).

Thanks again!

**Comment by clayadams5226** [comment] 2021-01-13 03:53
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by clayadams5226** 2021-01-13 03:53 UTC
