### ISSUE TITLE
[ios] Export vault not working

### ISSUE THREAD

**Issue by xtqqczze** [bitwarden/mobile#798] opened 2020-03-27 02:11 UTC
## Describe the Bug

Unable to export vault in iOS app: the master password is rejected even though it is valid.

## Steps To Reproduce

1. Open Bitwarden app
2. Go to settings
3. Select "Export vault"
4. Select either .json or .csv file format
5. Type valid master password
6. Select Export Vault button

## Expected Result

Vault is exported.

## Actual Result

Error message: "Invalid master password. Try again."

**Comment by sdo9** [comment] 2020-04-27 00:58
I also get the error about an invalid password, but then the exported file is actually created. So warning to OP: check if your exported unencrypted passwords might be lying around in your export location.

**Comment by xtqqczze** [comment] 2020-04-27 12:34
@sdo Where would the exported file be located? The mobile app does not give the opportunity to choose a location:

![Bitwarden export vault clipped](https://user-images.githubusercontent.com/45661989/80372397-61270400-888b-11ea-94e1-ed80c4e16223.png)

**Comment by sdo9** [comment] 2020-04-28 00:07
Never mind. So mine prompts for the master password, then there's a 
sharing dialog, I happened to pick Files (and in there picked Dropbox and 
Save). At this point I think it does the export for me, but doesn't 
confirm that it did, and then places me back at the screen with file format, master password, and 
Export button. I happened to just click Export, thinking to conclude the 
process, and it said the master password was invalid (because it had 
been blanked).

So, sorry, unrelated, kind of works for me except it's pretty confusing UX 
to be prompted again instead of getting confirmation that the export was done.

**Comment by xtqqczze** [comment] 2020-07-06 21:10
@kspearrin Any thoughts on this issue?

**Comment by xtqqczze** [comment] 2020-09-16 01:44
@kspearrin This feature is stil non-functional in version 2.5.0.

**Comment by xtqqczze** [comment] 2020-10-09 22:33
@kspearrin This feature is still non-functional in version 2.6.1

**Comment by xtqqczze** [comment] 2020-12-03 09:24
@kspearrin This feature is still non-functional in version 2.7.0 on iOS 14.2.

There is no doubt that the password my for account is valid as it is accepted at https://vault.bitwarden.com/

**Comment by MGibson1** [comment] 2020-12-21 21:42
@xtqqczze I'm not able to reproduce your issue. I downloaded your model iPhone (6s, right?) simulator on iOS 14.2 and json export worked for me on Bitwarden v2.7.0.

Is it possible you have a difficult-to-type master password and it is indeed wrong? Is there anything else unique about your setup?

**Comment by xtqqczze** [comment] 2020-12-21 21:51
@MGibson1 Thanks for looking into this for me. I can confirm my current environment is iPhone 6s on iOS 14.2.

Using Bitwarden v2.7.0, I entered the password with characters visible so I have no doubt that it is correct. The same password when entered at https://vault.bitwarden.com/ takes me to 2FA.

Unfortunately my 2FA is lost so I cannot export the vault from the web app.

**Comment by xtqqczze** [comment] 2020-12-24 17:07
Export vault still not working in version 2.7.2 on iOS 14.2.

**Comment by p3lim** [comment] 2022-07-19 21:36
Same issue on Android, version 2022.6.1 (4795), 100% sure the password is correct. I need to export because the self-hosted vault it was connected to is no longer running, and I need to export so I can import to a new vault.

**Comment by xtqqczze** [comment] 2022-07-20 21:33
> Is it possible you have a difficult-to-type master password and it is indeed wrong? Is there anything else unique about your setup?

@MGibson1 100% sure the password was correct.

**Comment by Duranis** [comment] 2023-08-25 05:03
I also have this issue but on Android mobile version as of 24 Aug 23.
Version: 2023.7.0 (6781)
Like original poster get invalid master password even though I know it is 100% correct.

**Comment by andrey-tar-xz** [comment] 2023-09-03 18:07
> I also have this issue but on Android mobile version as of 24 Aug 23. Version: 2023.7.0 (6781) Like original poster get invalid master password even though I know it is 100% correct.

Me too, the app crash after confirm.
Bitwarden version: 2023.8.0
Device: Samsung Galaxy M12
Android: 13
One UI: 5.1

**Comment by samuelbridgewater** [comment] 2023-10-04 09:59
Is this going to be looked at?

**Comment by djsmith85** [comment] 2023-10-04 10:44
The newer reports on this issue are likely a duplicate of https://github.com/bitwarden/mobile/issues/2793 which have been addressed with https://github.com/bitwarden/mobile/pull/2808.
The changes made with #2808 will be included in the upcoming `2023.10`-release.

**Comment by xtqqczze** [comment] 2023-10-04 23:27
I believe "Unlock with Touch ID" was enabled on the device where I had this issue.

**Comment by r-yanyo** [comment] 2023-10-07 07:37
> I believe "Unlock with Touch ID" was enabled on the device where I had this issue.

thanks. I can export to disable "Unlock with Face ID" and relaunch app.

**Comment by djsmith85** [comment] 2023-11-07 13:38
Hey everyone,

With the release of `2023.10` which includes the changes from #2808, could you please test and verify that this has been fixed.

Kind regards,
Daniel

**Comment by r-yanyo** [comment] 2023-11-07 14:16
I confirmed that I can export vault.

**Closed** 2023-11-08 20:28 UTC
