### ISSUE TITLE
crashing after log in (versions 2022.9.0 and 2022.9.1)

### ISSUE THREAD

**Issue by az3tmd** [bitwarden/mobile#2093] opened 2022-09-22 16:58 UTC
### Steps To Reproduce

1. Open app.
2. Log in.
3. App process creditentials then immediately crashes.

### Expected Result

This bug is happening only for latest versions: 2022.9.0 and 2022.9.1.

### Actual Result

The problem is simple.  I uninstalled the latest version 2022.9.1 which crashes.  I installed the penultimate version 2022.9.0.  Likewise, it crashes.  I installed version 2022.8.0, which of course works as it did before I updated to versions 2022.9.0 and 2022.9.1.  So it is definitely a problem with the last two updates.  Analyze and solve the internal situation, it is surely a bug that you have not discovered (yet).  

### Operating System

Android

### Operating System Version

10

### Device

Huawei P30 Lite wirh EMUI 12.

### Build Version

2022.9.0 and 2022.9.1, the same result.

### Beta

- [ ] Using a pre-release version of the application.

**Comment by luciansabo** [comment] 2022-09-22 20:21
I confirm this on samsung s21 and s10

**Comment by Tashima42** [comment] 2022-09-24 13:50
It look's like this is related to #2086 I'm having the same issue with the Romanian language.

**Comment by az3tmd** [comment] 2022-10-01 05:13
Bitwarden, are you working on it?
For us, the others affected by this problem, we need a full functional, working and stable version as soon as possible.

**Comment by Tashima42** [comment] 2022-10-01 10:54
@az3tmd looks like [this PR ](https://github.com/bitwarden/mobile/pull/2099) fixes it but it would be nice to have some confirmation from someone in Bitwarden, this bug affected me while I was in a trip and without internet, so I didn't had access to my passwords unitl I found an internet connection and saw the temporary fix in an issue here, which is not great.

**Comment by Larry-Sussman** [comment] 2022-10-03 23:59
Hi @az3tmd and @Tashima42, thank you for the reports and sorry for the inconvenience! 
We've identified the issue causing this crash, and have a fix (#2099 as mentioned) for Android and iOS which will be included in our upcoming 2022.10 release.

In the meantime, there is a workaround of setting the language for the Bitwarden app to English:
- How to change app language on [Android](https://support.google.com/android/answer/12395118?hl=en)

I hope this helps!

**Comment by az3tmd** [comment] 2022-10-04 06:18
Thanks but I'm sorry @Larry-Sussman, but I won't change the language of the whole mobile phone for this!  It's not right! When will the 2022.10 relase version that will include this fix be ready (as a deadline/term)?

**Comment by djsmith85** [comment] 2022-10-04 10:39
Hi @az3tmd, 

the workaround mentioned, does not involve changing your whole phone to a different language, just Bitwarden. 

As noted by @Larry-Sussman this will be fixed with the 2022.10 release, which is currently scheduled for ~mid-October.

I'm going to close this as a duplicate of https://github.com/bitwarden/mobile/issues/2086 and because a fix is on it's way.

We are sorry for the inconveniences this has caused!

**Closed by djsmith85** 2022-10-04 10:39 UTC
Labels: bug
