### ISSUE TITLE
Broken in TOTP

### ISSUE THREAD

**Issue by fabianski7** [bitwarden/mobile#786] opened 2020-03-19 20:36 UTC
## Describe the Bug
I'm trying to login with the latest version available (2.3.1) but I can't enter my TOTP code. The application closes right after the login with the email and password.

## Steps To Reproduce
1. An account with TOTP activated
2. Start a section with the email and password
3. Login
4. Broken now

## Environment
- Device: OnePlus 6
- Operating system: Android 10
- Build Version: 2.3.1
- Is this a Beta release? N

## Additional Context
Well, I use the Bromite webview module in magisk, and saw in the logs that it might be something webview related, but I did another test without this module loaded and the application kept closing.

Logs: https://0bin.net/paste/fAHJT457Vb7OdE36#iZQRWwXYyadkB85K8bOWvehDwH47j8ZYUif2yuP0zaH

**Comment by MDXDave** [comment] 2020-03-20 09:46
I can confirm the issue, the TOTP Token will not be copied to the clipboard.

Android 10, Xiaomi Mi 9

**Comment by mportune-bw** [comment] 2020-03-27 20:21
Hi @fabianski7 ,

I don't have experience with magisk but the log you provided (thank you btw!) indicates you have a missing chromium native lib:

`Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/webview/webview.apk"],nativeLibraryDirectories=[/system/app/webview/lib/arm64, /system/app/webview/webview.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /system/lib64, /system/product/lib64]]] couldn't find "libwebviewchromium.so"`

Was the log captured with or without the Bromite module?

**Comment by fabianski7** [comment] 2020-03-27 22:53
hi @mportune-bw,

Well, this happened because the bromite module for the magisk is not compatible with android 10 yet.

https://github.com/bromite/bromite/wiki/Installing-SystemWebView
https://groups.google.com/a/chromium.org/forum/m/#!topic/android-webview-dev/Y8FIRqJCCNA

So when the module was activated, the system ran out of webview support. 
Deactivating the module did not activate what the system had. 
That is, in both tests the webview was not working properly.

I don't know if this is possible, but a warning about the broken or missing webview on the system would be ideal to avoid these problems. I really didn't know that bitwarden for android used webview.

**Comment by djsmith85** [comment] 2022-03-11 00:32
Closing this as an upstream issue with Bromite.

**Closed by djsmith85** 2022-03-11 00:32 UTC
