### ISSUE TITLE
Password Generator missing Passphrase in Add New Item from Popover Window on iPadOS (maybe iOS)

### ISSUE THREAD

**Issue by RazorII** [bitwarden/mobile#1224] opened 2021-01-19 10:18 UTC
## Describe the Bug

I was trying to signup on a site and add it during the process to my vault but even though I have it set to passphrase inside the app and on the desktop app, it defaults to password with no option to change it to passphrase. Is this a bug or a missing feature?

## Steps To Reproduce

1. Go to Tap into a password field
2. Click on the key at the bottom bar of iPadOS
3. Scroll down to "+" in the Bitwarden menu bar to add a new entry
4. Click on Generate new password

## Expected Result

Option for Passphrase should be available.

## Actual Result

Only Password options are available.

## Screenshots or Videos
#

![](https://community.bitwarden.com/uploads/default/original/2X/3/31fb2262e7a51408a31ef54aec6df3a92d8224cf.jpeg)

## Environment

- Device: iPadPro
- Operating system: iOS 14.3
- Build Version: 2.7.2 (401)
- Is this a Beta release? N

**Comment by kendratodd** [comment] 2021-03-22 16:43
HI @RazorII, I believe this issue is the same as https://github.com/bitwarden/mobile/issues/620, which was addressed by https://github.com/bitwarden/mobile/pull/1230. 

I'm going to close this issue for now, as the original problem appears to have been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis. Thank you!

**Closed by kendratodd** 2021-03-22 16:43 UTC
