### ISSUE TITLE
Crash on login during server downtime

### ISSUE THREAD

**Issue by ML-Chen** [bitwarden/mobile#909] opened 2020-05-19 05:43 UTC
After pressing Log In, entering my email address and password, and pressing Log In, the app crashes. I just created an account using the app and I’m sure that my password is correct. I also tried a random email address and password and it still crashed, unless the email address was obviously not a valid email address, like “aaaa”, in which case there was a dialog that said “Invalid email address.”

## Environment

- Samsung Galaxy S9+, Android 10, app version 2.3.1, not beta
- iPad Air 2, iOS 13.4.1, app version 2.3.1, not beta

The bug is present on both my devices.

**Comment by kspearrin** [comment] 2020-05-19 06:15
We had some downtime earlier which likely caused this problem. Can you try now, please?

**Comment by ML-Chen** [comment] 2020-05-19 13:59
It works perfectly now. I’m excited to try out Bitwarden! Maybe the app should provide an error message instead of crashing if the server isn’t operating correctly?

**Comment by cscharf** [comment] 2020-07-23 13:29
Hi @ML-Chen , while I'm going to close this issue as it is now resolved, if you happen to be able to retrieve the crash log(s) from your device from when this did happen that would be immensely helpful so we can try to narrow down the scope and root cause of the crash itself. As of right now our team is unable to reproduce this behavior with a "server down" scenario.

**Closed by cscharf** 2020-07-23 13:29 UTC
