### ISSUE TITLE
There is a problem connecting to the server (Android, Wifi)

### ISSUE THREAD

**Issue by rlipscombe** [bitwarden/mobile#437] opened 2019-01-13 14:10 UTC
When I log in using the Android app, it reports "An Error has occurred." / "There is a problem connecting to the server.".

The app was working correctly (as far as can recall) yesterday. I'm connecting to the Bitwarden cloud. I can connect to the cloud from other devices (Chrome on Windows, app on Windows, Edge on Windows, Chrome on Linux).

Interesting point: if I disconnect my phone from my Wifi and use 4G, it works fine.

**Comment by rlipscombe** [comment] 2019-01-13 20:01
fwiw, I tried using tcpdump to capture traffic at my router, and I'm not seeing any bitwarden traffic at all (not even DNS, though that could be cached by Android, I guess). I see plenty of other traffic...

**Comment by kspearrin** [comment] 2019-01-14 02:44
I am not sure, but it seems related to your home network for whatever reason.

**Comment by Crocmagnon** [comment] 2019-01-14 06:51
Does your router have some kind of « malware protection » that could be implemented as SSL MITM with your router providing you with a custom SSL certificate ?
I don’t know if that could be a problem with BW app though.

**Comment by rlipscombe** [comment] 2019-01-14 07:57
> malware protection

No. It's OpenWRT 18.x. Nothing more intrusive than an inbound firewall.

**Comment by rlipscombe** [comment] 2019-01-14 07:59
It's working again this morning, same network (might _not_ be the same AP, but the AP's also running OpenWRT 18.x). Is there any way to debug this problem?

**Comment by rlipscombe** [comment] 2019-01-14 08:02
> I am not sure, but it seems related to your home network for whatever reason.

Like I say, I don't even see bitwarden network traffic on the network when this problem occurs -- though I do see plenty of other network traffic -- which makes me think it's something weird in the app/Android end. I'm using non-rooted Android 8.1.0 on a Google Pixel.

**Comment by nathandines** [comment] 2019-02-11 12:19
I’m also experiencing this on iOS, but seem to also have issues with adding/editing passwords in the Chrome extension on macOS Mojave

My router is running OpenWRT 18.06.2

**Comment by nathandines** [comment] 2019-02-12 20:15
Just an update on what I found for my network: seems like my issue was related to the default MTU setting on my WAN connection. This is a new install of OpenWRT, and I had missed configuring the MTU to a value lower than 1500 for my PPPOE WAN connection.

Anyway, the issue for me doesn’t appear to be caused by Bitwarden. Upon reconfiguring the router, I no longer experience the described issue. @rlipscombe perhaps you’ve got a similar issue.

**Comment by rlipscombe** [comment] 2019-02-13 13:05
> perhaps you’ve got a similar issue

I doubt it; it started working again without any intervention from me.

**Comment by Fealthas** [comment] 2020-09-23 22:31
Had the same issue. Restarting router fixed it.
Very strange... no other app is bothered by this.

**Comment by djsmith85** [comment] 2021-11-19 12:20
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2021-11-19 12:20 UTC
