### ISSUE TITLE
Android app crash when scanning TOTP QR Code

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/mobile#1228] opened 2021-01-20 00:24 UTC
## Describe the Bug

App crash when scanning QR code to add TOTP

## Steps To Reproduce

1. Scan TOTP QR Code

## Expected Result

TOTP configured

## Actual Result

App crash and back to Android home screen

## Environment

- Device: Google Pixel 2
- Operating system: Android 11
- Build Version  2.6.1
- Is this a Beta release? N

**Comment by bchociej** [comment] 2021-01-20 03:39
Hi, I am the one who reported the bug via email to support@bitwarden.com, and Sugianto kindly logged this issue for me. Happy to provide more info as needed.

**Comment by JOduMonT** [comment] 2021-02-10 12:53
I have the same issue on Android with the version 2.6.1

why this is closed ?
does the kickstarter worked and it as been already patched ? Than where is the PR for the patch?

It sound weirdly to an issue I opened last November no ?
https://github.com/bitwarden/mobile/issues/1157

**Comment by isfalcantara** [comment] 2021-02-17 20:49
The same happens on a Samsung Galaxy J4 (2018). The camera viewfinder is somewhat narrower and the app crashes when it sees the QR code.

**Comment by kendratodd** [comment] 2021-03-11 17:58
Similar reports from https://github.com/bitwarden/mobile/issues/1289: 

Device: Google Pixel 3
Operating system: Android 11 RQ1A.210205.004
Build Version (go to "Settings" → "About" in the app): 2.8.0 (3349)
Is this a Beta release? No

**Comment by tverspeelt** [comment] 2021-03-23 20:15
I have the same issue. It seems to only happen on 'complex' QR codes.

My workaround is to use Google Lens to get the URL from the QR, and paste the URL in Bitwarden.

**Comment by YpsilonOmega** [comment] 2021-04-02 06:27
It appears that I've got the same issue:

Device: Galaxy XCover 5 - SM-G525F/DS
OS: Android 11
Build Version: 2.9.1

**Comment by sambartle** [comment] 2021-04-02 06:34
> I have the same issue. It seems to only happen on 'complex' QR codes.
> 
> My workaround is to use Google Lens to get the URL from the QR, and paste the URL in Bitwarden.

I've never found one that cant be scanned in my case it just takes multiple attempts. 
The complexity doesn't seem to matter in my case, its truly random as far as I can tell.

**Comment by Matan** [comment] 2021-04-10 08:58
Same issue for me:

Device: Samsung A50
OS: Android 11
Build: 2.9.1

**Comment by Ksathral** [comment] 2021-06-06 08:13
I have never been able to scan a QR code from within the bitwarden app, it crashes on both official and custom roms (Android 7/8/9/10 all basd on Samsung oneui on my Galaxy S7 G930-F.  The only time I did got it to work was when I used an AOSP based rom ( Android 9).

I just use a seperate QR code scanning app and copy / paste the url into the Bitwarden apps TOTP field to get it it to work.

**Comment by rlipscombe** [comment] 2021-08-31 17:08
Same issue; Pixel 5

**Comment by cwille97** [comment] 2021-09-05 22:55
Same issue:
Google Pixel 3a XL
Android 11
App version 2.12.0

**Comment by Akryum** [comment] 2021-09-07 10:11
Crashes on any QR code scanning, wasn't able to make it work on Pixel 4a | Android 11 | Bitwarden 2.12.0

**Comment by Estevanbs** [comment] 2021-09-21 15:45
Same here.

Android 11 (Lineage OS 18.1)
SM-M205M
Bitwarden 2.12.0

**Comment by webprez** [comment] 2021-10-02 21:32
Same here.

**Comment by sso-bitwarden** [comment] 2021-11-10 06:41
+1 
Device: Samsung J6
Operating system: Android 10
Build Version 2.14.2
Is this a Beta release? No

**Comment by FlipFlopson** [comment] 2021-12-03 03:28
Device: Asus Zenphone 3 Zoom (ZE553KL)
Operating system: Android 8
Build Version 2.14.2
Is this a Beta release? N

I've tried to better understand what causes this, to make adding 2FA less of a hassle and hopefully help whoever looks into this in the future. My process wasn't anything especial:
- Before starting I uninstalled the app, restarted my phone and reinstalled it.
- Used a 2FA QR [code generator](https://stefansundin.github.io/2fa-qr/) to make mock QR codes that I scanned.
  - Made QR codes of varying complexity, from single character secret & label to ridiculously long strings of text.
- Closed and reopened the app after every test.
- Moved the camera in many different ways:
  - Top-down, bottom-up, left-to-right and right-to-left.
  - Fast (snapping the camera towards the QR code) and slow (carefully pointing the camera at it).

My findings were... also nothing special, but I felt the consistency was enough to share.
- Complexity doesn't seem to matter. No noticeable difference between the simplest and most complex QR code.
- Direction/Speed doesn't seem to matter. No noticeable difference between movements.
- The app consistently crashed when I tried to quickly scan the QR code after pressing the scan button.
- The app consistently worked just fine when I "gave it some time" after pressing the scan button, before actually aiming the camera at the QR code.

When I say consistently, I really mean it. I'm speaking 19/20 times consistency. But my camera is spotty, speaking from experience, so I'd be very grateful if someone could just check the findings above. Even if it turns out to be a dead end and it's just my camera being crappy, that's still useful information in a way.

I've little knowledge that could help here, so no idea what's happening beyond wild guesses. Could there be a critical component loading in the background that causes a crash if it isn't loaded by the time you try scanning the QR code?

**Comment by vvolkgang** [comment] 2022-02-10 12:41
Thanks everyone for the info! We weren't able to replicate this in multiple devices but we suspect the linked PR changes will fix it. If you previously had this issue, can you download the .apk from our [CI](https://github.com/bitwarden/mobile/actions/runs/1819141930) and test it please? 

~~Obligatory disclaimer:~~ This isn't an official release that went through regression testing, there might be other unrelated issues overall, we just want to be sure this TOTP crash is fixed. 


Issue was automatically closed due to being linked in the PR but I'm reopening this until we figure it out.

**Comment by aouerfelli** [comment] 2022-02-14 21:17
The issue I'm getting happens the second time I try to scan a QR code without restarting the app. The crash message is `java.lang.RuntimeException: Camera is being used after Camera.release() was called`.

**Comment by Larry-Sussman** [comment] 2022-02-14 22:23
This has been addressed by https://github.com/bitwarden/mobile/pull/1759 and should be resolved in the mobile app [v2.16.2](https://github.com/bitwarden/mobile/tree/v2.16.2). Please let us know if this crash still occurs after this update. I'm leaving this issue open as @vvolkgang mentioned until we can confirm the fix.

**Comment by aouerfelli** [comment] 2022-02-14 22:32
I thought that I installed the update before reporting, but I guess not; this was a mistake on my part. After updating and testing, I can confirm that the latest build fixed the issue for me.

**Comment by fmbarina** [comment] 2022-02-15 06:21
Happy to see progress on this, but sadly it still occasionally crashes here. Adb logcat also shows `java.lang.RuntimeException: Camera is being used after Camera.release() was called`.

Device: Asus Zenphone 3 Zoom (ZE553KL)
Operating system: Android 8
Build Version 2.16.2 (4334)

**Comment by vvolkgang** [comment] 2022-02-15 12:56
@fmbarina can you provide reproduction steps? We believe that's a different issue and we've been unable to replicate it yet.

**Comment by kosmoz** [comment] 2022-02-18 11:09
I am also experiencing this issue. 

The camera works fine until it "sees" the QR code, then the app crashes.

(2.16.2 on Xiaomi Mi5s running LineageOS 16, Android 9)

**Comment by Greenderella** [comment] 2022-05-05 16:05
This issue appears to still be present on version 2.18.0

**Comment by develop7** [comment] 2022-06-06 09:01
I'm affected by the issue as well, version 2022.05.0 on Pixel 5 running Android 12 (security update May 5, 2022). Bitwarden app crashes on first attempt to scan the QR code; scanning the code after reopening the app after crash succeeds though.

**Comment by fedemkr** [comment] 2022-06-06 20:26
Thanks a lot for all the feedback, this is happening because of a racing issue so it's quite difficult to reproduce consistently, but a fix has been applied in #1942  and will be available in June's release.

**Closed** 2022-06-07 14:46 UTC

**Comment by develop7** [comment] 2022-06-07 14:49
@fedemkr any beta releases before that?

**Comment by fedemkr** [comment] 2022-06-07 16:55
Hi, @develop7 you can grab the apk from [Github Action Artifacts](https://github.com/bitwarden/mobile/actions/runs/2455389590)  and try it to see if that solves your issue but beware that the app may not be stable given that it's a development build and it hasn't been tested thoroughly by the test team yet.
Also, we're going to ship it to the beta channel before the final June release so you can wait for that as well to have more things included and better stability (just in case here also applies that it's not the final release so issues may appear during beta testing but much less than development build)
