### ISSUE TITLE
iOS secure note window scroll bug

### ISSUE THREAD

**Issue by williammueller** [bitwarden/mobile#1436] opened 2021-06-21 13:16 UTC
## Describe the Bug

When opening a long secure note if you tap to input text anywhere it brings you to the bottom. Selecting text or editing is nearly impossible. 

## Steps To Reproduce

Open a secure note 2-3 pages long in edit mode, tap anywhere on the first page and it will move your cursor to end of file

## Expected Result

Expected to input cursor where you tap

## Actual Result

Cursor always jumps down the screen

## Environment

iPhone 11 Pro
iPhone se

Most up to date iOS and Bitwarden versions. 

## Additional Context

This has been around for over a year now

**Comment by eliykat** [comment] 2021-06-21 21:41
Thanks for the report. This is a duplicate of #1257, so I'll close it. You can continue any discussion or add any extra information to #1257.

**Closed by eliykat** 2021-06-21 21:41 UTC
