### ISSUE TITLE
Android application not logged out after account is deleted

### ISSUE THREAD

**Issue by grmpyninja** [bitwarden/mobile#737] opened 2020-02-22 19:04 UTC
I'm testing bitwarden on my mobile and wanted to test it on desktop. I forgot the password and had biometrics enabled on mobile. To recover password I decided to deleted the account. I followed the links and deleted account successfully, however the mobile app was not automatically logged out and i was still able to use biometrics to log in to the vault.

I would expect, in case of account delete, that all devices would be logged out immediately. 

1. would go for push notifications for mobile apps (haven't tested desktop apps yet)
2. re-try in case of unsuccessful (somebody can turn off my stolen device or put it into airplane mode)
3. force master password after some period of time, as e.g. from point 2, somebody can use airplane mode to disconnect from the network and then there is no way to deliver 'delete' instruction, but forcing master pass after X days would solve the issue i guess (theif needs to root the device in the meantime). Default could be off, configurable X days via settings would be awesome.

**Comment by kspearrin** [comment] 2020-02-23 02:10
Right now it will log out the next time it contacts the server (likely to sync) and sees that the user account doesnt exist.

**Comment by atjbramley** [comment] 2023-07-27 15:22
Hi @grmpyninja, 

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/mobile/issues/653 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by atjbramley** 2023-07-27 15:22 UTC
