### ISSUE TITLE
The iOS keyboard for the autofill password popup doesn’t appear in some apps when the password button on the keyboard is pressed

### ISSUE THREAD

**Issue by Jarboer** [bitwarden/mobile#1168] opened 2020-12-08 05:05 UTC
## Describe the Bug

When trying to select a password using the keyboard password button on iOS they keyboard does not show up once authenticated. So once authenticated you cannot search for a specific account or even create a new account since the keyboard doesn’t appear. I noticed it only occurs on apps that don’t automatically suggest a password (like the ProtonVPN app).

## Steps To Reproduce

1. Go to an app that doesn’t automatically suggest one of your accounts (in my cause the ProtonVPN app)
2. Click on login
3. Click on the password button on the keyboard (where typing suggestions are)
4. And observe as the keyboard doesn’t appear when searching or when your trying to create an account

## Expected Result

I’d expect the keyboard would appear so I could search for an account or be able to create an account.

## Actual Result

The keyboard never appears and so it’s not possible to search or create an account with some apps and sites.

## Screenshots or Videos

The keyboard password button I’m referring to: 
![36232A93-EB82-49F2-A3D4-96D20FEFBFD0](https://user-images.githubusercontent.com/16063018/101441847-0c02a480-38e8-11eb-8904-c1cb0a5cc002.png)

A screenshot of me trying to create an account but the keyboard won’t appear even after waiting: 
![DD95AA8C-6CAD-44F3-863A-CE5029D63F4A](https://user-images.githubusercontent.com/16063018/101441930-37858f00-38e8-11eb-9749-3379ce5bdaf2.png)
 

## Environment

- Device: iPhone 12
- Operating system: iOS 14.2
- Build Version (go to "Settings" → "About" in the app): Version: 2.7.0 (358)
- Is this a Beta release? No

## Additional Context

The main cause of this issue seems to be when apps don’t suggest an account to sign into so it seems to be related to the keyboard not appearing. This happens I think when ever a site is not suggest as seen in the above screenshot no URL was included automatically like in most apps.

**Comment by mahnoorzubair** [comment] 2020-12-08 18:26
Wow. This is amazing site for me. Good work on this webpage. Here is a detailed article on  <a href="https://technicalsain.com/how-to-change-google-chrome-themes/"> change google chrome themes</a>. Thankyou.

**Comment by herderich** [comment] 2020-12-20 18:48
I have this problem too on iPhone 12 mini (iOS 14.2.1) with Bitwarden version 2.7.0 (358).
When I try to use "Auto-fill" Feature and tap "Passwords" at the top of the keyboard, after FACE ID verification, no item is automatically matched and the password list appears directly. At this time, I tap "Search Vault" field, but no keyboard pops up anyway. And after I tap the “+” icon to try to add a new item, no keyboard pops up when I tap any field on the page anyway. During my use of Bitwarden iOS APP, this problem only appeared **in the "Auto-fill" Feature and no item was automatically matched**.
Hope this problem can be fixed as soon as possible!

**Comment by Twiglet1022** [comment] 2020-12-23 21:56
I have this issue too. Noticed it almost immediately upon upgrading from and iPhone SE (2016) to iPhone 12 mini. Never once had this problem before that.

**Comment by lilchancep** [comment] 2020-12-24 04:11
Same issue. 

iPhone 12 Pro Max
iOS 14.3
Bitwarden 2.7.2

Apps I have this issue in (will update as I encounter this issue) 

Honda Link [AppStore](https://apps.apple.com/us/app/hondalink/id750465030)

**Comment by psstarwarsisgood** [comment] 2021-01-03 01:35
Same problem here. 

Iphone 11
IOS 14.2
version 2.7.2

My issue happens exactly as described in the additional context of the original post

**Comment by SergeantConfused** [comment] 2021-01-05 15:52
Thank you all very much for bringing this to our attention. I will be marking this as a duplicate to consolidate this matter into a single issue, and we would be looking into this issue soon.

**Comment by SergeantConfused** [comment] 2021-01-05 15:52
Duplicate of #1114

**Closed** 2021-01-05 15:59 UTC
Labels: duplicate
