### ISSUE TITLE
Scanning kickstarter.com QR code for 2FA crashes Android mobile app

### ISSUE THREAD

**Issue by hoostus** [bitwarden/mobile#1242] opened 2021-01-26 04:01 UTC
## Describe the Bug

App crashes back to launcher with no error messages.

Unfortunately kickstarter.com doesn't list the codes to manually enter TOTP 😢 

## Steps To Reproduce

1. Login to kickstarter.com
2. Enable 2FA
3. Scan QR code
4. App crashes

**Comment by SergeantConfused** [comment] 2021-01-26 10:57
Hi there,

What is the make and model of your device, and which operating system version, and Bitwarden version are running, please?

Thank you in advance,

**Comment by sso-bitwarden** [comment] 2021-01-27 02:09
Possibly duplicate of https://github.com/bitwarden/mobile/issues/1228

As workaround, it will work on 2nd try.

**Comment by hoostus** [comment] 2021-01-27 02:27
> What is the make and model of your device, and which operating system version, and Bitwarden version are running, please?

Oppo Reno4 with the latest version of ColorOS 7.2 (which I think it based on Android 10). Latest version of Bitwarden from the appstore: 2.8.0 (3349).

> As workaround, it will work on 2nd try.

Unfortunately it doesn't work on the 2nd try for me. It crashes each time I try to scan it. I tried 4-5 times -- even rebooted the phone and tried again the next day in case it was gremlins in my phone or something 😄

**Comment by clayadams5226** [comment] 2021-01-29 04:46
Closing as a duplicate of #1228

**Closed by clayadams5226** 2021-01-29 04:46 UTC
