### ISSUE TITLE
iOS does not work with YubiKey 5Ci

### ISSUE THREAD

**Issue by revonoc** [bitwarden/mobile#644] opened 2019-10-30 16:12 UTC
The iOS app for BitWarden does not work with the 5Ci, which plugs into lightning port instead of using NFC. I contacted YubiKey and they replicated the problem, telling me to reach out here. I would love a fix, as I just switched from Lastpass

Btw it is advertised that it works [here on Bitwarden's site](https://help.bitwarden.com/article/setup-two-step-login-yubikey/) and [here on Yubikey's](https://www.yubico.com/works-with-yubikey/catalog/bitwarden-premium/)

Thanks!

**Comment by kspearrin** [comment] 2019-10-30 19:20
Closing, since this is a duplicate of #592 .

**Closed by kspearrin** 2019-10-30 19:20 UTC
