### ISSUE TITLE
Crashes when trying to “Export Vault”

### ISSUE THREAD

**Issue by Uricasha** [bitwarden/mobile#2843] opened 2023-10-29 20:30 UTC
### Steps To Reproduce

4. Click on '...'

### Expected Result

1. Open Bitwarden
2. Go to Settings
3. Click on “Export vault”
4. Choose file format “.csv” or “.json”
5. Enter Master Password
6. Click on Export Vault
7. iPhone (or iPad) ask user to select location for saving
8. File is saved on phone or iPad 

### Actual Result

1. . Open Bitwarden
2. Go to Settings
3. Click on “Export vault”
4. Choose file format “.csv” or “.json”
5. Enter Master Password
6. Click on Export Vault
7. Bitwarden app crashes (This happens on both iOS and iPadOS 17.1)

### Operating System

iOS

### Operating System Version

17.1

### Device

iPhone 13 Pro

### Build Version

2023.9.2 (5102)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment] 2023-10-29 22:26
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/mobile/issues/2793

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2023-10-29 22:26 UTC
Labels: bug
