### ISSUE TITLE
Unable to copy password field when re-prompted master password on Pixel 7 Pro

### ISSUE THREAD

**Issue by equetzal** [bitwarden/mobile#2752] opened 2023-09-08 05:59 UTC
### Steps To Reproduce

Case A:
1. Go to a master password protected field
2. Click on copy/view
3. Write the correct master password when prompted
4. Wait for the password to be copied/visible

Case B:
1. Go to a master password protected field
2. Click on copy/view
3. Write whatever in the master password field when prompted
4. Notice no wrong password is notified.

### Expected Result

Case A: Have the password copied into the clipboard, and be notified about that.
Case B: Be notified that the password is wrong.

### Actual Result

Case A: Prompt dismisses, anything is copied to clipboard and I'm not notified if the password was ok or wrong.
Case B: Prompt dismisses, anything is copied to clipboard and I'm not notified if the password was ok or wrong.
In certain cases the app even crashes and no feedback is provided.

### Screenshots or Videos

https://github.com/bitwarden/mobile/assets/62947298/36227380-c00d-40bf-a646-9c2b9e2d584d

### Additional Context

When I firsly installed/reinstalled the app I had any problems when trying to copy a double protected (master password re-prompt) field. But after some time (have not measured it) it starts doing the behavior of not copying anything and basically omitting any input.
I never experienced this before with my old Xiaomi phone, but since I tried Bitwarden on the Pixel this have started to happen very often.

I've already tried to clean the cache, clean all data, uninstall and reinstall and is not working. I haven't tried restore the phone but I don't want to do that.

### Operating System

Android

### Operating System Version

13

### Device

Pixel 7 Pro

### Build Version

TQ2A.230305.008.C1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment] 2023-09-08 06:02
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/6153

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2023-09-08 06:02 UTC
Labels: bug
