### ISSUE TITLE
Problem with the back button in a Pixel 2 XL

### ISSUE THREAD

**Issue by luismseoane** [bitwarden/mobile#462] opened 2019-02-13 16:58 UTC
I have a Pixel 2 XL with Android P, the issue is:

When I am in the App and I entry in a section or option, and I need to go back, if I press return button in my phone automatically the app closes. It don't return. 

What can be the problem? 

Sorry for my English, I don't talk it very well. 
Thank you.

**Comment by HobDev** [comment] 2019-03-25 10:12
@luismseoane I am running the app on pixel 2 xl. When I press back button it goes back. Only when I am on `My Valut` page , pressing back button is closing the app. It is a normal behaviour as the `My Vault` is the root page of the app

**Comment by kspearrin** [comment] 2019-06-04 15:40
Unfortunately, I am not able to reproduce the issue.

**Comment by djsmith85** [comment] 2022-03-10 23:19
Hi @luismseoane, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2022-03-10 23:19 UTC
