### ISSUE TITLE
Cannot effectively change the language within the application (Chinese)

### ISSUE THREAD

**Issue by huoxianribao** [bitwarden/mobile#3404] opened 2024-10-04 14:46 UTC
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Go to 'setting-appearance'
2. Click on 'language'
3. Click on "中文（中国）"
Tried restarting the app but it didn't change the language, it's still English
![image](https://github.com/user-attachments/assets/b295b4e3-9793-4160-912b-5483acc35dea)
![image](https://github.com/user-attachments/assets/3ed0336a-8237-4a10-b781-723436221ea8)

### Expected Result

In-app language changed to Chinese

### Actual Result

still English

### Operating System

iOS

### Operating System Version

ios17.5.1

### Device

iphone12

### Build Version

2024.9.2(1106)

**Comment by cbbit** [comment] 2024-10-04 14:53
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/ios/issues/747

This issue will now be closed.

Thanks!

**Closed by cbbit** 2024-10-04 14:53 UTC
Labels: bug
