### ISSUE TITLE
Android app goes to App homepage after selecting an autofill id-password combo or hits the back button on the page it was supposed to fill

### ISSUE THREAD

**Issue by uddinstock** [bitwarden/mobile#384] opened 2018-09-28 12:25 UTC
Here's the scenario. This is observed in chrome.

1. You browse to a website's login page, and the bitwarden icon appears in your notification bar.
2. You click on the icon and it asks for your fingerprint.
3. Once you are in the vault, you see the relevant id/pass combo for the website.
4. You select the id/password you want autofilled, amd it takes bitwarden into a weird state where bitwarden resets to it's home (the app itself) and in the background it goes back to whatever page you were previously on before logging in.

**Comment by kspearrin** [comment] 2018-09-28 12:37
I've seen this happen before too, though I am not sure why it happens yet. What autofill service are you using? Accessibility or Oreo?

**Comment by uddinstock** [comment] 2018-09-28 14:39
> I've seen this happen before too, though I am not sure why it happens yet. What autofill service are you using? Accessibility or Oreo?

I'm sorry if this sounds like a noob answer to your question but I'm not sure how I could check if I'm using `Oreo`.
Bitwarden is selected in my Autofill Settings though
```
 Settings -> General Management -> Language and Input -> Autofill Service.
```
It lists 3:
* Bitwarden
* Google
* Autofill with Samsung Pass

and out of the 3 `Bitwarden` is the one selected.

**Comment by kspearrin** [comment] 2018-09-29 02:19
It sounds like you're using Oreo (Android 8) autofill then.

**Comment by eliykat** [comment] 2021-04-29 23:09
Duplicate of #231. 

Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Closed by eliykat** 2021-04-29 23:09 UTC
