### ISSUE TITLE
Password displayed incorrectly in Android app

### ISSUE THREAD

**Issue by jensneubauer** [bitwarden/mobile#742] opened 2020-02-27 08:43 UTC
If a password contains the '<' character, that character is not shown when the password is revealed in the Android app. It is shown when the entry is edited. When the password is copied to the clipboard and pasted elsewhere, the character shows up. 

It shows normally on the web interface (both when viewing and editing).

**Comment by mportune-bw** [comment] 2020-02-28 14:25
Are you using the beta version by chance?

**Comment by jensneubauer** [comment] 2020-02-28 14:46
Sorry, I should have mentioned that. I'm using V 2.3.0 (2173) and am signed up for the beta.

**Comment by ShirokaiLon** [comment] 2020-02-28 14:52
Ah.. I bet @mportune-bw knows what the issue is already, but I imagine the characters will need to be percent-encoded before displaying... https://github.com/bitwarden/mobile/pull/686

Didn't think of that at the time ^^

**Comment by mportune-bw** [comment] 2020-02-28 15:31
Yup, working on it now 👍

**Comment by mportune-bw** [comment] 2020-02-28 20:23
Fixed in #746

**Closed by mportune-bw** 2020-02-28 20:23 UTC
