### ISSUE TITLE
iOS version ignoring Preferred Language Order setting

### ISSUE THREAD

**Issue by idiosyn** [bitwarden/mobile#979] opened 2020-06-15 05:06 UTC
The iOS version apparently ignores the Preferred Language Order setting.

## Steps To Reproduce

1. On an iOS device, go to Settings, General, Language & Region. Under Preferred Language Order, tap on Add Language... and add both "Portuguese (Brasil)" and "Portuguese (Portugal)".

2. Edit the Preferred Language Order to put "Português" on the top and "Português (Portugal)" on the second row. That will change the iPhone Language to Portuguese (Brazil).

3. Open Bitwarden.

## Expected Result

The app should appear with the European Portuguese translation (since -- I suppose -- it doesn't have a Brazilian Portuguese translation yet).

## Actual Result

The app appears in English. Apparently it is ignoring the Preferred Language Order setting. If "Portuguese (Portugal)" is set above English, the app should use "Portuguese (Portugal)".

## Screenshots or Videos

![iphone-language-order](https://user-images.githubusercontent.com/38734779/84619642-0f265600-aeac-11ea-95d9-88f473d795ee.jpg)

## Environment

- Device: iPhone SE, iPhone 6S (tested on both)
- Operating system: iOS 13.4.1
- Build Version: 2.4.3 (69)
- Is this a Beta release? No

**Comment by kspearrin** [comment] 2020-06-15 14:37
The app support both pt-BR and pt-PT today, so I imagine it should be using pt-BR for you.

**Comment by cscharf** [comment] 2020-07-09 14:31
When I test using iOS 13.4.1 on iPhone Xs the language works and switches right away for me and follows preference order, regardless of whether the Bitwarden app is open or not. I am unable to reproduce this, but I also do not have an iPhone SE or 6s to test on. Can you update to build 2.5.1 and see if this issue persists?

**Comment by cscharf** [comment] 2020-07-28 17:11
Closing this issue, if it reoccurs or continues to be a problem please feel free to reopen it.

**Comment by idiosyn** [comment] 2020-08-07 23:50
Just to let you know, I could not test it yet because the latest version on the App Store is 2.5.0 (in which the issue is not fixed).

I'll update this issue when I get to install 2.5.1.

**Comment by rccavalcante** [comment] 2020-08-12 22:05
I just experienced this problem. It happened today on my father's iPhone 7 iOS version 13.6 (Bitwarden version2.5.0 (193)). His device language is pt-BR, but BitWarden completely ignores it and shows everything in English. I even tried changing the language to pt-BR on the web version to see if it would trigger something, but it didn't change anything on the iOS app at all. It would be really nice if it could be fixed soon since it's probably a simple fix and might be crucial for some users like my parents who don't know a word in English. Also, I think it would be a great addition to add an extra setting to explictly set the desired language (what if the user wants the device in a language but Bitwarden in another one of their choice?). Let me know how I can help. Thank you!

**Comment by cscharf** [comment] 2020-08-12 22:08
Hi @rccavalcante and @idiosyn , thank you for the update, I'll re-open the issue for now. Can you please try logging out (vs. locking the vault) of Bitwarden, closing the app and re-opening/logging back in after the language change/preferred language to see if that resolves the issue?

**Comment by rccavalcante** [comment] 2020-08-12 22:14
> Hi @rccavalcante and @idiosyn , thank you for the update, I'll re-open the issue for now. Can you please try logging out (vs. locking the vault) of Bitwarden, closing the app and re-opening/logging back in after the language change/preferred language to see if that resolves the issue?

I just did that, but it still doesn't work as expected. Earlier today, I also tried uninstalling and reinstalling the app, but that didn't work either.

**Comment by cscharf** [comment] 2020-08-14 14:02
Thanks @rccavalcante , will need to be able to reproduce this for troubleshooting and root cause analysis as to why the language setting is not being passed to the Bitwarden app in this instance OR the language resource is not being found/loaded (likely one of those 2, but not sure). I'll work on getting a hold of that iOS version to test on and if necessary track down that device.

**Comment by idiosyn** [comment] 2020-08-19 05:59
The problem appears to affect specifically pt-BR.

I have tried changing the iPhone Language to other languages and they all worked fine.

It may have something to do with the confusion between pt, pt-BR and pt-PT:

https://stackoverflow.com/questions/21381955/xcode-project-localized-to-portuguese-brazil-why-still-show-english

https://developer.apple.com/forums/thread/24466

**Comment by idiosyn** [comment] 2020-09-16 22:36
@cscharf Did you get a chance to look at this?

> The problem appears to affect specifically pt-BR.
> 
> I have tried changing the iPhone Language to other languages and they all worked fine.
> 
> It may have something to do with the confusion between pt, pt-BR and pt-PT:
> 
> https://stackoverflow.com/questions/21381955/xcode-project-localized-to-portuguese-brazil-why-still-show-english
> 
> https://developer.apple.com/forums/thread/24466

Also, I'd like to add my support to this suggestion by @rccavalcante:

> Also, I think it would be a great addition to add an extra setting to explictly set the desired language (what if the user wants the device in a language but Bitwarden in another one of their choice?).

**Comment by cscharf** [comment] 2020-09-16 22:55
> Also, I think it would be a great addition to add an extra setting to explictly set the desired language (what if the user wants the device in a language but Bitwarden in another one of their choice?).
@rccavalcante , @idiosyn , you're more than welcome to vote for this or provide comments within our community forum: https://community.bitwarden.com/t/change-app-language-without-changing-system-language/13785

As far as the issue regarding the confusion between pt-BR, pt and pt-PT, I personally tested on my device and emulator running a few different versions of iOS and have not been able to replicate this issue. Do you have multiple Portuguese language locale's enabled on the same device?

**Comment by cscharf** [comment] 2020-09-16 23:07
Nevermind the question @idiosyn, I just triple checked, our translations coming from crowdin are only providing `pt-BR` and `pt-PT`, and the articles/posts you linked clearly state that iOS through Xcode will only support pt and pt-PT, so I will work on mapping the `pt-BR` and duplicating that to `pt` either in crowdin or part of a DevOps build task.

**Closed** 2020-09-29 14:58 UTC

**Comment by mvlaza** [comment] 2020-12-15 00:59
Hello guys,
I'm not sure if this is the right place to ask, but this issue should be fixed by now for everyone? Because I'm facing exactly the same situation here: iOS (iPhone XR with 14.2) configured for Brasilian portuguese, latest bitwarden app version from app store (not beta) and bitwarden interface texts are all still in english.
Thanks for your help!

**Comment by vachan-maker** [comment] 2020-12-15 01:12
> 
> 
> Hello guys,
> I'm not sure if this is the right place to ask, but this issue should be fixed by now for everyone? Because I'm facing exactly the same situation here: iOS (iPhone XR with 14.2) configured for Brasilian portuguese, latest bitwarden app version from app store (not beta) and bitwarden interface texts are all still in english.
> Thanks for your help!

![image](https://user-images.githubusercontent.com/65799568/102155044-b5c1d280-3ea0-11eb-919f-713435a2e4c3.png)

**Comment by tgreer-bw** [comment] 2021-05-20 14:39
@cscharf we should probably rename and reopen this one, unless you'd prefer to use #1406?
