### ISSUE TITLE
Android Chrome beta not recognized

### ISSUE THREAD

**Issue by kermus** [bitwarden/mobile#310] opened 2018-05-07 09:14 UTC
Hey! problems with the Google Chrome beta browser when trying to log on to any page bitwarder announces   "no found item com.chrome.beta" or something.
Chrome version 67.0.3396.29
Bitwarden versio 1.16.0

**Comment by kspearrin** [comment] 2018-05-07 11:42
We already support Chrome Beta for autofill. Does this happen every time or only sometimes?

**Comment by kylezimmerman** [comment] 2018-05-29 04:37
I'm having the same issue for non-beta Chrome. It detects login fields, but when I try to log in I get a similar error.

It's happening every time when using a fullscreen chrome app (added through 'Add to Desktop').

The error is:

"Items for com.android.chrome"
"There are no items in your valut for com.android.chrome"
[ADD AN ITEM] (button)

**Comment by andrebrait** [comment] 2018-06-02 14:13
Exact same here.

Going back to chrome and trying again usually makes Bitwarden recognize it again, but sometimes the first try results in it recognizing the Chrome app as the website I'm trying to fill a password for.

**Comment by ryanpcmcquen** [comment] 2018-06-02 18:36
Looks like a duplicate of https://github.com/bitwarden/mobile/issues/242.

**Comment by nvllsvm** [comment] 2018-06-02 19:28
Same issue with Firefox Klar (org.mozilla.klar).

**Comment by rcdailey** [comment] 2018-07-25 13:32
I'm seeing this issue on stable chrome on Android 8.1

**Comment by salmelo** [comment] 2018-10-04 08:57
Similar problem on stable chrome, Android 9. Doesn't happen with every site, but the sites it does happen on it happens every single time, haven't figured out a way to get them to recognize the actual site instead of `com.android.chrome`.

So far I've tested it on Domino's, which works fine, and on http://gobbln.com/forum/ and http://forum.theonyxpath.com which both fail. (I have no idea if their being forums is relevant.)

**Comment by Niek** [comment] 2019-01-29 19:51
Same issue here, Android 9

**Comment by Muurtegel** [comment] 2019-12-26 14:07
I just installed Bitwarden on an Android device with Chrome 79.0.3945.93 and I run into the same issue. Sometimes it works perfectly fine, other times it says it can't find items for com.android.chrome.

Any ideas on how to solve this?

**Comment by eliykat** [comment] 2021-04-29 23:08
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Closed by eliykat** 2021-04-29 23:08 UTC
