### ISSUE TITLE
Android Poor Performance 

### ISSUE THREAD

**Issue by 0xA354** [bitwarden/mobile#453] opened 2019-01-27 20:58 UTC
I have 30 entries in my bitwarden vault. When I'm scrolling down on my Android App it feels very laggy. Even when I'm trying to open an entry.

**Comment by mds08011** [comment] 2019-01-30 01:20
Are you able to provide more information?  I have ~50 entries in my app and do not notice any issues.

**Device:** Google Pixel 2
**Android version:** 9.0
**Bitwarden version:** 1.21.0

**Comment by 0xA354** [comment] 2019-01-30 01:40
Device: Samsung Galaxy s7 edge
SuperMan-Rom
Android version: 7.0
Bitwarden version: 1.21.0

**Comment by al-bashkir** [comment] 2019-03-30 19:24
Same problem.
Device: OnePlus 3T
Android version: 9.0 (OxygenOS 9 beta)
Bitwarden version: 1.22.0

**Comment by kspearrin** [comment] 2019-06-04 15:38
Can you try v2.0 from play store beta? is it better?

**Comment by PopeRigby** [comment] 2019-06-15 00:49
I'm using v2 and it seems even worse. Everything feels slower.

**Comment by Xeunyx-Cypher** [comment] 2020-08-02 17:21
Yes! I'm having similar. When I try to open my Vault at the start. It takes 15-20 seconds. I have 246 logins and only 3 notes. 
Bitwarden v2.5.0 on Redmi 4A

**Comment by djsmith85** [comment] 2022-03-10 23:18
I'm closing this now due to age, but if this is still an issue please feel free to re-open. Please provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2022-03-10 23:18 UTC

**Comment by Oakwas** [comment] 2022-04-23 22:50
I'm experiencing the same issue
Scrolling is very laggy

**Comment by fedemkr** [comment] 2022-04-25 20:04
Hi thank you for the update, could you provide us with the device model and operative system version where you experience the lagginess?

**Comment by Oakwas** [comment] 2022-04-25 20:10
I'm using a galaxy a21s and running android 11

**Comment by Surferlul** [comment] 2024-10-13 14:41
I also have performance issues, I'm on a Pixel 8
