### ISSUE TITLE
Search Result Kebabs No Longer Functioning

### ISSUE THREAD

**Issue by jhspyhard** [bitwarden/mobile#2488] opened 2023-04-21 14:05 UTC
### Steps To Reproduce

OS: Android 13 (Pixel 7Pro)
Version: Play Store 2023.3.2

**Reproduction Steps**:
1. Login to Bitwarden on Android
2. Click on the magnifying glass next to your account initials to start a vault item search.
3. Search for a particular vault item by starting to type the name of the item.
4. When a result is produced, click search result item's 3-dot kebab (not the vault kebab).

### Expected Result

A context menu allowing quick copying of username, password, and other items is popped up.

### Actual Result

Nothing happens.

### Screenshots or Videos

n/a

### Additional Context

n/a

### Operating System

Android

### Operating System Version

Android 13

### Device

Pixel 7 Pro

### Build Version

com.x8bit.bitwarden v2023.3.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by joshuabjordan** [comment] 2023-04-21 14:22
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/mobile/issues/2475.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2023-05-18 15:06 UTC
Labels: bug
