### ISSUE TITLE
Android app on Galaxy S22 Ultra: app crashes when adding new password through browser modal. 

### ISSUE THREAD

**Issue by goshtasb** [bitwarden/mobile#2180] opened 2022-11-10 13:12 UTC
### Steps To Reproduce

- using chrome browser, try signing up for a new account anywhere
- when directed to enter new username and password, clock on the small bitwarden modal pop-up that shows up under the entry box ("auto-fill with bitwarden")
- you'll be redirected to bitwarden vault to see if you already have existing account for that site or if you need to create a new one
- click to "add an item"
- to generate new password if you click on the "refresh/regen" button that regens a new password. Result: the app exits to the main bitwarden login page
- repeat steps and the 2nd time clicking on the "refresh/regen" button app crashes

### Expected Result

To get the password regen page and pick length and type of password needed for the new login

### Actual Result

App crashes. 

However, if you open bitwarden manually, the app does not crash. Only crashes when you open bitwarden through pop-up modal ("auto-fill with bitwarden")

### Screenshots or Videos

![Screenshot_20221110_050750_Chrome](https://user-images.githubusercontent.com/12802195/201100469-c0605bb2-d873-4c96-9f61-a2b0daee981e.jpg)

### Operating System

Android

### Device

Samsung Galaxy S22 Ultra 

### Build Version

2022.10.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by realansgar** [comment] 2022-11-21 15:57
I believe this is a duplicate of #2149 and was fixed in #2150. Since Bitwarden only releases monthly, you have to wait for the November release 2022.11 to receive the fix (see [this contributor response](https://github.com/bitwarden/mobile/issues/2194#issuecomment-1316944320)).

**Comment by goshtasb** [comment] 2022-11-21 16:01
@realansgar yes, you are absolutely correct. It does seem like the same bug. Thank you for your response.

**Comment by djsmith85** [comment] 2022-11-21 16:37
Closing this as duplicate of #2149.

**Closed by djsmith85** 2022-11-21 16:37 UTC
Labels: bug
