### ISSUE TITLE
[Android] Crash when viewing password of entry with "Master password re-prompt" 

### ISSUE THREAD

**Issue by nikitawootten** [bitwarden/mobile#2777] opened 2023-09-18 13:52 UTC
### Steps To Reproduce

1. Go to the entry which has "Master password re-prompt" enabled
2. Press the view or copy password buttons
3. Fill in your master password as prompted
4. Crash

### Expected Result

My password should become visible

### Actual Result

The application crashes.

### Additional Context

This only happens on mobile, I am able to view my password on the web app and extension fine.

### Operating System

Android

### Operating System Version

Android 13

### Device

Pixel 6 Pro

### Build Version

2023.8.0 (7466)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment] 2023-09-18 13:55
Duplicate of https://github.com/bitwarden/mobile/issues/2733

**Comment by djsmith85** [comment] 2023-09-18 13:55
Hi @nikitawootten,

This seems to have previously been reported with https://github.com/bitwarden/mobile/issues/2733 and a fix has been issued with https://github.com/bitwarden/mobile/pull/2713 which will be included in the next release (2023.9)

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2023-09-18 13:55 UTC
Labels: bug
