### ISSUE TITLE
[iPadOS] Can't change select box value in split view or "drawer mode"

### ISSUE THREAD

**Issue by Crocmagnon** [bitwarden/mobile#992] opened 2020-06-24 13:17 UTC
## Describe the Bug

On iPadOS, when using the app side by side with another one or in "drawer mode", it's impossible to change select boxes values.

## Steps To Reproduce

1. Open Bitwarden side by side with any other app
2. Create a login
3. Tap on the type (passphrase vs password)
4. Change the value
5. You can't validate the new value.

## Expected Result

The user should be able to change select box value in split view or "drawer mode".

## Actual Result

Can't change values, must go to full screen to change the value (the "Done") appears at the top right of the selection popup.

## Screenshots or Videos

Github doesn't allow mp4 and limits GIF size so there you go:
* https://cloud.augendre.info/s/eNpBoSxeGC8ENTs

## Environment

- Device: iPad Air 3
- Operating system: iPadOS 13.5.1
- Build Version: 2.4.3 (69)
- Is this a Beta release? ❌

**Comment by cscharf** [comment] 2020-06-24 14:58
I was able to reproduce this, however I was not able to find any other iPad apps that use the built-in selector, each had rolled their own, so I wasn't able to compare to any others where this may also be an issue.

**Comment by Crocmagnon** [comment] 2020-06-24 16:05
I found YNAB which has what looks like a native date picker and doesn’t suffer from this issue:

https://u.pcloud.link/publink/show?code=XZA6cUkZO6X62hnU29VoUKgz3cxVHLFNguH7

**Comment by eliykat** [comment] 2021-11-24 01:48
There have been no further reports of this in some time, and we've been unable to reproduce the issue using Bitwarden version 2.13.1 on iOS 15. I'm going to close this, however if you are still experiencing the issue, please reopen it and provide any further information to help us reproduce it.

**Closed by eliykat** 2021-11-24 01:48 UTC

**Comment by Crocmagnon** [comment] 2021-11-26 09:46
I can confirm this issue is fixed.
