### ISSUE TITLE
Cannot save new login if personal ownership is disabled

### ISSUE THREAD

**Issue by Gerardv514** [bitwarden/mobile#3066] opened 2024-03-09 03:31 UTC
### Steps To Reproduce

1) disable personal ownership in the organization policy
2) go to any site (cnn.com) in mobile Safari and try to create new login using Bitwarden extension

### Expected Result

Login saved

### Actual Result

Extension hangs on saving new login
New login is not saved

### Additional Context

Extension does not offer to set the collection for the new login and it is mandatory when personal ownership is disabled.

Proposed Solution(s):

Add the ability to select collections for the new item
Add the ability to define default collection for the new items (per organization, for the person or both). This collection should be applied to new items by default if not specified otherwise.

### Operating System

iOS

### Operating System Version

17.4

### Build Version

 Version: 2024.2.0 (6100)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment] 2024-03-11 10:26
Duplicate of https://github.com/bitwarden/mobile/issues/1874

**Comment by djsmith85** [comment] 2024-03-11 10:26
@Gerardv514 Please do not open duplicate issue. I have passed your feedback from here and the forums on to the product team.

**Closed by djsmith85** 2024-03-11 10:26 UTC
Labels: bug

**Comment by Gerardv514** [comment] 2024-03-11 10:32
Only way to get someone to respond 🤷‍♂️
