### ISSUE TITLE
Special characters excluded from view

### ISSUE THREAD

**Issue by wzwick** [bitwarden/mobile#3365] opened 2024-07-27 10:36 UTC
### Production Build

- [ ] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

create a new login credential
use any email address
in the password use `<>` together

### Expected Result

expected result is part<>part

### Actual Result

actual result is partpart

the <> is ignored as code

### Additional Context

if you use <partpart>
the result is partpart> highlighted in red

### Operating System

Android

### Device

Asus Zenfone 9

### Build Version

10746

**Comment by SergeantConfused** [comment] 2024-07-27 13:49
Hello @wzwick,

Thank you for your report. This report seems to be a duplicate of [this GitHub report](https://github.com/bitwarden/mobile/issues/3110); If there's anything you'd like to add, such as screenshots or video recordings of the screen, please feel free to add them to that existing GitHub report so that they'd be reviewed by the Bitwarden Engineering department.

This report will now be closed as a duplicate.

Thank you again,

**Closed by SergeantConfused** 2024-07-27 13:49 UTC
Labels: bug
