### ISSUE TITLE
The latest Android APP (2.3.1) cannot automatically fill in the account and password.

### ISSUE THREAD

**Issue by qw4096** [bitwarden/mobile#784] opened 2020-03-19 04:03 UTC
The latest Android APP (2.3.1) cannot automatically fill in the account and password. Specifically, when the input box is clicked, the auto-fill window pops up quickly and disappears. There is no time to choose.
Model is Huawei honor V20, system version Android 10

**Comment by Picasso59** [comment] 2020-03-19 23:07
Having the same issue. Android 10, OnePlus 6T, using Chrome.

**Comment by Picasso59** [comment] 2020-03-19 23:15
I've just updated to Chrome 80.0.3987.149 since my post a few minutes ago. It is working now!

**Comment by dkoppenh** [comment] 2020-03-20 03:41
Left this on the community forum, but copying here:
The latest update also broke the pop-up for me. Like others have reported, it appears for a split second and then disappears.

At least in the past, I could use the notification to autofill.
LG V40 Android 9
Brave 1.5.9 based on Chrome 80.0.3987.132
Firefox 68.6

Interestingly, Chrome 80.0.3987.149 works

**Comment by Picasso59** [comment] 2020-03-20 08:34
A follow up to my earlier posts. The problem eventually reappeared with Chrome 80...149. However, I disabled the accessibility setting and left the overlay setting active. This has it working again for me.

Perhaps of interest to the Devs, before I disabled accessibility, I found that clearing the phone's "recent items" allowed it to work temporarily.

**Comment by jeffshead** [comment] 2020-03-20 13:45
**Android Pie on Pixel XL**

Same issues that I reported here (https://github.com/bitwarden/mobile/issues/683), with videos,  still exist. The only difference with v2.3.1, is that the pop-up to select the vault is now persistent but auto-fill failures are much more frequent. Actually, the pop-up usually remains on the screen when it should not and it is usually in the way and covering the form submission button. I've even seen the pop-up remain on the Android home screen when there is no app or form present. The persistent notification option was less intrusive -- I wish that was still an option.

Sometimes auto-fill works. Sometimes I have to perform the [touch the persistent _**Auto-fill with Bitwarden**_ pop-up on the form and then select the correct login from the vault] cycle 4-5 times before it finally fills the form.

If I'm already logged into the Android BW app, the list of matching logins still flashes above the persistent pop-up for a split-second and disappears as depicted in the videos I mentioned above.

Sometimes when I touch the persistent _**Auto-fill with Bitwarden**_ pop-up on the form and then select the correct login from the vault, I'm brought back to the form with a list of matching logins above the persistent _**Auto-fill with Bitwarden**_ pop-up rather than the form being auto-filled, as it should be.

Unfortunatly, this latest update makes using BW on Android MORE inconvenient for many of us.

**Comment by THEOCKID** [comment] 2020-03-21 03:26
Got that same "flash and gone" on my samsung galaxy S20+ but I'm running Opera 56.1.2780.59589  .  I never run Chrome.

**Comment by THEOCKID** [comment] 2020-03-21 03:27
Also, I downgraded by BW to 2.2.8 (2136) and it works fine; gives me 3 options For Auto-fill Accessibility Service: Always Scan (off), Persist Notification (on, which seems to work best for me) and Scan When Password Field Focused).  If I recall correctly, none of these 3 options were available on the newest BW release.  :(

**Comment by THEOCKID** [comment] 2020-03-21 03:28
Sorry, guess I'm too old to be a beta-tester anymore.  BW is mission-critical to me, it's gotta be stable.

**Comment by immanuelfodor** [comment] 2020-03-22 05:35
Same issue as OP, the small popup under the form input appears, then immediately disappears, can't fill the form as I have zero time to tap on it. Oneplus 7

**Comment by immanuelfodor** [comment] 2020-03-22 05:46
Here it is on sceen record. 

Brave (Chromium): https://sendvid.com/75dgxgh8
Firefox: https://sendvid.com/dr6ljjgx

**Comment by tomo92s** [comment] 2020-03-22 11:27
Please restore old notification option

**Comment by guiggs** [comment] 2020-03-22 22:13
I'm having the exactly same problem. Samsung S8 with Android 9. Doesn't work on Firefox, Kiwi or Bromite.

**Comment by tomo92s** [comment] 2020-03-23 06:21
![IMG_20200322_121700](https://user-images.githubusercontent.com/32452522/77287880-e3456b00-6cd6-11ea-81ba-1f11083272bb.jpg)
I think is over...;/

**Comment by lfrancke** [comment] 2020-03-24 08:20
It works for me on a Samsung Galaxy Tab 3 (Android 9) but it doesn't work with a Pixel 4 (Android 10). Both of them unmodified (no root etc.).

On the tablet it doesn't work reliably though and the experience is noticeably worse than before. In many apps the username and password fields are on separate dialogs. I only get the popup for the password field. For the username I don't get anything and have to manually open the app and manually search & copy in there.

The option for the persistent notification is gone which would have made this a bit easier.

Happy to provide more input, the way it is currently working makes the app basically unusable for my devices.

**Comment by MeiRos** [comment] 2020-03-26 00:17
Same problem with Honor 8A and Bromite.
Does anyone have an idea, why this happens?

**Comment by immanuelfodor** [comment] 2020-03-28 13:43
Do you guys know any workaround or temporary fix? This bug is one of the most annoying one I've ever had.

**Comment by tomo92s** [comment] 2020-03-28 13:57
> Do you guys know any workaround or temporary fix? This bug is one of the most annoying I've ever had.
Back to v2.2.8, create clone and that's it

**Comment by WarmongeringBeaver** [comment] 2020-03-29 00:41
Same problem here. 

The pop-up appears, then vanishes in about ~five nanoseconds.

Since it's the only secure and usable way of using BW (to my knowledge), it's quite annoying...

**Comment by ContentPersonality2** [comment] 2020-03-29 08:59
Please bring back the old system as an option, especially the consistent notification version because that was the most reliable. I'm going to use the outdated client for now.

**Comment by mateusz-owczarek** [comment] 2020-03-31 08:03
I have the same problem. Device info:

- Galaxy S7 (SM-G930F)
- Chrome 80.0.3987.149
- Android 8.0.0
- Bitwarden 2.3.1

**Comment by MisteurZZ** [comment] 2020-04-01 09:45
Same problem, with a Huawei P30 Pro, android 10.
I've downgraded to 2.2.8

**Comment by Nyar233** [comment] 2020-04-04 00:08
enable popup windows in background

**Comment by tomo92s** [comment] 2020-04-04 05:42
> You can try giving the bitwarden app permission to pop up in the background.

That not working. This is app issue

**Comment by victor-bayas** [comment] 2020-04-05 14:52
Autofill is working for me but it doesn't detects Vivaldi Snapshot 2.12 (com.vivaldi.browser.snapshot) as a browser app thus showing results only for vivaldi.net.

Android App: 2.3.1
Android: One UI 2 with Android 10
Device: SM-G970F

**Comment by superm1** [comment] 2020-04-06 16:05
Since #715 got duplicated here, just to leave this link for people.  _This looks to be an Android autofill service or chrome issue_:
https://bugs.chromium.org/p/chromium/issues/detail?id=1015381

It happens in a variety of browsers and often restarting the browser kicks it back to life.

**Comment by immanuelfodor** [comment] 2020-04-06 16:41
Since it worked one version earlier on a variety of browsers, and only Bitwarden got updated in the meantime, and it works again when downgraded on the same set of browsers, I don't think its a Chrome/FF issue, the change mentioned in the release notes (rewrite) is what doesn't work.

**Comment by Picasso59** [comment] 2020-04-06 16:57
I posted nearly 3 weeks ago when I was having this problem. I've had it working (almost) since then.

I switched off all the autofill permissions and switched off my phone. I restarted into Recovery and wipe the cache partition. When the phone restarted I enabled all the Bitwrden autofill permissions.

I'm now on Chrome 80.0.3987.162 (Oneplus 6T Android 10)

The only anomaly I'm seeing is that a grey box occasionally shows for a few seconds asking me to enable autofill, which it already is. However, BW is mainly usably.

**Comment by superm1** [comment] 2020-04-06 17:15
> Since it worked one version earlier on a variety of browsers, and only Bitwarden got updated in the meantime, and it works again when downgraded on the same set of browsers, I don't think its a Chrome/FF issue, the change mentioned in the release notes (rewrite) is what doesn't work.

The thing is it's intermittent - particularly if the browser has been running a while.  There have been several instances that someone claims "Upgrading chrome fixed it for me"!  Upgrading the app typically kills the process and restarts it, so that's why it works for a bit.
And sure enough I upgrade too and it's working _for a short period of time_.  Then eventually I switch apps, or come into the browser another way and the issue happens again. 

And this has been a problem with LP and Bitwarden both for me.  I experienced it with LP and continue to experience with Bitwarden.

**Comment by mportune-bw** [comment] 2020-04-06 17:34
Here's a link to a recent build containing some accessibility fixes (since it's taking too long for Google to approve beta releases).  I'd be interested if this improves the accessibility overlay's behavior for you guys.

https://ci.appveyor.com/api/buildjobs/taawbjdls9ixmlao/artifacts/com.x8bit.bitwarden.apk

**Comment by superm1** [comment] 2020-04-06 17:38
(FYI My comments above were not based on the accessibility overlay; they were for native android password filling API)

**Comment by tomo92s** [comment] 2020-04-06 18:06
> Here's a link to a recent build containing some accessibility fixes (since it's taking too long for Google to approve beta releases). I'd be interested if this improves the accessibility overlay's behavior for you guys.
> 
> https://ci.appveyor.com/api/buildjobs/taawbjdls9ixmlao/artifacts/com.x8bit.bitwarden.apk

Still not working (Redmi Note 4X - Android 7.0)

**Comment by ratenfanger** [comment] 2020-04-06 18:16
> Here's a link to a recent build containing some accessibility fixes (since it's taking too long for Google to approve beta releases). I'd be interested if this improves the accessibility overlay's behavior for you guys.
> 
> https://ci.appveyor.com/api/buildjobs/taawbjdls9ixmlao/artifacts/com.x8bit.bitwarden.apk

I had the same problems as described in this issue. I tried this version for some minutes and all sites which did not work before are working flawlessly now!

Great work! Thank you very much!

Using Firefox on Android 8.1.

**Comment by Picasso59** [comment] 2020-04-06 18:21
> Here's a link to a recent build containing some accessibility fixes (since it's taking too long for Google to approve beta releases). I'd be interested if this improves the accessibility overlay's behavior for you guys.

It seems to be working as before. See my comment above. I still get an intermittent warning at the bottom of my screen relating to the Autofill Accessibility Service. It is enabled with permission granted. It doesn't seem to affect the working of BW but it would seem to be an incorrect warning.

**Comment by jeffshead** [comment] 2020-04-06 18:23
BW on my Pixel XL has always been really flaky. Even with this latest v2.3.1 (2295) beta. It seems to behave exactly as the previous version. The auto-fill box never appears sometimes. Sometimes if flashes a couple of times and stays on the screen and sometimes it flashes and does not come back.

I still get the gray pop-up, intermittently, that says “BW needs your attention -- see auto-fill accessibility service…” even though both BW settings are enabled and BW is the only auto-fill enabled app on the phone.

Sometimes I also get, “No items in your vault for --“even though matching logins do exist and they do work most of the time. Sometimes auto-fill sees a match but it does not fill in any fields. Sometimes it fills in only the username, sometimes in fills in both the username and password.

Roboform worked nearly perfect on the same phone so I can’t see this being a phone issue or a conflict with something else.

**Comment by mportune-bw** [comment] 2020-04-06 18:30
Thanks everyone for the feedback.  If you haven't already can you specify if you're using the autofill service, the autofill accessibility service, or both?

**Comment by MisteurZZ** [comment] 2020-04-06 18:34
> Here's a link to a recent build containing some accessibility fixes (since it's taking too long for Google to approve beta releases). I'd be interested if this improves the accessibility overlay's behavior for you guys.
> 
> https://ci.appveyor.com/api/buildjobs/taawbjdls9ixmlao/artifacts/com.x8bit.bitwarden.apk

It seems to work for me.
Thanx

**Comment by jeffshead** [comment] 2020-04-06 18:34
Both. Fills fewer forms with only one enabled.

**Comment by Picasso59** [comment] 2020-04-06 18:37
> Thanks everyone for the feedback. If you haven't already can you specify if you're using the autofill service, the autofill accessibility service, or both?

Using both.

**Comment by mportune-bw** [comment] 2020-04-06 18:51
BTW if you're on Android 7.0+ we added an Auto-fill tile to the quick settings panel.  Since it's always present (once enabled) it will function like the old auto-fill notification, except without the battery drain.

**Comment by tomo92s** [comment] 2020-04-07 05:16
> BTW if you're on Android 7.0+ we added an Auto-fill tile to the quick settings panel. Since it's always present (once enabled) it will function like the old auto-fill notification, except without the battery drain.

So when can we expect a fix? On my Redmi Note 4X with Android 7.0 notification still not appearing. I had to go back to version 2.2.8.

**Comment by mportune-bw** [comment] 2020-04-07 13:34
> On my Redmi Note 4X with Android 7.0 notification still not appearing.

The quick settings tile isn't a notification, it's a tile that you have to enable it via the quick settings panel. 
 Google led me here for the Redmi Note 4X:

https://www.gadgetdetail.com/xiaomi-redmi-note-4-change-quick-toggles-notification-bar/

**Comment by tomo92s** [comment] 2020-04-07 14:36
> > On my Redmi Note 4X with Android 7.0 notification still not appearing.
> 
> The quick settings tile isn't a notification, it's a tile that you have to enable it via the quick settings panel.
> Google led me here for the Redmi Note 4X:
> 
> https://www.gadgetdetail.com/xiaomi-redmi-note-4-change-quick-toggles-notification-bar/

I've always had it turned on

**Comment by qw4096** [comment] 2020-04-07 15:04
> 
> 
> Here's a link to a recent build containing some accessibility fixes (since it's taking too long for Google to approve beta releases). I'd be interested if this improves the accessibility overlay's behavior for you guys.
> 
> https://ci.appveyor.com/api/buildjobs/taawbjdls9ixmlao/artifacts/com.x8bit.bitwarden.apk

Thanks, it's working now

**Comment by mportune-bw** [comment] 2020-04-08 13:51
@Picasso59 @jeffshead Can you provide some examples of websites and/or apps that trigger the behavior you're seeing?

**Comment by Picasso59** [comment] 2020-04-08 16:02
> @Picasso59 @jeffshead Can you provide some examples of websites and/or apps that trigger the behavior you're seeing?

It is intermittent. I don't recall any apps but I use fingerprint login for my most used ones.

https://bbc.co.uk If I try to sign in to my account, usually when I touch the password box, I will see the BW warning. It is intermittent as I say. Refreshing the page can sometimes show the alert. It happens when BW is both locked and unlocked.

**Comment by Picasso59** [comment] 2020-04-08 16:05
> @Picasso59 @jeffshead Can you provide some examples of websites and/or apps that trigger the behavior you're seeing?

itv.com and github.com show the same behaviour.

**Comment by mportune-bw** [comment] 2020-04-08 17:23
@Picasso59 Thanks, I'm now seeing the intermittent toast message on itv.com (curiously only on a pixel 3, and only on itv.com - the others are fine, and all three are fine on a galaxy s10 running the same version of Chrome).  Looking into it.

**Comment by tomo92s** [comment] 2020-04-08 17:35
Can someone explain why version 2.2.8 displays the icon on notification bar correctly and version 2.3.1 no longer? Redmi Note 4X

**Comment by Picasso59** [comment] 2020-04-08 17:39
> @Picasso59 Thanks, I'm now seeing the intermittent toast message on itv.com (curiously only on a pixel 3, and only on itv.com - the others are fine, and all three are fine on a galaxy s10 running the same version of Chrome). Looking into it.

FYI I'm using OnePlus 6T (Android 10, most recent firmware) and Chrome 80.0.3987.162 (most recent). There are times the warning show for a few seconds, then disappears. At other times it shows briefly, but is flashing during that time.

**Comment by jeffshead** [comment] 2020-04-08 18:11
The username and password are filled when using a desktop. Only the
username gets filled on Android:

https://www.righteverywhere.com

Is there a way to provide a URL, privately? The web page I would like to
share with you is not indexed and I'd like to keep it that way.

**Comment by mportune-bw** [comment] 2020-04-09 19:13
@Picasso59 @jeffshead Here's another build to try.  Let me know if this improves anything for you.

https://ci.appveyor.com/api/buildjobs/0lc6dt7nnuckgedd/artifacts/com.x8bit.bitwarden.apk

@jeffshead If this still isn't working I'll find a way for you to PM me a URL.

**Comment by Picasso59** [comment] 2020-04-09 19:44
> @Picasso59 @jeffshead Here's another build to try. Let me know if this improves anything for you.

I've hammered a few logins and it seems to be working well. After installation, I cleared the storage and cache, followed by restarting the phone. Auto-fill service: enabled. Overlay permission: granted. Auto-fill accessibility service: off. If I enable the accessibility service I see the BW warning again, but it works fine without it.

**Comment by Snuupy** [comment] 2020-04-12 13:05
Alternate proposal:

Use the quick settings tile to detect the current app and autofill the password.

There is currently a Bitwarden tile ("My Vault") that opens the Bitwarden app. If you are set on removing the notification, perhaps a tile icon could be set to do the same thing: read the screen context/app bundle name and autofill the login.

**Comment by Snuupy** [comment] 2020-04-12 13:11
> > On my Redmi Note 4X with Android 7.0 notification still not appearing.
> 
> The quick settings tile isn't a notification, it's a tile that you have to enable it via the quick settings panel.
> Google led me here for the Redmi Note 4X:
> 
> [gadgetdetail.com/xiaomi-redmi-note-4-change-quick-toggles-notification-bar](https://www.gadgetdetail.com/xiaomi-redmi-note-4-change-quick-toggles-notification-bar/)

This tile does not autofill/read the app bundle. It only opens "My Vault".

**Comment by mportune-bw** [comment] 2020-04-12 14:39
@Snuupy There's a third tile labeled "Auto-fill" in the most recent version linked above.  Once enabled it performs the same function that the notification used to.

**Comment by Snuupy** [comment] 2020-04-15 04:45
@mportune-bw I believe I have run into a syncing bug specifically when there are more than 42717 lines of JSON in the database file. I have reproduced this on 2 separate servers (Bitwarden official + bitwarden_rs that I self-host) and on 3 bitwarden android versions: 2.2.8 (2136), 2.3.1 (2257), and 2.3.1 (2299)

The results are as follows:
2136: syncs with both servers with database export files > 42717 lines long
2257: syncs with both servers with database export files > 42717 lines long
2299: fails on databases > 42717 lines long (at least for my database)
The error received is: "Syncing failed".

Downgrading (obviously) fixes this problem, but does not allow me to use the quick settings tile to auto-fill my logins.

I originally thought it was my database that was corrupted, but any combination of my logins (as long as < 42717 lines long) works. The second I add 1 more login such that it is longer than 42717 lines, it gives me a syncing error. I have spent several hours debugging this and am happy to provide logs if you can direct me to instructions that tell me how to provide them.

**Comment by dexterwick** [comment] 2020-04-15 15:04
> @Picasso59 @jeffshead Here's another build to try. Let me know if this improves anything for you.
> 
> https://ci.appveyor.com/api/buildjobs/0lc6dt7nnuckgedd/artifacts/com.x8bit.bitwarden.apk
> 
> @jeffshead If this still isn't working I'll find a way for you to PM me a URL.

Apparently solved for me, I will continue testing, tks!

**Comment by mportune-bw** [comment] 2020-04-24 13:09
The Google Play beta has been updated with the latest accessibility/autofill fixes (build 2353).

**Comment by nkm8** [comment] 2020-04-24 13:32
I tried the latest beta (2.3.1) on a Pixel 3 (Android 10) and I am still seeing issues. Specifically, http://www.costco.com is consistently reproduceable when trying to log in. STR:
- Focus password field (no BW prompt)
- Change input focus to different field, then back to password field (no BW prompt - sometimes this works on other sites)
- Try new 'Auto-fill' BW quick-setting tile
- BW opens, prompts for fingerprint
- BW main screen opens and displays toast message "no password fields detected"
- I can manually search and copy my password here, but this is annoying
- Tap back button to navigate back to costco.com in Chrome
- Focus in/out of password field and BW will correctly show a matching account and auto-fill user/pass

**Comment by nkm8** [comment] 2020-04-24 13:38
Alternative work-around:
- When you focus the password field in Chrome, a key icon is displayed in the bottom left corner to open the Chrome saved passwords feature
- Click the key - Chrome displays "no saved passwords for www.costco.com"
- Click the password field again and BW displays the "Auto-fill with Bitwarden - go to my vault" prompt

I will add, this work-around isn't ideal, either, because BW displays that prompt even if BW is already unlocked. If you focus/re-focus the password field a 3rd time, BW displays both the matching account (correct) and the "go to my vault" prompt (not sure if this is correct or not)

**Comment by mportune-bw** [comment] 2020-04-24 13:41
@nkm8 Are you using build 2353 with both accessibility & autofill service enabled?  I'm not experiencing any issues with `www.costco.com` using Chrome on a Pixel 3.

**Comment by nkm8** [comment] 2020-04-24 13:46
@mportune-bw Confirmed version is build 2353, auto-fill service and auto-fill accessibility service both enabled:
Chrome version: 81.0.4044.117
Android build: QQ2A.200405.005

Not sure what other details would be useful.

**Comment by mportune-bw** [comment] 2020-04-24 13:58
@nkm8 We have an identical configuration. Have you disabled Chrome's built-in password manager?

**Comment by tomo92s** [comment] 2020-04-24 13:58
Why still old option not working? It was better that way...
![Screenshot_2020-04-24-15-56-07-372_com android chrome](https://user-images.githubusercontent.com/32452522/80220637-6ba38c80-8644-11ea-9688-99943b096a91.jpg)

**Comment by mportune-bw** [comment] 2020-04-24 14:02
@tomo92s The way the notification worked was not battery-friendly.  The Auto-fill quick-settings tile provides the same functionality without the power consumption.

**Comment by tomo92s** [comment] 2020-04-24 14:05
@mportune-bw Maybe you will do two versions of filling? Please...

**Comment by mportune-bw** [comment] 2020-04-24 14:10
@nkm8 Any chance there is another accessibility app installed and enabled? (Android settings -> Accessibility -> Downloaded Services)

**Comment by nkm8** [comment] 2020-04-24 14:14
@mportune-bw "My Verizon Guided Navigation" and "Tasker" - neither are enabled.

**Comment by jeffshead** [comment] 2020-04-24 14:26
I just tried the latest beta (2353). I see no improvement on my Pixel XL with Firefox. In fact, (maybe coincidence) I am now getting a lot of the _"There are no items in your vault for x.com"_ warnings when I touch the _**Auto-fill with Bitwarden**_ pop-up. If I simply touch the back button and try again, it finds the correct login. Seems to happen mainly when I start with the Bitwarden app being in a locked state. Subsequent attempts work if the Bitwarden app was previously unlocked.

Has anyone tried or had success in having BW on an Android device auto-fill the login form on:
https://www.righteverywhere.com/

**Comment by victor-bayas** [comment] 2020-04-24 14:40
> I just tried the latest beta (2353). I see no improvement on my Pixel XL with Firefox. In fact, (maybe coincidence) I am now getting a lot of the _"There are no items in your vault for x.com"_ warnings when I touch the _**Auto-fill with Bitwarden**_ pop-up. If I simply touch the back button and try again, it finds the correct login. Seems to happen mainly when I start with the Bitwarden app being in a locked state. Subsequent attempts work if the Bitwarden app was previously unlocked.
> 
> Has anyone tried or had success in having BW on an Android device auto-fill the login form on:
> https://www.righteverywhere.com/
> Works fine on Windows.

It's working for me on Vivaldi Snapshot and FF Nightly with latest BW Play Store beta

![Screenshot_20200424-093759_Vivaldi](https://user-images.githubusercontent.com/49411169/80224669-9f17f400-860f-11ea-9075-d40910992987.jpg)

**Comment by jeffshead** [comment] 2020-04-24 14:57
> It's working for me on Vivaldi Snapshot and FF Nightly with latest BW Play Store beta
Did you actually create login credentials in BW and see if it will fill in the username and password fields on that page?

**Comment by victor-bayas** [comment] 2020-04-24 15:12
> > It's working for me on Vivaldi Snapshot and FF Nightly with latest BW Play Store beta
> 
> Did you actually create login credentials in BW and see if it will fill in the username and password fields on that page?

Yes, I created a fake entry previously for this specific website.

![Screenshot_20200424-101027_Vivaldi](https://user-images.githubusercontent.com/49411169/80227915-f91ab880-8613-11ea-9178-65c91da80ebd.jpg)

**Comment by jeffshead** [comment] 2020-04-24 15:27
> > Did you actually create login credentials in BW and see if it will fill in the username and password fields on that page?
> Yes, I created a fake entry previously for this specific website.
> 
> Edit: I forgot to say that I explicitly disabled battery optimizations for BW app, enabled autofill API and accessibility service.

Thanks for the followup. Doesn't work for me. I installed Vivaldi Snapshot on a Pixel XL and a Galaxy S7. Both have disabled battery optimizations for BW app and auto-fill & accessibility service enabled.

**Comment by Tukks** [comment] 2020-04-28 20:47
Don't work either on last Firefox beta.
Everything in activated in autofill service.
When I close Firefox with a login page on and I re-open it, sometimes the bitwarden popup  appear.

**Comment by mportune-bw** [comment] 2020-04-29 22:06
Build 2376 is now available in the beta channel.  Among other fixes, it hopefully stops the “BW needs your attention -- see auto-fill accessibility service…” popup from appearing on occasion even if you've already enabled the overlay permission.

Re: Firefox beta - it doesn't appear to be firing off any accessibility events, but regular autofill appears to be working.  (Regular Firefox and Firefox Focus seem to work with both)

**Comment by Stephan-P** [comment] 2020-04-30 06:56
Beta version: 2.3.1 (2376) is giving me a nice pop up overlay to tap.
- Nokia 3.1, Android 9
- Vivaldi and Edge browsers
- Accessibility service on, Autofill service off
- URL matching option: any

**Comment by mportune-bw** [comment] 2020-05-08 20:56
As the original issue (and several others mentioned throughout the thread) have been fixed, I'm closing this issue for the sake of clarity.  If you're still experiencing problems while using the latest beta (build 2413 as of this comment) please create a new issue and provide as much detail as possible (Android version, browser type and version, exact URL (if possible), and Bitwarden app autofill & accessibility settings).

**Closed by mportune-bw** 2020-05-08 20:56 UTC
