### ISSUE TITLE
Autofill broken on iOS after updating Bitwarden app

### ISSUE THREAD

**Issue by PowerNodeS** [bitwarden/mobile#3231] opened 2024-05-09 03:16 UTC
### Steps To Reproduce

1. Enable Bitwarden as the only autofill option in iOS settings.
2. Launch any app or webpage that requires login credentials.
3. Tap on autofill suggestion above keyboard.
4. Authenticate with Bitwarden using master password or biometrics (Face ID).

### Expected Result

App or webpage fields should autofill with the respective username and password.

### Actual Result

The fields remain empty. Autofill function breaks and will no longer suggest autofill above keyboard on any app or webpage. Instead, a passwords key icon is presented and must be tapped and the user must manually choose login credentials from within Bitwarden in order to fill fields.

To restore autofill suggestion above the keyboard, the Bitwarden autofill toggle in iOS Settings must be toggled off and back on. The next attempt to use autofill will result in a loop of the results described above.

### Screenshots or Videos

https://github.com/bitwarden/mobile/assets/35882905/fe91f4df-6c27-4175-86ba-c8e0adb05f0e

### Additional Context

This issue has also been reported in the Bitwarden Reddit thread [here](https://www.reddit.com/r/Bitwarden/comments/1cm690n/autofill_not_working_after_update_ios/?rdt=56543).

### Operating System

iOS

### Operating System Version

iOS 17.4.1, iPadOS 17.4.1

### Device

iPhone 15 Pro Max, iPad Pro 12.9 (5th Gen)

### Build Version

Version 2024.4.2 (7528)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment] 2024-05-09 04:05
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/mobile/issues/3225

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-05-09 04:05 UTC
Labels: bug
