### ISSUE TITLE
TOTP code is not saved

### ISSUE THREAD

**Issue by mys31f** [bitwarden/mobile#1553] opened 2021-09-29 04:45 UTC
### Steps To Reproduce

1. Edit an already made password entry.
2. Add a 2FA (TOTP) code either by using a code or scanning a QR code.
3. Press save on the password entry.

### Expected Result

The app to close the edit menu and exit like normal.

### Actual Result

Either: The app takes a while to load and then gives an output of: `Exception message: The operation was canceled' despite me not touching the screen at all.
Or: After scanning a QR code, the app would crash.

### Screenshots or Videos

https://photos.app.goo.gl/RB6b195BnAF9cu9cA

### Operating System

Android

### Operating System Version

Android 11

### Device

Google Pixel 4 XL

### Build Version

RQ3A.210905.001

### Beta

- [ ] Using a pre-release version of the application.

**Comment by eliykat** [comment] 2021-09-29 05:36
Hi @mys31f, thanks for reporting this issue. This appears to be a duplicate of #1228, please add any information or discussion to that thread.

**Closed by eliykat** 2021-09-29 05:36 UTC
Labels: bug

**Comment by mys31f** [comment] 2021-09-29 06:58
Thanks for the info, I'll report it there.Am 29.09.2021 12:36 schrieb Thomas Rittson ***@***.***>:
Hi @mys31f, thanks for reporting this issue. This appears to be a duplicate of #1228, please add any information or discussion to that thread.
