### ISSUE TITLE
< character not displaying in passwords 

### ISSUE THREAD

**Issue by ramiro-zz** [bitwarden/mobile#3372] opened 2024-08-05 09:08 UTC
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

Create a password with the < character in it
Save
View and show the password

### Expected Result

Password is displayed as saved

### Actual Result

Password is displayed without < character. Instead, all subsequent text is red

### Screenshots or Videos

![Screenshot_20240805-190542](https://github.com/user-attachments/assets/50a129b5-bc67-4cc6-8912-092937dc4a34)
![Screenshot_20240805-190535](https://github.com/user-attachments/assets/8cc7a4b0-e248-412d-96f0-187890963580)

### Additional Context

I'm running self hosted vaultwarden, however, from best I can tell this is an issue with the Android app and not the server.

### Operating System

Android

### Operating System Version

14

### Device

Pixel 8

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.7.1 (11086)

**Comment by NovaSilentium** [comment] 2024-08-05 09:21
Duplicate of #3110

**Comment by NovaSilentium** [comment] 2024-08-05 09:21
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/mobile/issues/3110

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by NovaSilentium** 2024-08-05 09:22 UTC
Labels: bug
