### ISSUE TITLE
Random Crash on iOS (BitwardeniOSAutoFill)

### ISSUE THREAD

**Issue by JeffResc** [bitwarden/mobile#899] opened 2020-05-12 18:41 UTC
## Describe the Bug

Random crash after auto filling password in Chrome on iOS 13.3 and BitWarden app version 2.3.1

## Steps To Reproduce

Using the password auto fill feature on iOS in Chrome on the Discover.com website

## Expected Result

For the app extension not to crash

## Actual Result

The app extension crashed in the background after autofilling the password. This did not affect the password being auto filled, but it should not crash after autofilling.

## Screenshots or Videos

I do not have these, but my device is jailbroken, so I’m able to get the crash log
```

Date: 5/12/20, 2:32 PM
Process: BitwardeniOSAutofill
Bundle id: com.8bit.bitwarden.autofill
Device: iPhone 11 Pro Max, iOS 13.3
Bundle version: 2.3.1

Exception type: System.Exception
Reason: System.Exception: Service storageService is not registered.Xamarin Exception Stack:
  at Bit.Core.Utilities.ServiceContainer.Resolve[T] (System.String serviceName, System.Boolean dontThrow) <0x1052c8720 + 0x00108> in <c76a2b8be77144f3a0d1a414550d3044>:0 
  at Bit.iOS.Autofill.Utilities.AutofillHelpers.TableRowSelectedAsync (UIKit.UITableView tableView, Foundation.NSIndexPath indexPath, Bit.iOS.Core.Views.ExtensionTableSource tableSource, Bit.iOS.Autofill.CredentialProviderViewController cpViewController, UIKit.UITableViewController controller, System.String loginAddSegue) <0x104805280 + 0x0030f> in <260cb066032e482ea1ea3acbeacec720>:0 
  at Bit.iOS.Autofill.LoginListViewController+TableSource.RowSelected (UIKit.UITableView tableView, Foundation.NSIndexPath indexPath) <0x1048062c0 + 0x0018f> in <260cb066032e482ea1ea3acbeacec720>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) <0x104974580 + 0x00053> in <7df0b59b3ac34c319d58e821ad54104a>:0 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () <0x104c71160 + 0x0002b> in <9e88d3e16c094729a95b8a083d1224a5>:0 
Culprit: Unknown

Call stack:
0   CoreFoundation                      0x0000000193c9c980 0x193b6a000 + 0x13296c        // __exceptionPreprocess
1   libobjc.A.dylib                     0x00000001939b5028 0x1939af000 + 0x6028          // objc_exception_throw
2   CoreFoundation                      0x0000000193b9b9dc 0x193b6a000 + 0x319dc         // -[NSObject(NSKindOfAdditions) isNSSet__]
3   BitwardeniOSAutofill                0x00000001058e1254 BitwardeniOSAutofill + 18125396
4   BitwardeniOSAutofill                0x00000001058d5de8 BitwardeniOSAutofill + 18079208
5   BitwardeniOSAutofill                0x00000001058d5bbc BitwardeniOSAutofill + 18078652
6   BitwardeniOSAutofill                0x00000001058d7018 BitwardeniOSAutofill + 18083864
7   BitwardeniOSAutofill                0x0000000104b659a4 BitwardeniOSAutofill + 3987876
8   Mono                                0x00000001066734ac 0x10662c000 + 0x474ac         // mono_get_runtime_build_info
9   Mono                                0x000000010673395c 0x10662c000 + 0x10795c        // mono_runtime_try_invoke
10  Mono                                0x0000000106738d44 0x10662c000 + 0x10cd44        // mono_print_unhandled_exception_internal
11  Mono                                0x00000001067387a4 0x10662c000 + 0x10c7a4        // mono_unhandled_exception_checked
12  Mono                                0x00000001067385e8 0x10662c000 + 0x10c5e8        // mono_unhandled_exception_internal
13  Mono                                0x0000000106660830 0x10662c000 + 0x34830         // mono_handle_exception
14  Mono                                0x000000010665fbb8 0x10662c000 + 0x33bb8         // mono_handle_exception
15  Mono                                0x0000000106654928 0x10662c000 + 0x28928         // mono_arm_throw_exception
16  BitwardeniOSAutofill                0x0000000104ba2b1c BitwardeniOSAutofill + 4238108
17  BitwardeniOSAutofill                0x000000010496e6bc BitwardeniOSAutofill + 1926844
18  BitwardeniOSAutofill                0x00000001049745d4 BitwardeniOSAutofill + 1951188
19  BitwardeniOSAutofill                0x0000000104c7118c BitwardeniOSAutofill + 5083532
20  BitwardeniOSAutofill                0x0000000104b659a4 BitwardeniOSAutofill + 3987876
21  Mono                                0x00000001066734ac 0x10662c000 + 0x474ac         // mono_get_runtime_build_info
22  Mono                                0x0000000106732058 0x10662c000 + 0x106058        // mono_runtime_invoke_checked
23  Mono                                0x00000001067358e8 0x10662c000 + 0x1098e8        // mono_runtime_invoke
24  BitwardeniOSAutofill                0x00000001047bf8bc BitwardeniOSAutofill + 161980
25  BitwardeniOSAutofill                0x00000001047c65cc BitwardeniOSAutofill + 189900
26  libobjc.A.dylib                     0x00000001939b0a4c 0x1939af000 + 0x1a4c          // -[NSObject performSelector:withObject:]
27  Foundation                          0x0000000194091c08 0x193f4f000 + 0x142c08        // __NSThreadPerformPerform
28  CoreFoundation                      0x0000000193c18108 0x193b6a000 + 0xae108         // __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
29  CoreFoundation                      0x0000000193c1805c 0x193b6a000 + 0xae05c         // __CFRunLoopDoSource0
30  CoreFoundation                      0x0000000193c177c8 0x193b6a000 + 0xad7c8         // __CFRunLoopDoSources0
31  CoreFoundation                      0x0000000193c12694 0x193b6a000 + 0xa8694         // __CFRunLoopRun
32  CoreFoundation                      0x0000000193c11f40 0x193b6a000 + 0xa7f40         // CFRunLoopRunSpecific
33  GraphicsServices                    0x000000019de8f534 0x19de8c000 + 0x3534          // GSEventRunModal
34  UIKitCore                           0x0000000197d8aa60 0x197347000 + 0xa43a60        // UIApplicationMain
35  libxpc.dylib                        0x00000001938b5e38 0x19388b000 + 0x2ae38         // _xpc_objc_main.cold.3
36  libxpc.dylib                        0x00000001938a0a48 0x19388b000 + 0x15a48         // _xpc_objc_main
37  libxpc.dylib                        0x00000001938a34d0 0x19388b000 + 0x184d0         // xpc_main
38  Foundation                          0x0000000193f94700 0x193f4f000 + 0x45700         // +[NSXPCListener serviceListener]
39  PlugInKit                           0x00000001a12d89bc 0x1a12c2000 + 0x169bc         // __PLUGINKIT_CALLING_OUT_TO_CLIENT_SUBSYSTEM_FOR_BEGINUSING__
40  PlugInKit                           0x00000001a12d86a4 0x1a12c2000 + 0x166a4         // __PLUGINKIT_CALLING_OUT_TO_CLIENT_SUBSYSTEM_FOR_BEGINUSING__
41  PlugInKit                           0x00000001a12d8de0 0x1a12c2000 + 0x16de0         // __PLUGINKIT_CALLING_OUT_TO_CLIENT_SUBSYSTEM_FOR_BEGINUSING__
42  Foundation                          0x00000001941802b4 0x193f4f000 + 0x2312b4        // NSExtensionMain
43  BitwardeniOSAutofill                0x00000001061c3138 0x104798000 + 0x1a2b138       // xamarin_release_block_on_main_thread
44  BitwardeniOSAutofill                0x00000001047fccc8 BitwardeniOSAutofill + 412872
45  libdyld.dylib                       0x0000000193a90e18 0x193a90000 + 0xe18           // start

{"NSExceptionReason":"System.Exception: Service storageService is not registered.Xamarin Exception Stack:\n  at Bit.Core.Utilities.ServiceContainer.Resolve[T] (System.String serviceName, System.Boolean dontThrow) <0x1052c8720 + 0x00108> in <c76a2b8be77144f3a0d1a414550d3044>:0 \n  at Bit.iOS.Autofill.Utilities.AutofillHelpers.TableRowSelectedAsync (UIKit.UITableView tableView, Foundation.NSIndexPath indexPath, Bit.iOS.Core.Views.ExtensionTableSource tableSource, Bit.iOS.Autofill.CredentialProviderViewController cpViewController, UIKit.UITableViewController controller, System.String loginAddSegue) <0x104805280 + 0x0030f> in <260cb066032e482ea1ea3acbeacec720>:0 \n  at Bit.iOS.Autofill.LoginListViewController+TableSource.RowSelected (UIKit.UITableView tableView, Foundation.NSIndexPath indexPath) <0x1048062c0 + 0x0018f> in <260cb066032e482ea1ea3acbeacec720>:0 \n  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) <0x104974580 + 0x00053> in <7df0b59b3ac34c319d58e821ad54104a>:0 \n  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () <0x104c71160 + 0x0002b> in <9e88d3e16c094729a95b8a083d1224a5>:0 ","ProcessBundleID":"com.8bit.bitwarden.autofill","ProcessName":"BitwardeniOSAutofill","Culprit":"Unknown"}
```

## Environment

- Device: iPhone 11 Pro Max
- Operating system: iOS 13.3
- Build Version (go to "Settings" → "About" in the app): 2.3.1 (64)
- Is this a Beta release? N

## Additional Context

Not that I can think of, but please respond if there are any additional questions that I could answer.

**Comment by DingXiangYuanZhiXing** [comment] 2020-06-17 11:13
Similar issue. Sometimes when clicking autofill nothing happened, bitwarden don't show up to give the password. Seems the app crashes.

**Comment by tgreer-bw** [comment] 2020-06-17 12:02
Crashes and other autofill issues have been addressed in 2.4.3 - can you give that version a shot?

**Comment by DingXiangYuanZhiXing** [comment] 2020-06-17 12:07
@tgreer-bw Unfortunately, this problem occurs after I upgrade to 2.4.3(69).

**Comment by nxli** [comment] 2020-07-27 02:42
ipad os 13.5.1 jailbroken, bitwarden crashes for autofill and app

**Comment by clayadams5226** [comment] 2021-01-06 04:40
@JeffResc is this still happening to you on the newest Appstore build 2.7.2? If yes, does it persist after a fresh install? I'm unable to reproduce it here, so any additional information / exact steps you can give would be helpful.

**Comment by JeffResc** [comment] 2021-01-15 19:10
@clayadams5226 — Thanks for the reply. The issue seemed to stop happening within a few weeks of submitting this issue. I haven't had any issues since, as for me you can close this issue, but I'll leave it open for other people having the issue as well.

**Comment by clayadams5226** [comment] 2021-01-20 05:39
Closing this issue for now as it seems to be resolved. If anyone is still having issues please feel free to open a new ticket or reach out and we can re-open this one.

**Closed** 2021-01-20 05:38 UTC
