### ISSUE TITLE
F-Droid App crashes when generating new password for new app login

### ISSUE THREAD

**Issue by TheDoctorT** [bitwarden/mobile#2201] opened 2022-11-21 19:46 UTC
### Steps To Reproduce

1. Open an app that necessitates a login
2. Go to the login page and open the BitWarden Vault by tapping on the prompt
3. Tap the plus icon to create a new login
4. Tap on the circling arrows next to the password field to generate a new password

### Expected Result

The password generator should open and generate a new password.

### Actual Result

The application crashes.

### Additional Context

The application is the F-Droid version. Additionally, this only happens if the new login is for an application, whereas the same process behaves fine when creating a new browser login.

I tested it on 2 different applications: org.telegram.messenger and com.lgi.upcch
A third application, ch.ethz.eduapp, did not show this behaviour.

This phone has Android One installed.

### Operating System

Android

### Operating System Version

Android 10

### Device

HTC U11 Life

### Build Version

2022.10.0 (5247)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment] 2022-11-21 20:30
Hi @TheDoctorT and thank you for your report.

This seems to be a duplicate of https://github.com/bitwarden/mobile/issues/2149, which has already received a fix.

This should be resolved with the next release (2022.11)

Closing this now.

**Closed by djsmith85** 2022-11-21 20:30 UTC
Labels: bug
