### ISSUE TITLE
Crashing after logging in

### ISSUE THREAD

**Issue by mizzunet** [bitwarden/mobile#1437] opened 2021-06-21 20:18 UTC
## Describe the Bug
Crashes the app once I logged in, then whenever I open, it crashes. Server https://username.mycozy.cloud/bitwarden
They have client on their own but it's outdated and buggy as well. That's why I tried with official client.
https://github.com/cozy/cozy-pass-mobile/issues/39#issuecomment-861583033

## Steps To Reproduce

You need to have a cozy.io account
1. Set server URL as https://foo.mycozy.cloud/bitwarden
2. Login email as me@foo.mycozy.cloud
3. See that it has been logged in. The loading happens

## Expected Result

Shouldn't crash
## Actual Result
Crash

## Logs
[Log_2021-06-22_01-39-54.txt](https://github.com/bitwarden/mobile/files/6689361/Log_2021-06-22_01-39-54.txt)

## Environment

- Device: OnePlus 5
- Operating system: AOSP 11
- Build Version (go to "Settings" → "About" in the app): 2.10.0
- Is this a Beta release? [Y/N] N

## Additional Context
It works properly for official BitWarden server

**Comment by eliykat** [comment] 2021-06-21 22:47
This thread indicates that Cozy are not using the latest version of the Bitwarden server: https://github.com/cozy/cozy-pass-mobile/issues/39

If that is the case, then this crash is likely caused by an up-to-date client trying to communicate with an old server. For example, Bitwarden Send required many updates to both the client and server. Trying to run a new client against an old server is going to cause issues.

I'll close this thread as it's not anything we can fix - it's Cozy's responsibility to update their servers. However, please let me know if I've misunderstood anything.

**Closed by eliykat** 2021-06-21 22:47 UTC

**Comment by mizzunet** [comment] 2021-06-22 04:51
Thank you for the info🙏. I'll let them know this
