### ISSUE TITLE
Discrepancy between mobile and Web vaults when displaying passwords with '<' and '>'.

### ISSUE THREAD

**Issue by tweekes0** [bitwarden/mobile#3380] opened 2024-08-21 17:04 UTC
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Create password that has characters '<' and '>'
2. Save Password into vault
3. Check if the password is viewable across both devices

### Expected Result

I created a test password that read as follows: "This is a test <>".
When viewing on the web vault I see should see "This is a test <>" on both devices. 

### Actual Result

When viewing the password in the mobile app the "<>" part of the password is not shown. 

"This is a test" is what I get.

When copying the password however the the contents are correct.

### Operating System

Android

### Device

Google Pixel 7 XL

### Build Version

2024.7.1 (11086)

**Comment by Greenderella** [comment] 2024-08-22 09:28
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/mobile/issues/3110

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Greenderella** 2024-08-22 09:28 UTC
Labels: bug
