### ISSUE TITLE
Scrolling Issues

### ISSUE THREAD

**Issue by djohannes** [bitwarden/mobile#641] opened 2019-10-26 08:01 UTC
With the newest beta scrolling through my vault sometimes just stops or doesn't work, sometimes it helps to scroll "slow", sometimes I need to tap and hold for a sec before I start scrolling. It's especially annoying if scrolling worked at first but then you want to "keep scrolling" but instead of getting faster it just stops.
It would be great if scrolling could work as intended soon again :)

I'm on a Pixel 4

**Comment by SlowNicoFish** [comment] 2019-11-23 16:06
I have the same problem. I scroll down fast and let it "scroll" by it self, when i then stop it it's stuck.
I'm on Pixel 3 Android 10 (not beta)
Bitwarden version: 2.2.6

**Comment by SlowNicoFish** [comment] 2020-01-02 19:14
It seems to be fixed in 2.2.8.
At least for me!

**Comment by djsmith85** [comment] 2021-11-19 12:29
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2021-11-19 12:29 UTC
