### ISSUE TITLE
iOS: App Extension not working since latest version (2.14.2)

### ISSUE THREAD

**Issue by crivchri** [bitwarden/mobile#1635] opened 2021-11-09 19:17 UTC
### Steps To Reproduce

1. Go to 'Settings'
2. Click on 'Application extension'
4. Click on 'Activate…'

### Expected Result

Bitwarden showing up in the list

### Actual Result

Bitwarden not showing up in the list

### Operating System

iOS

### Operating System Version

15.1

### Device

iPhone XS, iPhone 12 mini

### Build Version

12.14.2 (1105)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by crivchri** [comment] 2021-11-17 06:55
Hi,
Is there anything new regarding this issue?
Thanks and kind regards

**Comment by jlf0dev** [comment] 2021-11-22 15:52
Hi @crivchri, this might be a duplicate of #1624

**Comment by crivchri** [comment] 2021-11-22 17:46
> Hi @crivchri, this might be a duplicate of #1624

Hi @jlf0dev, yes it might be, but the issue here is that the application extension **cannot be activated** in Bitwarden iOS application.

**Comment by AlexHunterCodes** [comment] 2021-12-01 00:14
I uninstalled and reinstalled the Bitwarden iOS application, in an attempt to fix #1624. Should've checked GitHub first, as I'm now stuck on this issue instead, and can't even get to the extension to see if reinstalling fixed #1624 at all.

**Comment by bcelary** [comment] 2021-12-09 09:02
Hi,
I am trying to figure out if this is the issue I am facing.

When I click Settings -> App Extension -> Enable app extension, the window shows up with [Bitwarden] label but clicking it has no effect. I don't get to see the "Extension Activated!" pop up. I do have it in a list so it's slightly different than described here. Should I create a new issue?
Thanks.

**Comment by AlexHunterCodes** [comment] 2021-12-09 15:24
> When I click Settings -> App Extension -> Enable app extension, the window shows up with [Bitwarden] label but clicking it has no effect. I don't get to see the "Extension Activated!" pop up. I do have it in a list so it's slightly different than described here.

Yeah, that's the same behaviour I had before I reinstalled the app and the entry disappeared. I'm pretty sure it's the same issue for those who had the app installed before the update that broke the extension.

**Comment by crivchri** [comment] 2021-12-10 11:20
Hi,
I have just updated to version 2.15.0 and that issue is still not fixed.
Please fix it soon! 😕
Thanks in advance and kind regards

**Comment by jlf0dev** [comment] 2021-12-10 15:06
Hi @crivchri, I'm having trouble reproducing this anymore in iOS 15.1 with 2.15.0. Could you try reinstalling the app and letting me know if that works? I thought I had a fix for this in #1631, but might be unrelated.
Thanks!

**Comment by AlexHunterCodes** [comment] 2021-12-10 18:04
Like @crivchri I am also still able to reproduce this on iOS 15.1 with Bitwarden 2.15.0, also tried a reboot and reinstall and issue persists. Can't vouch for whether #1624 is still reproducible as I'm not able get past this issue to test, although I noticed it's been closed. (perhaps prematurely?)

**Comment by jlf0dev** [comment] 2021-12-10 18:20
Could one of you verify that the App Extension is enabled in your extension list? I noticed that if I disable it, the option disappears in the app.
<img src="https://user-images.githubusercontent.com/24985544/145622079-db052eaa-6c15-4279-8d8e-d47603973a9f.png" width="50%" height="50%">

**Comment by crivchri** [comment] 2021-12-10 18:41
> Could one of you verify that the App Extension is enabled in your extension list? I noticed that if I disable it, the option disappears in the app.
> 
> <img src="https://user-images.githubusercontent.com/24985544/145622079-db052eaa-6c15-4279-8d8e-d47603973a9f.png" width="50%" height="50%">
> 
> 

Hi @jlf0dev,

Thanks for your answer, this was the issue on my iPhone.

I have no clue why Bitwarden was deactivated in the App Extension list (as on your screenshot).
But after reactivating Bitwarden in the list, the option is now shown again in the Bitwarden app.

Kind regards

**Closed** 2021-12-14 04:28 UTC
Labels: bug
