### ISSUE TITLE
Context-Menu for filtered vault-list does not open

### ISSUE THREAD

**Issue by mhombach** [bitwarden/mobile#2500] opened 2023-04-29 19:50 UTC
### Steps To Reproduce

1. Open app
2. Unlock vault
3. Click the magnifyer-icon top right to search your vault
4. Type in some search-term so you see a few items from your vault appear
5. Touch the 3-dots in the right of an entry to open the context-menu to for example quickly copy the password

### Expected Result

The context-menu opens

### Actual Result

nothing happens

### Additional Context

The touch and opening of the context menu works if the vault isn't in the filtered-view. So if you are directly navigating to your vault from the main-view, the 3-dots open the context-menu (although i feel the touch-area where the 3-dots trigger is too small, but it works at least. In the filtered view it's not working even with perfect-targeted touches/clicks).

### Operating System

Android

### Operating System Version

TQ2A.230405.003.E1

### Device

Google Pixel 7

### Build Version

2023.3.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment] 2023-05-01 10:15
Hi @mhombach,

Thank you for your report. It seems like it's a duplicate of this one (https://github.com/bitwarden/mobile/issues/2446), and this was addressed in version 2023.4 (https://bitwarden.com/help/releasenotes/). 

This issue will now be closed.

Thank you again,

**Closed by SergeantConfused** 2023-05-01 10:15 UTC
Labels: bug

**Comment by mhombach** [comment] 2023-05-01 11:00
@SergeantConfused thx, this is indeed the same issu. I didn't find it by my previously done search because at that time it was already closed (but not released). The google play store still doesn't give me an update for bitwarden, do you have an idea how long it usually takes between the github-release (26th April) until it's deployed through the google playstore?
