### ISSUE TITLE
Export vault .json - force close

### ISSUE THREAD

**Issue by dp-collection** [bitwarden/mobile#2800] opened 2023-09-27 19:28 UTC
### Steps To Reproduce

1. Go to 'Settings'
2. Click on 'Export vault'
3. After submitting password, and confirming accepting prompt
4. Force close

### Expected Result

Prompt where file .json is exported

### Actual Result

Force close 

### Operating System

Android

### Operating System Version

Android 13

### Device

Oneplus 9

### Build Version

LE2115 13.1.0.590(EX01)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by dp-collection** [comment] 2023-09-28 10:19
App version is 2023.9.1

**Comment by djsmith85** [comment] 2023-09-28 11:21
Duplicate of https://github.com/bitwarden/mobile/issues/2793

**Comment by djsmith85** [comment] 2023-09-28 11:21
Hi there!

Thank you for your report, it seems like it is a duplicate of this one #2793  .

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2023-09-28 11:21 UTC
Labels: bug
