### ISSUE TITLE
[Android] Website icon for Quizlet is never shown

### ISSUE THREAD

**Issue by meenbeese** [bitwarden/mobile#2393] opened 2023-03-01 14:29 UTC
### Steps To Reproduce

1. Go to 'My Vault’
2. Click on 'Login’
3. Scroll down to 'Quizlet’
4. You will see a generic low quality icon instead of the real one

### Expected Result

‘Show website icons’ is enabled on my device and it works for all other websites except Quizlet. I have tried disabling and reenabling it, to no avail. I have faced this issue of app icons not working but all of them have resolved one way or another except Quizlet. Quizlet is very persistent in not working at all, even when I use the enter the generic ‘www.quizlet.com’ website to my vault.

### Actual Result

I see a low quality world-like icon instead of the expected one. This is also weird because this means that the app is probably failing to fetch the icon somewhere along the way. Normally, when a website isn’t provided for example, there is a higher quality world icon which does not look bad at all. But it looks bad in my case.

### Operating System

Android

### Operating System Version

13

### Device

Samsung Galaxy S20+

### Build Version

2023.2.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Adedamola-Aina** [comment] 2023-03-01 14:54
Hello, 

With regard to the favicons, please first make sure that the site has a compatible one by using any of the online finder tools (like https://realfavicongenerator.net/favicon_checker or http://www.faviconfinder.com). 

If it does, please attempt to refresh the vault item that is not showing the favicon by adding “https://icons.bitwarden.net/www.YOUR_URL.com/icon.png?refresh=123” as your new URI 1. Remember to replace the “YOUR_URL” part with the actual correct URL, as this will prompt Bitwarden to try to pull the favicon from scratch:
![image](https://user-images.githubusercontent.com/91448810/222175915-6f7a68bb-0357-47ad-9911-2046aaaef08b.png)


It is worth noting that this can also happen when the website stores its favicon at a non-standard location, and can also be potentially caused by our own servers (CDN) as we had received reports about that, and we are looking into them. 

If the steps above did not assist you in resolving this, please bear with us while we continue to examine this matter internally, and hopefully we'll address it in the near future.

We're sorry about this inconvenience, and we thank you for your patience.

**Closed by Adedamola-Aina** 2023-03-01 14:54 UTC
Labels: bug
