### ISSUE TITLE
Clicking on button next to URL doesn't open web browser on Android 11

### ISSUE THREAD

**Issue by Dan884** [bitwarden/mobile#1255] opened 2021-02-08 23:15 UTC
This has been broken for a couple of weeks. 

## Steps to reproduce
You can reproduce by opening the Bitwarden app and clicking on the button next to the URL on any item. This is the button that looks like a square with an arrow in it. 

##Expected Result
It should open that URL in your browser. 

##Actual Result
It doesn't do anything. It is like you didn't even press the button. It stays in the Bitwarden app. The button to copy the URL works fine. 

## Environment
Doesn't work on my Samsung Galaxy S20 FE 5G running Android 11.
Works fine on my Samsung Galaxy A11 and my Samsung Galaxy S5e tablet. Both are running Android 10.
I am running Bitwarden 2.8.0 (3349).

**Comment by sso-bitwarden** [comment] 2021-02-08 23:28
Thanks for your report. This is duplicate of https://github.com/bitwarden/mobile/issues/1164

**Comment by clayadams5226** [comment] 2021-02-17 04:37
Closing as a duplicate.

**Closed by clayadams5226** 2021-02-17 04:37 UTC
