### ISSUE TITLE
Android 10 Icons not appearing and sync issue

### ISSUE THREAD

**Issue by User486375** [bitwarden/mobile#674] opened 2019-12-18 02:14 UTC
I'm on android version: 2.2.7

After logging into the Android app and syncing my accounts none of the accounts have icons. I have tried disabling website icons and re-enabling them in settings and it doesn't help.

In regard to syncing, auto sync doesn't seem to really happen consistently like the extension or website. As well as when I actually try to manually sync after making lots of changes the app is often stuck on syncing for over a minute, which I'm assuming isn't intended?

**Comment by kspearrin** [comment] 2019-12-18 03:49
The icons server was having some issues earlier. It should be fixed now.

**Comment by User486375** [comment] 2019-12-19 08:46
Well, after a re-sync and restart nothing has changed. On multiple account also. Everything else is fine, desktop, extension, webpage.

Also, any info on that sync time? Like is it an actual issue being looked into or "expected".

**Comment by kspearrin** [comment] 2019-12-19 15:35
Can you try reinstalling the app to see if that changes anything?

**Comment by User486375** [comment] 2019-12-19 15:41
No changes.

**Comment by kspearrin** [comment] 2019-12-19 15:46
As an example, Are you able to access https://icons.bitwarden.net/google.com/icon.png?sadfasd=dddddd ?

**Comment by User486375** [comment] 2019-12-19 16:03
Hmmm, I think I just figured out the issue due to you asking that. I can connect to that fine in the browser with it enabled. But having just disabled Cloudflares 1.1.1.1 DNS via their app, they now load fine. Why would this be affecting Bitwarden, when Cloudflare doesn't block any domains?

**Comment by djsmith85** [comment] 2022-03-10 23:58
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2022-03-10 23:58 UTC
