### ISSUE TITLE
Android app three dot menu next to login entry does not work when you click on it

### ISSUE THREAD

**Issue by pseudacris** [bitwarden/mobile#2461] opened 2023-04-01 06:41 UTC
### Steps To Reproduce

1. Go to 'Auto-fill' in Quick Panel 
2. Click on the three dot menu of the login entry for whatever app you're trying to login into

### Expected Result

Open other options, such as editing

### Actual Result

Nothing happens at all

### Additional Context

Same problem if I access Bitwarden through the app drawer.

### Operating System

Android

### Operating System Version

13

### Device

Pixel 4 XL

### Build Version

TP1A.221005.002.B2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by shalloran** [comment] 2023-04-01 12:20
Similar issue on iPadOS and iOS version: 2023.3.2. 3-dot menu is not functional in certain states - easiest way to reproduce is to search for an entry in the vault, and attempt to click on 3-dot menu.

**Comment by SergeantConfused** [comment] 2023-04-01 14:57
Hi @pseudacris,

Thank you for your report, it seems like it is a duplicate of this (https://github.com/bitwarden/mobile/issues/2446).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in that thread - our engineering team will be happy to review these.

This issue will now be closed.


Thank you.

**Closed by SergeantConfused** 2023-04-01 14:57 UTC
Labels: bug
