### ISSUE TITLE
"Show Password" feature shows wrong password on mobile for passwords with certain characters in them

### ISSUE THREAD

**Issue by snhardin** [bitwarden/mobile#3186] opened 2024-04-23 16:34 UTC
### Steps To Reproduce

1. Create a new Login with a password containing the greater-than or less-than signs i.e. `this is a test password <> lalala`. Save this to your vault.
2. Open your vault on your Android mobile phone.
3. Open the login and click on the 'Show Password' button next to the obscured password.

### Expected Result

Your actual password should be shown: `this is a test password <> lalala`.

### Actual Result

The password is shown without greater-than or less-than symbols: `this is a test password  lalala`.

### Screenshots or Videos

(screenshot on mobile blocked due to app security)

### Operating System

Android

### Operating System Version

Android version: 13, One UI version: 5.1

### Device

Samsung Note 20 Ultra

### Build Version

2024.4.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment] 2024-04-23 17:32
Duplicate of #3110

**Comment by djsmith85** [comment] 2024-04-23 17:32
Hi @snhardin!

Thank you for your report, it seems like it is a duplicate of this one #3110

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-04-23 17:32 UTC
Labels: bug

**Comment by keanchuanpoh** [comment] 2024-04-23 20:37
> ### Steps To Reproduce
> 
> 1. Create a new Login with a password containing the greater-than or less-than signs i.e. `this is a test password <> lalala`. Save this to your vault.
> 2. Open your vault on your Android mobile phone.
> 3. Open the login and click on the 'Show Password' button next to the obscured password.
> 
> ### Expected Result
> 
> Your actual password should be shown: `this is a test password <> lalala`.
> 
> ### Actual Result
> 
> The password is shown without greater-than or less-than symbols: `this is a test password  lalala`.
> 
> ### Screenshots or Videos
> 
> (screenshot on mobile blocked due to app security)
> 
> ### Additional Context
> 
> _No response_
> 
> ### Operating System
> 
> Android
> 
> ### Operating System Version
> 
> Android version: 13, One UI version: 5.1
> 
> ### Device
> 
> Samsung Note 20 Ultra
> 
> ### Build Version
> 
> 2024.4.0
> 
> ### Beta
> 
> - [ ] Using a pre-release version of the application.

**Comment by keanchuanpoh** [comment] 2024-04-23 20:37
> ### Steps To Reproduce
> 
> 1. Create a new Login with a password containing the greater-than or less-than signs i.e. `this is a test password <> lalala`. Save this to your vault.
> 2. Open your vault on your Android mobile phone.
> 3. Open the login and click on the 'Show Password' button next to the obscured password.
> 
> ### Expected Result
> 
> Your actual password should be shown: `this is a test password <> lalala`.
> 
> ### Actual Result
> 
> The password is shown without greater-than or less-than symbols: `this is a test password  lalala`.
> 
> ### Screenshots or Videos
> 
> (screenshot on mobile blocked due to app security)
> 
> ### Additional Context
> 
> _No response_
> 
> ### Operating System
> 
- > Android
> 
> ### Operating System Version
> 
> Android version: 13, One UI version: 5.1
> 
> ### Device
> 
> Samsung Note 20 Ultra
> 
> ### Build Version
> 
> 2024.4.0
> 
> ### Beta
> 
> - [ ] Using a pre-release version of the application.
