### ISSUE TITLE
The Search vault windows when signing in an IOS app is not updating. 

### ISSUE THREAD

**Issue by Freeland90** [bitwarden/mobile#1068] opened 2020-09-14 10:25 UTC
I've manually synced multiple times, it stays the same. The vault is fully synced if I searched through the Bitwarden app, but not in individuals apps!  Also what is the best  way to save log ins for IOS apps?

**Comment by Johnnyt12** [comment] 2020-09-18 06:49
I'm having the same issue. Bitwarden simply does not suggest any login in third-party app other than Safari. In other words, AutoFill does work only in Safari. Using iOs 14 and newest Bitwarden app version.

**Comment by Johnnyt12** [comment] 2020-09-18 06:57
I had the same issue. Restarting the iPhone had solved it.

**Comment by cscharf** [comment] 2020-09-18 20:31
This is a duplicate of #405 and #980. Please refer to those for possible workarounds and explanations of some of the iOS autofill limitations that we're currently experiencing and trying to work around.

**Closed by cscharf** 2020-09-18 20:31 UTC
