### ISSUE TITLE
iOS app crashes after entering master password

### ISSUE THREAD

**Issue by MathiasHandle** [bitwarden/mobile#2750] opened 2023-09-07 21:57 UTC
### Steps To Reproduce

1. Go to 'vault'
2. Open login that has enabled master password re-prompt to view fields
3. Fill in your master password
4. After submitting password, the app closes and nothing happens

### Expected Result

Expected result is that I will see my fields

### Actual Result

Actual result is that app crashes/closes

### Additional Context

Web extension (firefox) works fine

### Operating System

iOS

### Operating System Version

16.6

### Device

iPhone 12 mini

### Build Version

2023.8.0 (4566)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by mkmaslov** [comment] 2023-09-07 22:01
Seems to be the same problem on Android. I tried exporting the Vault. App crashed right after entering the master password. I tried several times.

Build version: 2023.8.0

**Comment by djsmith85** [comment] 2023-09-07 22:05
Duplicate of https://github.com/bitwarden/mobile/issues/2733

**Comment by djsmith85** [comment] 2023-09-07 22:05
@MathiasHandle and @mkmaslov Thank you for your reports, this seems to have previously been reported with https://github.com/bitwarden/mobile/issues/2733 and a fix has been issued with #2713 which will be included in the next release (`2023.9`)

**Closed by djsmith85** 2023-09-07 22:05 UTC
Labels: bug

**Comment by MathiasHandle** [comment] 2023-09-07 22:19
> @MathiasHandle and @mkmaslov Thank you for your reports, this seems to have previously been reported with #2733 and a fix has been issued with #2713 which will be included in the next release (`2023.9`)

May I ask how often do you do releases? :)

**Comment by djsmith85** [comment] 2023-09-07 22:35
`2023.9`will be available in 2-3 weeks time.
