### ISSUE TITLE
Secure Notes almost unusable for long notes on iOS

### ISSUE THREAD

**Issue by cedarmora** [bitwarden/mobile#1430] opened 2021-06-15 05:42 UTC
## Describe the Bug

After opening edit mode for a Secure note, when I tap to edit somewhere in the top of a long note (mine is about 70 lines long) on iOS, it scrolls all the way down to the bottom, which is annoying, since I have to scroll all the way back up. This happens every single time I tap to move the cursor.

## Steps To Reproduce

1. Open a long (e.g. 70 line) secure note
2. Tap Edit
3. Tap somewhere in the top of the note to place the cursor

## Expected Result

I can edit the note

## Actual Result

It scrolls to the bottom of the note, so I have to scroll all the way back up to see what I’m typing

## Environment

- Device: iPhone SE 2020
- Operating system: iOS 14.4.2
- Build Version (go to "Settings" → "About" in the app): 2.10.0 (616)
- Is this a Beta release? [Y/N] no

**Comment by sso-bitwarden** [comment] 2021-06-15 06:24
Thank you for your report. This is a duplicate of https://github.com/bitwarden/mobile/issues/1257

**Comment by cedarmora** [comment] 2021-06-15 19:25
Ahhh gotcha, guess I didn’t search thoroughly enough. Thanks.

**Closed** 2021-06-16 00:11 UTC
