### ISSUE TITLE
iOS - The application closes/crashes the moment it is unlocked when the device language is set to Romanian.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#2086] opened 2022-09-20 16:21 UTC
### Steps To Reproduce

1. Set the device language to Romanian.
2. Attempt to log in or unlock your Bitwarden iOS client.

### Expected Result

To access the vault.

### Actual Result

The client closes unexpectedly without displaying an error message.

### Screenshots or Videos

N/A.

### Additional Context

Changing the language to English addresses this, without needing to install the iOS client from scratch.

### Operating System

iOS

### Operating System Version

16.

### Device

Iphone SE 2020.

### Build Version

2022.9.1.

### Beta

- [ ] Using a pre-release version of the application.

**Comment by hmlendea** [comment] 2022-09-20 21:23
Thanks for reporting this. It looks like I have the same issue!

I spent a lot of time trying to remember and revert all the changes I've made today to various items thinking that somehow those were the issue, but it wasn't that.

It is indeed the language problem... and it happens both on Android and iOS.

**Comment by cslucian** [comment] 2022-09-22 07:32
I can confirm I have the same issue on IOS 16. 

Device language set to Romanian.
The client closes unexpectedly without displaying an error message after using Face ID or prompting the password.

**Comment by hmlendea** [comment] 2022-09-22 07:58
As a workaround you can set the language for this specific app to English from the settings application.
As a new iPhone user it took a bit to figure this fix out :P

**Comment by madpipeline** [comment] 2022-09-26 09:13
I'd like to report that I'm having the same issue but on Android.
Android version: 11
Bitwarden version: 2022.9.1 installed from F-Droid

**Comment by Larry-Sussman** [comment] 2022-10-03 23:55
Hi all, sorry about the trouble. Luckily we've identified the issue causing this crash, and have a fix for iOS and Android which will be included in our upcoming 2022.10 release. 

In the meantime, there is the workaround of setting the language for the Bitwarden app to English as @hmlendea mentioned. 👍 
- On your iOS device: open Settings, scroll down to the Bitwarden app, and set the "Preferred Language" to English. 
- How to change app language on [Android](https://support.google.com/android/answer/12395118?hl=en)

**Comment by djsmith85** [comment] 2022-10-04 10:42
Closing this now as a fix has been made and is scheduled for release with 2022.10 (~mid-October)

We are sorry for the inconveniences this has caused!

**Closed by djsmith85** 2022-10-04 10:42 UTC
Labels: bug
