### ISSUE TITLE
TOTP scanning fails on tall android devices

### ISSUE THREAD

**Issue by varunyellina** [bitwarden/mobile#2244] opened 2022-12-15 05:36 UTC
### Steps To Reproduce

1. On Android device, edit a saved login to add TOTP for 2FA.
2. If your device is not the standard aspect ratio of 16:9, then the camera preview will look stretched vertically in Bitwarden.
3. Scanning fails on my 21:9 Flip phone.

### Expected Result

It should scan normally.

### Actual Result

It is not scanning. It is scanning normally if I fold the phone into a 90deg shape. The camera preview is not warped in this mode.

### Screenshots or Videos

![PXL_20221215_052038660](https://user-images.githubusercontent.com/1850730/207780440-8b0460a2-a3a3-47f2-834d-9383548c4562.jpg)
![PXL_20221215_052104632](https://user-images.githubusercontent.com/1850730/207780454-d4eb7376-04ea-4219-a7f7-39dfa7ea33ca.jpg)
![PXL_20221215_052204934](https://user-images.githubusercontent.com/1850730/207780459-430be617-6857-42d8-92af-7beb61931eef.jpg)

### Operating System

Android

### Operating System Version

13

### Device

Samsung Z Flip 3

### Build Version

2022.11.0 (5880)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by ntlv** [comment] 2022-12-28 21:24
I can repro this on an Asus Zenfone 9 though it is less extreme. Perhaps Google's recently released [Viewfinder library](https://android-developers.googleblog.com/2022/11/introducing-camera-viewfinder.html) could be used to solve this issue.

**Comment by dal00** [comment] 2023-01-18 17:02
@varunyellina you should change that TOTP if you are using it because it is readable in the reflection of your phone.

**Comment by Cheesebaron** [comment] 2023-01-25 19:08
ZXing.Net.Mobile is kind of a dead project and has so many issues with regards to handling aspect ratios with cameras. Detecting cameras and their resolutions. Handling frames from high resolution cameras and more. Mainly on Android though.

For simple QR codes I highly recommend just rolling your own AVFoundation code for iOS reading AVMetadataObjects and for Android using AndroidX.Camera.View + a simple frame analyzer that sends the data to ZXing.Net.

This has solved most QR code reading issues in most of my Apps, where I was using ZXing.Net.Mobile before.

**Comment by N1c093** [comment] 2023-01-27 14:05
I can confirm this issue on my Google Pixel 6 with Android 13.

**Comment by Greenderella** [comment] 2023-02-14 16:22
Hi there,

This issue appears to be duplicated from this one: https://github.com/bitwarden/mobile/issues/1130

I will proceed to close this one. If you wish to add any further information/screenshots/recordings etc., please feel free to do so here: https://github.com/bitwarden/mobile/issues/1130 - our engineering team will be happy to review these.

**Closed by Greenderella** 2023-02-14 16:22 UTC
Labels: bug

**Comment by test4testUnlimit** [comment] 2023-05-11 02:35
Same problem on Samsung Galaxy A30s (and A50)

**Comment by capatina** [comment] 2023-10-19 12:40
HELLO, SAME PROBLEM HERE. PLEASE FIX IT ASAP

**Comment by test4testUnlimit** [comment] 2023-11-04 16:27
Dude, I see your secret QR in reflection...

**Comment by varunyellina** [comment] 2023-12-22 08:37
> Dude, I see your secret QR in reflection...

Changed the TOTP.
