### ISSUE TITLE
[IOS] Autofill don't sync. with vault when password have been changed in browser

### ISSUE THREAD

**Issue by PatrickRorth** [bitwarden/mobile#1126] opened 2020-10-20 17:26 UTC
## Describe the Bug

When updateing a password in browser, or desktop app. The Autofill dont get updated on IOS unless you open the bitwarden app, and sync/pull to syns manually.

## Steps To Reproduce

1. Change the password on what ever user in the vault, via browser extention or desktop app.
2. On your IOS device, go to the site, wich user's password you just changed.
3. On autofill, press the account you changed the password for, and press login. This dont work.
4. Open bitwarden app, and sync manually.
5. Close Safai ( otherwise the same error keeps happening )
6. Open Safai again, and try step 2 + 3 again, this time you will get the correct password, and can login.

This also happens with usernames, if these are updated, but not manually synced.

## Expected Result

I expect the vault is getting updated when i update a password or user, no matter where its being done.
I expect this update is getting synced to all my devices, without the need for manually sync, when ever an account is updated.
I expect this to happend within 2-3min of me updating what ever account.

## Actual Result

When updating an account in the vault, both password or username, it is not getting synced to the autofill automaticly, unless you wait a long time. When an account HAVE been updated in wither browser extention or desktop app, and i go to my IOS device to login on the site, with the account i just updated, im stuck with my "old" info in the autofill. I now have to close the "SOMENAME APP" on my IOS device, open bitwarden, manually sync, open the "SOMENAME APP" again, and now im able to use the new info in the autofill. Not before these steps are taken.

I have tried to wait up to 10min for a auto sync. but still not working.

## Screenshots or Videos

I have video, if you can provide a place to upload it securly, as it shows my vault and all my usernames.

## Environment

- Device: iPhone 11 PRO
- Operating system: iOS 14.0.1
- Build Version (go to "Settings" → "About" in the app): 18A393
- Is this a Beta release? [Y/N] No - Public release

## Additional Context

On the video, i did not close the "SOMENAME APP" wich would have worked. But i didnt know it at the time.
I have also tried to wait for the sync, but it takes a long time before that happens.

**Comment by clayadams5226** [comment] 2020-10-20 21:00
Looks like a duplicate of https://github.com/bitwarden/mobile/issues/980

**Comment by mportune-bw** [comment] 2020-10-20 21:17
This sounds more like client/server sync issues to me (#980 pertains to app/extension sync)

**Comment by mstoffel-sag** [comment] 2020-10-21 08:19
Same issue here on ios 14.1 app version 2.6.2 (278). My problem is, I change something in the browser, I sync the bitwarden app in ios. The password is now visible in the bitwarden app on ios. But when I try autofill to an app it is neither suggested nor I can find it via search in the autofill dialog.

**Comment by mportune-bw** [comment] 2020-10-21 13:00
@mstoffel-sag That's the issue fixed in #980 and will be in the next release.

**Comment by PatrickRorth** [comment] 2020-10-21 18:40
> @mstoffel-sag That's the issue fixed in #980 and will be in the next release.

When will that this release be?

**Comment by Neurotoxin001** [comment] 2020-10-26 18:37
Just noticed that too.

**Comment by PatrickRorth** [comment] 2020-11-18 09:38
@mportune-bw Is there an ETA on when the next update is released, fixing the issue?

**Comment by mportune-bw** [comment] 2020-11-18 22:43
@PatrickRorth Barring any issues the new release is going out this week.

**Comment by matthttam0** [comment] 2020-11-21 17:17
hello, @mportune-bw
I just update to 2.7.0 on iOS, and the issu is still there...

**Comment by mportune-bw** [comment] 2020-11-21 22:09
@matthttam0 This is still an open issue with sync between the app and server (i.e. main app and autofill extension doesn't show changes made from web vault).  2.7.0 (via #1112) fixes the issue with sync between the app and autofill extension (i.e. main app shows updated data but autofill extension does not).

**Comment by matthttam0** [comment] 2020-11-22 09:30
Hello, @mportune-bw 
My bad, I first comment on this issue but saw that it was not what I thought. 
I was talking about sync between app and autofill extension (#1112).
I transfered my comment on the right post, and forgot to delete this one...

**Comment by yekver** [comment] 2020-12-22 19:05
Any chance to fix this annoying bug?(

**Comment by cscharf** [comment] 2020-12-22 21:18
@yekver , yes, we've prepared the release to resolve this, v2.7.2, just waiting for app store approval of the new version.

**Comment by s4nd3r84** [comment] 2021-01-19 13:55
Hi have the same problem here. 
iOS 14.2
Bitwarden 2.7.2 (401)

I don't think the latest update fixed the problem.

**Comment by Tataru-Taru** [comment] 2021-01-22 20:28
Can confirm the issue is fixed in 2.8. Many thanks :D

**Comment by cscharf** [comment] 2021-01-25 19:29
Closing this issue for now, thanks to all for your patience while we got this issue resolved. If you continue to experience this problem after updating to the latest version on iOS please open a new issue, linked to this one, with appropriate recreation steps, detail, etc.

**Closed by cscharf** 2021-01-25 19:29 UTC
