### ISSUE TITLE
Whatsapp (android) Passkey not supported

### ISSUE THREAD

**Issue by Ironfist69** [bitwarden/mobile#3226] opened 2024-05-04 14:17 UTC
### Steps To Reproduce

1. Go to 'Whatsapp android' 
2. Then Settings > Account > Passkeys
3. Click on "Create a Passkey"
4. Select Bitwarden and create passkey.
5. Unlock vault and try to save it. Error will show up.

### Expected Result

It should save Whatsapp passkey inside vault

### Actual Result

Error creating passkey
Passkeys not supported for this app

### Screenshots or Videos

![Screenshot_20240504_193627_Credential Manager](https://github.com/bitwarden/mobile/assets/70436487/70776d5c-05bd-4810-aa85-1c4dd9fda45b)

![Screenshot_20240504_193814](https://github.com/bitwarden/mobile/assets/70436487/8276d993-063c-4c2a-a275-3ffa6f6c53a7)

### Operating System

Android

### Operating System Version

Android 14 - OneUI 6.0

### Device

SM-A135F/DS

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.4.1 (10283)

### Beta

- [X] Using a pre-release version of the application.

**Comment by aamadorj** [comment] 2024-05-04 21:02
According to this [Bitwarden Help Document](https://bitwarden.com/help/storing-passkeys/#tab-android-(beta)-3XutklkReT3Gw0l1qHhBem), for Android "while passkeys for web browsers are supported, support for is apps coming soon in a future beta build".  This can be the cause of @Ironfist69 issue.

**Comment by SergeantConfused** [comment] 2024-05-06 11:55
Hello @Ironfist69,

Thank you for this report. As @aamadorj had mentioned, this is to be expected [at this stage of the Beta release](https://bitwarden.com/help/storing-passkeys/#tab-android-(beta)-3XutklkReT3Gw0l1qHhBem); You are more than welcome to subscribe to the [Bitwarden Release Announcements](https://bitwarden.com/help/releasenotes/#release-announcements) if you wish to stay in the loop about future versions.

I will now close this GitHub report. If anyone has any questions or concerns, please feel free to get in touch via the contact form within the [Help Centre](https://bitwarden.com/help/).

Thank you all,

**Closed by SergeantConfused** 2024-05-06 11:55 UTC
Labels: bug
