### ISSUE TITLE
Android - Inline autofill does not copy the TOTP code to the clipboard.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#1712] opened 2022-01-09 18:44 UTC
### Steps To Reproduce

1. Attempt to log into an account with TOTP 2FA (I used the Bitwarden Web Vault).
2. Tap on one of the credential fields.
3. Tap on the relevant vault item from the Inline Autofill' suggestions.
4. Attempt to paste the 6-digit TOTP code from the clipboard.

### Expected Result

The code from the Bitwarden TOTP Generator should be present in the clipboard.

### Actual Result

The clipboard is empty.

### Screenshots or Videos

N/A.

### Additional Context

Tapping on Bitwarden and opening the Bitwarden vault via Inline Autofill, instead of tapping on the vault item directly, and then tapping on the relevant vault item from that list causes the 6-digit TOTP code to be copied into the clipboard.

### Operating System

Android

### Operating System Version

11.

### Device

Samsung Note 10+.

### Build Version

2.15.0 (4125).

### Beta

- [ ] Using a pre-release version of the application.

**Comment by shilobacca** [comment] 2022-03-02 21:45
I can confirm the exact behavior for me. Also confirm the exact behavior as outlined in "Additional Context".

Android 12
Pixel 5
BitWarden 2.16.2

**Comment by mind-overflow** [comment] 2022-07-27 10:52
hey, just a heads up. the issue is still there on. i have a Xiaomi 12x on Android 12, and Bitwarden 2022.6.2.

**Comment by mthespian** [comment] 2022-08-03 20:07
I'm having the same issue, except I can't translate the "Additional Context" workaround into action.  I'm clearly missing something to make that happen.

Android 12
Samsung Galaxy S21
BitWarden 2022.6.2 (4851)

**Comment by Jordan-4** [comment] 2022-08-09 20:20
same problem.

Android 11
Xiaomi Redmi Note 8 Pro

**Comment by dbosompem** [comment] 2022-08-16 18:23
Hi all, thank you for bringing this to our attention that issue still persists. The team will reproduce this, and we will proceed to resolving this. Thanks!

**Comment by rdaugherty** [comment] 2022-08-17 13:52
QA has confirmed that this issue still exists. Handing this ticket over to the development team.

**Comment by techbot2342** [comment] 2022-09-15 01:48
still an issue...

**Closed** 2022-12-05 17:49 UTC
Labels: bug

**Comment by rokejulianlockhart** [comment] 2023-01-19 00:40
This continues, but solely intermittently.
