### ISSUE TITLE
Mobile Safari iOS doesn't auto-detect / auto-suggest local network sites with custom port(s)

### ISSUE THREAD

**Issue by mikey32230** [bitwarden/mobile#804] opened 2020-03-30 20:03 UTC
## Describe the Bug

Mobile Safari (iOS) does auto-detect nor auto-fill local network sites with custom port(s).

For example, when accessing the following site/URL via Mobile Safari (iOS):
`http://qbittorrent:8090`

Bitwarden does not auto-detect the site and does not provide a suggestion to auto-fill credentials.
I must manually click the Bitwarden "Passwords" button and search for the site.

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/7960413/77956275-a1509200-729f-11ea-8a7f-0c5c5d74c4f4.png)

## Environment

- Device: iPhone 7
- Operating system: iOS 13.4
- Build Version (go to "Settings" → "About" in the app): Version: 2.3.1 (64)
- Is this a Beta release? No

**Comment by kspearrin** [comment] 2020-04-04 00:53
This seems like an issue with iOS itself. We do not do any of the detection.

**Comment by djsmith85** [comment] 2022-03-11 00:36
Hi @mikey32230 you could possibly test, setting the detection to host.

While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2022-03-11 00:36 UTC

**Comment by kennymc-c** [comment] 2023-02-19 15:17
As mentioned in the community forums this is also a problem when running multiple services on the same ip/url but on different ports: https://community.bitwarden.com/t/iphone-app-port-in-url-not-being-used-even-with-host-setting-in-uri/28615
The Bitwarden mobile app seems to detect the port correctly when clicking the Bitwarden... option in Safari's auto-fill account menu but the default auto-fill account seems to be always the first account for the url.
I am wondering if anyone of the Bitwarden devs have filed a bug for this at Apple in the meantime? If so, has there been any feedback?
