### ISSUE TITLE
Crash on Android when typing master password a 2nd time

### ISSUE THREAD

**Issue by alexgieg** [bitwarden/mobile#2740] opened 2023-08-31 22:19 UTC
### Steps To Reproduce

1. Open the Bitwarden app and biometrically unlock it.
2. Go to any entry that requires typing the master password a 2nd time to view or edit it.
2. Type the master password a 2nd time.
3. Tap Submit.

Alternatively:

1. Open a site on a mobile browser that requires a password which in turn is protected within Bitwarden with the requirement to type the master password a 2nd time.
2. Tap on the Bitwarden button that appears below the password entry field when the field is selected.
3. Bitwarden loads and asks for biometric unlock.
4. Unlock it.
5. Tap the entry that requires retyping the master password.
6. Type the master password a 2nd time.
7. Tap Submit.

### Expected Result

Bitwarden should copy/paste/show/allow editing the entry protected by the requirement to type the master password a 2nd time.

### Actual Result

If entering Bitwarden directly, once the master password is typed a second time, it crashes, and the Android screen to optionally submit feedback appears.

If Bitwarden is loaded from a web browser by typing its button on a password field, once the master password is typed a second time an error message appears informing there was an error retrieving the information, and the password filling fails.

This combined bug makes it impossible to access and use entries configured to require typing the master password a 2nd time. They can only be accessed by other means such as the desktop web browser, desktop browser extension etc.

### Additional Context

Tested on two different phones with the same result. It started happening after the most recent version of Bitwarden for Android was downloaded and installed from the Google Play Store.

### Operating System

Android

### Operating System Version

Android 10

### Device

a) Motorola Moto G 8 Power; b) PAX M30.

### Build Version

2023.8.0 (7466)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment] 2023-08-31 22:32
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6153.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2023-08-31 22:32 UTC
Labels: bug

**Comment by alexgieg** [comment] 2023-08-31 22:35
> Thank you for your report, it seems like it is a duplicate of this one [bitwarden/clients#6153](https://github.com/bitwarden/clients/issues/6153).

They don't seem to be the same. That one talks about issues on the Windows application / browser. Mine is on Android. Are they related? Should I copy this information over there?

**Comment by sammbw** [comment] 2023-09-01 02:57
Hello @alexgieg,

At this stage we believe the root cause to be the same. If you could copy and paste your information across, that would be excellent!
