### ISSUE TITLE
Android app freezes on protected passwords

### ISSUE THREAD

**Issue by jeffeb3** [bitwarden/mobile#2757] opened 2023-09-10 17:04 UTC
### Steps To Reproduce

1. Open BitWarden app
2. Unlock the vault
3. Search for a password that has additional protection
4. Click on the eyeball to see the password
5. Re enter your master password to unlock it

### Expected Result

It should show me the protected password

### Actual Result

App crashes

### Additional Context

It also fails when trying to auto fill from the app after reentering my master password.

Passwords without additional protection don't have a problem. The same problem on my desktop works fine.

### Operating System

Android

### Operating System Version

13

### Device

pixel 6 pro

### Build Version

TQ3A.230805.001.A1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by robations** [comment] 2023-09-10 21:24
I'm seeing what looks like the same issue on iOS and iPadOS.

Editing the entry or requesting to view the secret crashes after entering the master Bitwarden password.

**Comment by sammbw** [comment] 2023-09-10 22:30
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/6153

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2023-09-10 22:30 UTC
Labels: bug

**Comment by jeffeb3** [comment] 2023-09-10 23:01
Thanks for staying on top of it. I searched for issues labeled with android and I didn't find it.

**Comment by jeffeb3** [comment] 2023-09-10 23:04
I just turned off biometric login (based on the questions in the linked issue). 

I closed the app, and unlocked with my password.

Then the protected passwords did unlock and stopped crashing. 

So it definitely seems related to bio unlock.
