### ISSUE TITLE
App crashes when generating password 

### ISSUE THREAD

**Issue by sord1d** [bitwarden/mobile#2176] opened 2022-11-08 11:28 UTC
### Steps To Reproduce

Important: The vault has to be locked to reproduce this error. If the vault has been unlocked via the app previously this doesn't seem to be an issue. 

1. Visit any site that has no saved credentials 
2. Click on vault is locked above your keyboard
3. Enter your master password 
4. Click on add an item
5. Generate a new password 

### Expected Result

The vault should be unlocked
A new password should be generated 

### Actual Result

The app crashes as soon as you hit that generate button.
When you try it again your vault ist still locked (maybe because of the crash?), so the issue repeats itself.

### Operating System

Android

### Operating System Version

12

### Device

Samsung S20 plus

### Build Version

Version: 2022.10.0 (5247)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment] 2022-11-08 11:34
Hi @sord1d and thank you for your report.

This seems to be a duplicate of https://github.com/bitwarden/mobile/issues/2149, which has already received a fix.

This should be resolved with the next release (2022.11)

Closing this now.

**Closed by djsmith85** 2022-11-08 11:34 UTC
Labels: bug

**Comment by sord1d** [comment] 2022-11-08 11:37
Hey @djsmith85 , thanks for the quick response.
I'm sorry I wasn't aware of the other issue, I guess I just searched in the open issues.
Thanks for your great work.
