### ISSUE TITLE
Android - Tapping the 'Help and feedback' button in Android 11 does nothing.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#1181] opened 2020-12-15 13:31 UTC
## Describe the Bug
Tapping the 'Help and feedback' button in the Settings menu does nothing.

## Steps To Reproduce
1. Open the Android Bitwarden client.
2. Go to Settings.
3. Tap on 'Help and feedback'.

## Expected Result
To open a browser and go to http://help.bitwarden.com/.

## Actual Result
Nothing happens.

## Screenshots or Videos
N/A.

## Environment

- Device: Google Pixel 2.
- Operating system: Android 11.
- Build Version: 2.7.0 (3258).
- Is this a Beta release? N.

## Additional Context
This was also reported to be happening on a Pixel 3 running Android 11.

**Comment by SumuduF** [comment] 2020-12-15 22:35
I suspect this is the same as https://github.com/bitwarden/mobile/issues/1164

Does launching vault item URIs work for you? How about "Bitwarden Web Vault" item on the Settings page?

**Comment by mportune-bw** [comment] 2020-12-16 22:16
Duplicate of #1164

**Closed by mportune-bw** 2020-12-16 22:16 UTC
