### ISSUE TITLE
Passwords are not refreshing 

### ISSUE THREAD

**Issue by AlexCarrithers** [bitwarden/mobile#393] opened 2018-10-13 07:56 UTC
Operating System: iOS 12.0
Bitwarden Version: 1.19.4

The iOS application does not appear to refresh the password cache following a change made to the vault. Specifically, this occurred when I updated the password to one of my existing accounts. It is necessary to logout and back in in order to fetch new passwords.

I'm not sure if this is a bug or expected behaviour. If the latter, is it feasible to add some kind of refresh mechanism to fetch changes to the vault? If so, I will add a feature request on the forum.

**Comment by kspearrin** [comment] 2018-10-15 02:58
A few people have reported this but I haven't been able to reproduce it yet. Does this happen every time you make a change? What if you toggle the autofill for Bitwarden off and back on under iOS Settings?

**Comment by AlexCarrithers** [comment] 2018-10-15 10:59
I'm not sure. I can't reproduce it now either unfortunately. I will keep an eye on it and if it shows up again I will test and report back.

**Comment by zzhhbyt1** [comment] 2018-12-09 23:45
This thing happens to me sometimes from the first time I get and setup my XR. Sometimes it happens after I edited an account and sometimes an change synced from another device. But I don't know how to effectively produce it, either.
Rebooting always solves this. Maybe I'll try add account during picking account.

**Comment by zzhhbyt1** [comment] 2018-12-09 23:50
When trying to add an account after the bug appeared, the app will not return to account picking view after hitting save.
But then press cancel and call the password manager again, it will refresh.

**Comment by zzhhbyt1** [comment] 2018-12-10 00:41
I just reproduced this bug on iOS 12.1.1(16C50) & Bitwarden 1.20.0(43).
Reboot. Unlock. Open Firefox. Open a  webpage with a password form. Open Bitwarden. Change the password to the account of the website. Switch back to Firefox and use auto fill.
It fills the old password.

**Comment by AlexCarrithers** [comment] 2018-12-10 12:59
I have this problem again now too. 

To answer the question you posed to me previously, @kspearrin, toggling autofill off and on in iOS settings does not resolve the problem. Cycling the power on the device does not resolve the problem either. 

The only thing that resolves the problem is logging out and back into Bitwarden.

**Comment by zzhhbyt1** [comment] 2018-12-10 13:02
Really? I think I did temporarily resolve it by restart or add account through auto fill page.

**Comment by AlexCarrithers** [comment] 2018-12-10 13:05
I tested it twice. Even tried a hard reset. Neither fixed the problem. I can try again when I next notice the bug, but I am not optimistic.

**Comment by zzhhbyt1** [comment] 2018-12-10 15:49
> 
> 
> I just tested this again doing the following:
> 
>     1. Went to github.com in Safari, saw that my user1/password1 login as being suggested in the keyboard.
> 
>     2. Opened Bitwarden main app and edited the user1 login and changed it to user2/password2
> 
>     3. Went back to Safari and refreshed github.com. Now I see user2/password2 being suggested, as expected.
> 
> 
> I am not sure what I am doing differently here, but I cannot reproduce the issue.

I'm sorry. I think it's me to blame that I didn't clarify one should actually open up the suggestion in the keyboard and use that to fill-in before then opening the Bitwarden main app to edit.
And I do think a restart is needed to reproduce the problem.

So allow me to post the more explained steps:
1. Restart the phone.
2. Go to github.com in Firefox, saw that my user1/password1 login as being suggested in the keyboard.
3. Use that to auto-fill.
4. Open Bitwarden main app and edited the user1 login and changed it to user2/password2
5. Go back to Firefox and refresh github.com. And nothing changed there.

Additional steps to "update it":
1. Click on any password field to raise the keyboard with auto-fill options.
2. Open up Bitwarden auto-fill.
3. Add an random entry. (Sometimes the auto-fill page just get stuck here with "the saving and the circle".)
4. Click cancel and then cancel - as the "Entry adding" routine don't send you back and let you stay on "edit view" - to get back to the password entering field.
5. Try again with "refreshed" entries.

I hope I helped in some way.

**Comment by kspearrin** [comment] 2018-12-10 15:55
> So allow me to post the more explained steps:
> 
> 1. Restart the phone.
> 2. Go to github.com in Firefox, see that my user1/password1 login as being suggested in the keyboard.
> 3. Use that to auto-fill.
> 4. Open Bitwarden main app and edit the user1 login and change it to user2/password2
> 5. Go back to Firefox and refresh github.com. And nothing changed there like I just tried again a moment ago.

Tried these exact steps, except using Safari browser, and it works as expected.

**Comment by zzhhbyt1** [comment] 2018-12-10 16:04
> 
> 
> > So allow me to post the more explained steps:
> > 
> > 1. Restart the phone.
> > 2. Go to github.com in Firefox, see that my user1/password1 login as being suggested in the keyboard.
> > 3. Use that to auto-fill.
> > 4. Open Bitwarden main app and edit the user1 login and change it to user2/password2
> > 5. Go back to Firefox and refresh github.com. And nothing changed there like I just tried again a moment ago.
> 
> Tried these exact steps, except using Safari browser, and it works as expected.

Okay, I gave a try on Safari and I find these two did have some differences, like you will be able to directly choose an account entry without go into the Bitwarden auto-fill window. 
But for me Firefox (and Gboard) user and any user have multiple account then have to choose one, we seems to always be using the Bitwarden auto-fill window.
Anyway, if you would give another try and this time use the Bitwarden auto-fill window. You may see that the entries there is still not updated.

**Comment by zzhhbyt1** [comment] 2018-12-10 16:16
BTW, maybe someone can explain why Firefox can't get that nice and clean password fill-in special keyboard?
I always have to use the "(key icon) Passwords" button and raise the Bitwarden auto-fill window to fill-in.
Which part does the problem lie in, Apple or Firefox or Bitwarden?

**Comment by kspearrin** [comment] 2018-12-10 16:17
I see. So the problem is not with the keyboard options, but with the popup window. I can reproduce this in Safari now too.

> BTW, maybe someone can explain why Firefox can't get that nice and clean password fill-in special keyboard? I always have to use the "(key icon) Passwords" button and raise the Bitwarden auto-fill window to fill-in. Which part does the problem lie in, Apple or Firefox or Bitwarden?

That's a Firefox issue. Sounds like they haven't implemented the new autofill extension keyboard options like Safari.

**Comment by kspearrin** [comment] 2018-12-10 16:57
Should be fixed in next version. https://github.com/bitwarden/mobile/commit/3b9f4433ad4362c33a01404ae36b1987b2f3dec6

**Closed by kspearrin** 2018-12-10 16:57 UTC
Labels: bug

**Comment by joallard** [comment] 2020-03-12 16:01
I’m getting this in the latest Chrome iPad. Passwords added within the last week just don’t appear.
