### ISSUE TITLE
IOS: Autofill doesn’t work

### ISSUE THREAD

**Issue by Fortunate-111** [bitwarden/mobile#3240] opened 2024-05-13 18:10 UTC
### Steps To Reproduce

1. Go to a website that you want to log into on Safari on an iPhone using Bitwarden.
2. Click on a blue box that should appear prompting you to autofill your username and password.

### Expected Result

My username and password to be autofilled.

### Actual Result

Nothing happens.

### Screenshots or Videos

![IMG_8794](https://github.com/bitwarden/mobile/assets/110201604/24e70d03-5fea-4a85-8e82-24e9738f8b39)

### Additional Context

If it doesn’t work, you can try autofilling your password again by clicking ‘passwords’ above the keyboard. Usually I find this method autofills my passwords.

### Operating System

iOS

### Operating System Version

iOS 17.4.1 (21E236)

### Device

iPhone SE 2nd Generation

### Build Version

Version: 2024.4.2 (7528)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Neonwarden** [comment] 2024-05-13 18:29
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Fortunate-111** [comment] 2024-05-13 18:31
No worries, I am glad I could help!

**Comment by pheiduck** [comment] 2024-05-18 10:07
Version: 2024.5.1 (7674)
iOS: 17.5
Still not working.

**Comment by StefanLobbenmeier** [comment] 2024-05-27 21:19
As a workaround you can ignore the suggested passwords and open Bitwarden from the dialog instead, autofilling from there does not have the issue (but is slightly more tedious)

**Comment by Zingo21** [comment] 2024-05-28 09:07
I have tried that, but it's the same result as with the blue button that it won't autofill

**Comment by StefanLobbenmeier** [comment] 2024-05-28 09:34
oh weird, just to clarify there should be 3 methods:

1. click on the button to autofill in 1 step (does not work)
2. click on the key in the corner and on the username to autofill in 2 steps (does not work either) 
3. click on the key in the corner, then on bitwarden, a bitwarden modal asks you to authenticate and after that you select the entry in the bitwarden modal (works for me)


do none of those methods work for you?

**Comment by Zingo21** [comment] 2024-05-28 12:18
I have tried all three methods, I clicked on the key icon and clicked on my credentials that is stored in my vault But it still wouldn't ask me to authenticate. 

The only thing working for me is that I go to the app and copy my password from any of my accounts that is stored in the vault and paste it in my browser.

**Comment by Fortunate-111** [comment] 2024-05-29 12:49
I have tested all of them and found that they are all working for me.

**Comment by Fortunate-111** [comment] 2024-05-29 12:52
Idk if this will help but I updated to IOS 17.5.1

**Comment by Zingo21** [comment] 2024-05-29 14:16
I'm on iOS 16.7.8 and I still have the issues

**Comment by LittleTurtle2333** [comment] 2024-05-30 17:46
it didn’t work on 2024.4.2 or 2024.5.1. I downgraded to 2024.4.0 and it was fine.
![C83AFFEF-931A-4C16-A05C-99A4E771CD66](https://github.com/bitwarden/mobile/assets/32336368/50fcdf6a-9a99-44e6-9cc8-996d21536ddb)

**Comment by john-gom** [comment] 2024-06-02 10:52
> oh weird, just to clarify there should be 3 methods:
> 
> 1. click on the button to autofill in 1 step (does not work)
> 2. click on the key in the corner and on the username to autofill in 2 steps (does not work either)
> 3. click on the key in the corner, then on bitwarden, a bitwarden modal asks you to authenticate and after that you select the entry in the bitwarden modal (works for me)
> 
> do none of those methods work for you?

Only option 3 is working for me. BW Version 2024.5.1 (7674), iOS 16.1.1, iPhone 12

**Comment by john-gom** [comment] 2024-06-02 13:15
> Only option 3 is working for me. BW Version 2024.5.1 (7674), iOS 16.1.1, iPhone 12

Just upgraded to iOS 17.5.1 and that seems to have fixed it.

**Comment by Fortunate-111** [comment] 2024-06-02 13:52
@LittleTurtle2333 what iOS version are you using? I found updating to the latest version (iOS 15.7.1) fixed the problem for me so perhaps it may fix it for you?

**Comment by simongapp** [comment] 2024-06-07 20:22
Hi,
I can confirm this issue on an iPhone 8 with iOS 16.7.8 and Bitwarden Version: 2024.5.1 (7674). 

The workaround to use Bitwarden instead of the suggested user name is working for me.

**Comment by atoussama** [comment] 2024-06-12 20:02
Having this exact issue for a while now, and i'm on iOS 16.3.1

**Comment by LittleTurtle2333** [comment] 2024-06-12 21:40
> Having this exact issue for a while now, and i'm on iOS 16.3.1

I am also 16.3.1, which seems to have been restored in this issue, and it has been fixed

https://github.com/bitwarden/mobile/issues/3225#issuecomment-2155334614

**Comment by LittleTurtle2333** [comment] 2024-06-12 21:45
I just tested the latest ci. It is indeed fixed. It's not officially released yet

**Comment by Zingo21** [comment] 2024-06-14 12:57
The update solved the problem

**Comment by Greenderella** [comment] 2024-06-19 15:35
As the issue appears to have been solved, I will proceed to close it.

Thank you everybody!

**Closed by Greenderella** 2024-06-19 15:35 UTC
Labels: bug
