### ISSUE TITLE
Android - Cannot View or Edit passwords while Login with Biometrics or Pin is enabled

### ISSUE THREAD

**Issue by bathiel** [bitwarden/mobile#2781] opened 2023-09-19 17:42 UTC
### Steps To Reproduce

1. Enable on Settings 'Unlock with Biometrics' or 'Unlock with PIN code'
2. Login into the app
3. Go to any Login vault and Open it
4. Tap on View or Edit the password
5. Enter the Master Password
6. App crashes

If I disable Biometrics or PIN code I can view or edit the passwords. Tested on 3 phones I have: Samsung Z fold 5, Samsung S20, Xiaomi Mi A2 lite

I found that other people are facing this issue: [Reddit](https://www.reddit.com/r/Bitwarden/comments/164eg71/comment/jznf5oj/?utm_source=share&utm_medium=web2x&context=3)

### Expected Result

Ability to view or edit the password

### Actual Result

App crashes, it closes immediately

### Operating System

Android

### Operating System Version

Android 13

### Device

Samsung Z Fold 5

### Build Version

2023.8.0(7466)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by bahaedin** [comment] 2023-09-20 22:56
Same problem bro 
version 2023.8.0 from Google play store 
Android 13

**Comment by djsmith85** [comment] 2023-09-21 08:10
Duplicate of https://github.com/bitwarden/mobile/issues/2733

**Comment by djsmith85** [comment] 2023-09-21 08:10
Hi @bathiel and @bahaedin ,

This seems to have previously been reported with https://github.com/bitwarden/mobile/issues/2733 and a fix has been issued with https://github.com/bitwarden/mobile/pull/2713 which will be included in the next release (2023.9)

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2023-09-21 08:10 UTC
Labels: bug
