### ISSUE TITLE
iOS - Cannot unlock with Face ID on autofill

### ISSUE THREAD

**Issue by nyuszika7h** [bitwarden/mobile#1263] opened 2021-02-13 16:01 UTC
## Describe the Bug

When attempting to autofill a password, Bitwarden does not scan Face ID, and tapping "Unlock with Face ID" has no effect.

## Steps To Reproduce

1. Enable Face ID in Bitwarden
2. Enable password autofill
3. Enter your master password
4. Try to autofill a password

## Expected Result

Bitwarden should authenticate with Face ID.

## Actual Result

The Face ID authentication does not happen, and tapping "Unlock with Face ID" has no effect either.

## Screenshots or Videos

https://femto.pw/rruk

## Environment

- Device: iPhone XR
- Operating system: iOS 14.5 beta
- Build Version: 2.8.0 (449)
- Is this a Beta release? No

## Additional Context

Face ID unlock works fine for the Bitwarden app itself, just not for autofill. It was working before.

I have already tried uninstalling Bitwarden, rebooting my device and reinstalling Bitwarden. It didn't help.

**Comment by nyuszika7h** [comment] 2021-02-13 20:27
Update: I restored my phone to iOS 14.4 and it works fine. So it seems to be an iOS 14.5-specific bug. However, Face ID with 1Password autofill works fine on 14.5.

**Comment by Kokorone** [comment] 2021-02-16 21:18
> Update: I restored my phone to iOS 14.4 and it works fine. So it seems to be an iOS 14.5-specific bug. However, Face ID with 1Password autofill works fine on 14.5.

Try again with 14.5 dev beta 2. Working for me since updating today

**Comment by maciekb94** [comment] 2021-02-17 15:29
I am having the same issue - iPhone 11, iOS 14.4. Relogging, reinstalling, autofill reconfigure didn't help.

**Comment by Mennaruuk** [comment] 2021-02-18 22:20
For me, the option existed initially. When I clicked it, and then clicked "Don't Allow", that's when it disappeared entirely. Restarting my iPhone X didn't help.

**Comment by Subterrane** [comment] 2022-01-12 21:10
> For me, the option existed initially. When I clicked it, and then clicked "Don't Allow", that's when it disappeared entirely. Restarting my iPhone X didn't help. The only way I was able to resolve this was reinstalling the app.

Same. Option was missing. Remove app and re-install, FaceID option magically came back. Thanks!

**Comment by djsmith85** [comment] 2022-03-11 01:44
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2022-03-11 01:44 UTC
