### ISSUE TITLE
ios 15.3 always crash when click the app

### ISSUE THREAD

**Issue by RatedR9** [bitwarden/mobile#1749] opened 2022-02-03 15:19 UTC
### Steps To Reproduce

click on the app

### Expected Result

Fix the crash as soon as possible 

### Actual Result

No

### Screenshots or Videos

The words explain exactly so the videos are not necessary 

### Operating System

iOS

### Operating System Version

15.3

### Device

iPhone 12 pro Max

### Build Version

版本: 2.15.0 (1225)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment] 2022-02-12 23:40
Thanks for the report. I'm unable to reproduce this, are you still having this issue with the latest update?

**Comment by SergeantConfused** [comment] 2023-09-12 12:11
Hi @RatedR9,

Could you please check this thread out (https://github.com/bitwarden/mobile/issues/2478) and let me know if that is what you are experiencing?


Thank you in advance,

**Comment by SergeantConfused** [comment] 2023-09-25 15:44
Hi @RatedR9,

I will proceed and close this GitHub report as a Duplicate because it seems that what you are reporting is the same as (https://github.com/bitwarden/mobile/issues/2478). Please feel free to let me know if anything comes up; And you're more than welcome to comment in that thread if you'd like to add any details.


All the best,

**Closed by SergeantConfused** 2023-09-25 15:44 UTC
Labels: bug
