### ISSUE TITLE
After the Android client is updated to a version after 2023.9, regardless of the password library timeout setting, it will time out after restarting the application and require the main password to be re-entered

### ISSUE THREAD

**Issue by zzy-ac** [bitwarden/mobile#2807] opened 2023-09-30 15:36 UTC
### Steps To Reproduce

4. Click on '...'

### Expected Result

I hope the password store timeout setting here can take effect normally, as in versions before March 2023

### Actual Result

After the Android client is updated to a version after 2023.9, regardless of the password library timeout setting, it will time out after restarting the application and require the main password to be re-entered

### Operating System

Android

### Operating System Version

Android13

### Device

redme note 11 t pro

### Build Version

2023.9.0 and 2023.9.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment] 2023-10-01 13:19
Hi @zzy-ac,

Thank you for your report. It seems that this is a duplicate of (https://github.com/bitwarden/mobile/issues/2787) which is affecting our Android and iOS clients.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in that thread - our engineering team will be happy to review these.

I will now proceed and close this report.

Thank you again,

**Closed by SergeantConfused** 2023-10-01 13:19 UTC
Labels: bug
