### ISSUE TITLE
Password Display error

### ISSUE THREAD

**Issue by darksim33** [bitwarden/mobile#3166] opened 2024-04-17 11:46 UTC
### Steps To Reproduce

Create a password containing **<** on android.
Save the password. 
On the entry show the password.

### Expected Result

The **<** is displayed as a usual special character

### Actual Result

All following symbols are coded in red like they were special characters.
The **<** is not showing at all

### Operating System

Android

### Operating System Version

14 - AP1A.240405.002

### Device

Pixel 6A

### Build Version

2024.4.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment] 2024-04-17 12:23
Duplicate of https://github.com/bitwarden/mobile/issues/3110

**Comment by djsmith85** [comment] 2024-04-17 12:23
Hi @darksim33!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/mobile/issues/3110

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-04-17 12:23 UTC
Labels: bug
