### ISSUE TITLE
"Scan when password field focused" doesn't work in the latest version of Opera mobile for Android

### ISSUE THREAD

**Issue by DanielTrifonov** [bitwarden/mobile#313] opened 2018-05-13 15:52 UTC
As I said in the title, this particular option stopped working when I updated the Android version of Opera mobile. I tested it with other browsers and it works fine.

**Comment by kspearrin** [comment] 2018-05-13 16:16
Do the other options work?

**Comment by kspearrin** [comment] 2018-05-19 01:54
I just tested this and can reproduce it. After debugging the problem it seems that Opera is no longer sending `ViewFocused` events when you focus input fields on a webpage. Not sure why not but there isn't really anything we can do about it. You'll have to use one of the other methods I guess.

Closing since it is an Opera bug.

**Closed by kspearrin** 2018-05-19 01:54 UTC

**Comment by DanielTrifonov** [comment] 2018-05-19 04:51
Have any idea how I would proceed to report it? Do I just send them a message telling them that the app no longer sends viewfocused events?

**Comment by kspearrin** [comment] 2018-05-19 12:49
Just tell them that websites are no longer reliably returning accessibility [TYPE_VIEW_FOCUSED](https://developer.android.com/reference/android/view/accessibility/AccessibilityEvent#TYPE_VIEW_FOCUSED) events anymore.
