### ISSUE TITLE
Autofill not working correctly on Cromite

### ISSUE THREAD

**Issue by Shadowvaporwarez** [bitwarden/mobile#2709] opened 2023-08-20 10:15 UTC
### Steps To Reproduce

Using Cromite 

1. Tap on a username and password field
2. Bitwarden opens
3. Displays results for org.cromite.cromite
4. Manually search for the URI/App to correctly autofill 

### Expected Result

Should open the specific URI

### Actual Result

Opens to search org.cromite.cromite for any field on any URI

### Screenshots or Videos

![Screenshot_2023-08-20-11-11-19-90_edf9c6c5202cf0aae90965d36a8e7fc4](https://github.com/bitwarden/mobile/assets/96532814/4807a15e-f33c-47ae-9148-e6f7c6ba573c)
![Screenshot_2023-08-20-11-07-34-54_5dca195d7d09adf043e42a8f3ad62b19](https://github.com/bitwarden/mobile/assets/96532814/c09c1266-b362-4a9f-9838-98b0a3a8587c)

### Operating System

Android

### Operating System Version

13

### Device

One Plus 11

### Build Version

Version: 2023.7.0 (6781)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment] 2023-08-20 18:32
Duplicate of #2639

**Comment by djsmith85** [comment] 2023-08-20 18:32
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a [Feature Requests](https://community.bitwarden.com/c/feature-requests) section for submitting, voting for, and discussing requests like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Closed** 2023-08-20 18:32 UTC
Labels: bug
