### ISSUE TITLE
Crash when successful login to a custom hosted API

### ISSUE THREAD

**Issue by TecHunter** [bitwarden/mobile#391] opened 2018-10-10 09:01 UTC
When using the js CLI I can interact with my API but when I try to use the mobile app I get this error :

> 
> 10-10 10:53:43.827 24650 24650 I MonoDroid: UNHANDLED EXCEPTION:
> 10-10 10:53:43.832 24650 24650 I MonoDroid: System.ArgumentException: encryptedString
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at Bit.App.Models.CipherString..ctor (System.String encryptedString) [0x0000e] in <dd3f0008bd104a478960cdf88b4bf769>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at Bit.App.Services.AuthService+<ProcessLoginSuccessAsync>d__50.MoveNext () [0x0005a] in <dd3f0008bd104a478960cdf88b4bf769>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid: --- End of stack trace from previous location where exception was thrown ---
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <75c596ebdbf44e519fe4817dfb1ae2ed>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <75c596ebdbf44e519fe4817dfb1ae2ed>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <75c596ebdbf44e519fe4817dfb1ae2ed>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <75c596ebdbf44e519fe4817dfb1ae2ed>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at Bit.App.Services.AuthService+<TokenPostAsync>d__48.MoveNext () [0x00324] in <dd3f0008bd104a478960cdf88b4bf769>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid: --- End of stack trace from previous location where exception was thrown ---
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <75c596ebdbf44e519fe4817dfb1ae2ed>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <75c596ebdbf44e519fe4817dfb1ae2ed>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <75c596ebdbf44e519fe4817dfb1ae2ed>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <75c596ebdbf44e519fe4817dfb1ae2ed>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at Bit.App.Pages.LoginPage+<LogIn>d__21.MoveNext () [0x00231] in <dd3f0008bd104a478960cdf88b4bf769>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid: --- End of stack trace from previous location where exception was thrown ---
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <75c596ebdbf44e519fe4817dfb1ae2ed>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <75c596ebdbf44e519fe4817dfb1ae2ed>:0 
> 10-10 10:53:43.832 24650 24650 I MonoDroid:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <75c596ebdbf44e519fe4817dfb1ae2ed>:0 
> 10-10 10:53:43.833 24650 24650 I MonoDroid:   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <75c596ebdbf44e519fe4817dfb1ae2ed>:0 
> 10-10 10:53:43.833 24650 24650 I MonoDroid:   at Bit.App.Pages.LoginPage+<Entry_Completed>d__19.MoveNext () [0x00062] in <dd3f0008bd104a478960cdf88b4bf769>:0 
> 10-10 10:53:43.833 24650 24650 I MonoDroid: --- End of stack trace from previous location where exception was thrown ---
> 10-10 10:53:43.833 24650 24650 I MonoDroid:   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <75c596ebdbf44e519fe4817dfb1ae2ed>:0 
> 10-10 10:53:43.833 24650 24650 I MonoDroid:   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <bee533d01aa643458150160694e6a76a>:0 
> 10-10 10:53:43.833 24650 24650 I MonoDroid:   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <bee533d01aa643458150160694e6a76a>:0 
> 10-10 10:53:43.833 24650 24650 I MonoDroid:   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <bee533d01aa643458150160694e6a76a>:0 
> 10-10 10:53:43.833 24650 24650 I MonoDroid:   at (wrapper dynamic-method) System.Object.47(intptr,intptr)
> 10-10 10:53:43.835 24650 24650 W zygote64: JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
> 10-10 10:53:43.873  1399  1901 W InputDispatcher: channel 'fcd22a8 com.x8bit.bitwarden/md5b95ad25b85f158431f24aa9fc17a1c1e.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
> 10-10 10:53:43.874  1399  1901 E InputDispatcher: channel 'fcd22a8 com.x8bit.bitwarden/md5b95ad25b85f158431f24aa9fc17a1c1e.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
> 10-10 10:53:43.874  1399  1901 W InputDispatcher: channel '1699c6b com.x8bit.bitwarden/md5b95ad25b85f158431f24aa9fc17a1c1e.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
> 10-10 10:53:43.874  1399  1901 E InputDispatcher: channel '1699c6b com.x8bit.bitwarden/md5b95ad25b85f158431f24aa9fc17a1c1e.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
> 10-10 10:53:43.886  1399  2002 I ActivityManager: Process com.x8bit.bitwarden (pid 24650) has died: fore TOP 

Using Xperia XZ2 Android 8 not rooted/OEM locked (factory settings)
Same over 4G or wifi.
The API is hosted by AWS serverless Lambda based on this one https://github.com/vvondra/bitwarden-serverless

**Comment by kspearrin** [comment] 2018-10-10 13:38
Looks like you have some corrupted data.

**Comment by TecHunter** [comment] 2018-10-11 10:33
but it's working fine on desktop app and CLI. maybe add some error catch for cleaner log? I've added a 2factor and it asks me for the 2FA code then also crash if code is OK

**Comment by kspearrin** [comment] 2019-06-04 15:33
Can you try v2.0 from play store beta?

**Comment by djsmith85** [comment] 2022-03-01 23:35
Hi @TecHunter, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2022-03-01 23:35 UTC
