### ISSUE TITLE
iOS app crashes when attempting to edit specific entry

### ISSUE THREAD

**Issue by davidearl** [bitwarden/mobile#3387] opened 2024-09-10 12:26 UTC
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

Click on Edit for a particular entry

I think your production build notice above is out oif date. This is a production app, but it is the new one, so not clear which repo I should report it in.

### Expected Result

Edit the contents

### Actual Result

Crashes - app disappears completely

### Screenshots or Videos

n/a

### Additional Context

This is with a specific entry (for GitHub as it happens, though I have more than one github-related entry and the others are OK). All other entries can be edited OK. There's something in this particular one that makes it crash consistently.

Surprisingly, I can edit it OK on iPad. I was able to add TOTP there, and then go back to the iPhone and it still crashes, even after having been synced with the changes.

One thing where this differs from other entries is I have a note, and the note contains angle brackets. I'll experiment with that to see if that is the trigger for the crash.

Hopefully you have crash logs for this - that setting was turned on. They'll have been sent from 80.5.194.46

### Operating System

iOS

### Operating System Version

iOS 17.6.1

### Device

iPhone 13 mini

### Build Version

2024.7.1 (8086)

**Comment by cbw23** [comment] 2024-09-10 18:27
Hi there!

Thank you for your report, it seems like it is a duplicate of this one #3146. The recent update (2024.8.1) to the mobile app should address this issue.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-09-10 18:27 UTC
Labels: bug

**Comment by davidearl** [comment] 2024-09-10 19:07
Further testing shows it was indeed the dashes in my note that were causing it to crash. Removing them let me edit.

2024.8.1 isn't available to me yet. I'll check when it arrives.
