### ISSUE TITLE
Frozen dialogue in iPad autofill settings

### ISSUE THREAD

**Issue by kevinmickey** [bitwarden/mobile#586] opened 2019-08-25 22:04 UTC
Using Bitwarden version 2.2.1 on iPad Pro iOS 12.4:

Installed, created account, enabled autofill in iOS settings, and saw a blank dialogue pop up, that seemed to freeze or not accept any input over top of the Settings app.  After quitting the settings app, and disabling then re-enabling autofill, the same issue occurred, except I could now see part of the Bitwarden logo within the dialogue.

**Comment by kspearrin** [comment] 2019-08-30 13:46
Maybe a fix in next version. I wasn't able to find your crash report specifically, but I did find some that might indicate what is causing the problem here.

**Comment by Crocmagnon** [comment] 2019-09-02 14:17
I also had a similar issue after setting up the auto fill in iPad settings. In Firefox, sometimes, the popup is blank.
It happens a lot on iOS 13.1 beta but also happened on iOS 12.4 before I upgraded to the beta.

**Comment by partyka1** [comment] 2019-09-20 06:12
happens also on iPadOS 13.1 beta 4

**Comment by jcbvm** [comment] 2019-09-26 12:20
I can confirm this issue. It still happens to me with the final releases of iOS 13.1 and iPadOS 13.1. I do see a popup showing up with the bitwarden logo, but no authentication is asked, it just freezes.

**Comment by kspearrin** [comment] 2019-10-01 01:23
Possible fix in 2.2.4 coming out soon

**Comment by mme000** [comment] 2019-11-05 12:09
It also happens with a fresh installation of iPadOS 13.2 installed on ad iPad (6th generation).
Here is a screenshot of what happens when I try to enable BitWarden inside Settings -> Password & Accounts -> AutoFill Passwords https://pasteboard.co/IFh77Wf.png
Here is a screenshot of what happens when I try to use it inside an app (Just Eat, in this case) https://pasteboard.co/IFh9oIF.png
Please, tell me if you need more infos.

**Comment by mme000** [comment] 2019-11-13 14:30
> It also happens with a fresh installation of iPadOS 13.2 installed on an iPad (6th generation).
> Here is a screenshot of what happens when I try to enable BitWarden inside Settings -> Password & Accounts -> AutoFill Passwords https://pasteboard.co/IFh77Wf.png
> Here is a screenshot of what happens when I try to use it inside an app (Just Eat, in this case) https://pasteboard.co/IFh9oIF.png
> Please, tell me if you need more info.

iPad updated today to iPadOS 13.2.2.
BitWarden still doesn't work.

**Comment by khalo-sa** [comment] 2019-12-24 15:54
Same issue that @mme000 reports on iPad with iPadOS 13.2.3. Any updates on this?

**Comment by devurandom** [comment] 2020-01-03 21:32
I also ran into the issue at about 19:20 UTC today.

**Comment by ppsirius** [comment] 2020-02-16 19:12
iPhone 7 iOS 13.3.1 still freeze

**Comment by sandangel** [comment] 2020-02-25 11:21
I have the same issue for ipados latest on ipad mini 4

**Comment by GirzzlyAK** [comment] 2020-03-03 02:25
Same, iOS 13.2, iPhone 7. Just created my account, set up BW on desktop, downloaded app to iPhone, went through setup, activated extensions, tried to use it Pinterest APP with no options, then went to Settings to set BW as default autofill, and it froze. Also went back to BW app, which was asking me to log in, but which was ALSO frozen. So, pretty much useless so far on iOS?

Firefox on Windows 10 seems to be working ok, as did initial sync to the iPhone. Seems this has been a problem for a while. Anybody working on it actively?

**Comment by Elehiggle** [comment] 2020-03-06 17:26
Still happening here.

**Comment by mportune-bw** [comment] 2020-06-07 04:08
Fixed in #960

**Closed** 2020-06-07 04:16 UTC
