### ISSUE TITLE
Horizontal 3 dots button not working in Search

### ISSUE THREAD

**Issue by jmejco** [bitwarden/mobile#2481] opened 2023-04-17 11:38 UTC
### Steps To Reproduce

1. Go to Search Vault
2. Type in anything to show some Login items
3. Click on the '...' button to the right of any item

### Expected Result

Clicking on the '...' button should display options including copy username and password.

### Actual Result

Nothing happens.

### Additional Context

The '...' button seems to work fine when going to the Logins and listing all items. It is broken only when searching for items.

### Operating System

Android, iOS

### Operating System Version

Android 13, iOS 16.4.1

### Device

Google Pixel 7 Pro, iPhone 13  Mini

### Build Version

Android: 2023.3.2(6098), iOS: 2023.3.2(3195)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment] 2023-04-17 11:44
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by djsmith85** [comment] 2023-04-17 18:31
Closing this as duplicate of your other report #2480, which has also been answered.

**Closed by djsmith85** 2023-04-17 18:31 UTC
Labels: bug
