### ISSUE TITLE
Bitwarden autofill stop working since Chrome, Brave... (chromium 79.0.?)

### ISSUE THREAD

**Issue by jwall149** [bitwarden/mobile#715] opened 2020-02-04 06:12 UTC
Tested on 79.0.3945.136, Android 9; Lenovo

Bitwarden autofill uses Android autofill framework, and requires switching back and forward from Bitwarden and Chrome.

Unfortunately now chrome tab get reload EVERYTIME we switch from application to other, and make autofill  stop working.

I tried to find an option or a flag to stop Chrome doing the refresh on android but not yet found.

**Comment by kspearrin** [comment] 2020-02-04 14:37
This sounds like a Chrome issue rather than a problem with Bitwarden?

**Comment by jwall149** [comment] 2020-02-04 18:31
@kspearrin, not a Chrome issue, instead, Chrome "feature"...

**Comment by nopynoop** [comment] 2020-02-08 09:40
For me Bitwarden auto-fill on Android is inconsistent.

Overlay keeps appearing and disappearing randomly.

See the video:
![C4fixers66](https://user-images.githubusercontent.com/25570106/74082991-6aa88900-4a5f-11ea-902b-e4eacb13ed2e.gif)

**Comment by superm1** [comment] 2020-02-18 14:02
> For me Bitwarden auto-fill on Android is inconsistent.
> 
> Overlay keeps appearing and disappearing randomly.
> 
> See the video:
> ![C4fixers66](https://user-images.githubusercontent.com/25570106/74082991-6aa88900-4a5f-11ea-902b-e4eacb13ed2e.gif)

I don't believe this is a Bitwarden bug, but rather a browser or Android bug.  I've had the same behavior with Lastpass +Chrome for ages.  Typically force closing the browser and opening it again gets it working for me again.
It's been reported here:
https://bugs.chromium.org/p/chromium/issues/detail?id=1015381

**Comment by mportune-bw** [comment] 2020-04-06 16:01
Duplicate of #784

**Closed by mportune-bw** 2020-04-06 16:01 UTC
