### ISSUE TITLE
Vault timeout "Never" option from drop down menu dosen't work. Forces me to re-enter the master password everytime I need to acces My Vault or login into an application or website.

### ISSUE THREAD

**Issue by alexandrubaciu9** [bitwarden/mobile#2857] opened 2023-11-04 15:05 UTC
### Steps To Reproduce

1. Go to 'Settings'
2. Click on 'Vault timeout'
3. Scroll down to 'Never'
4. Click on 'Never'

### Expected Result

After setting Vault timeout to "Never" in that way, I should never ever be prompted to type again the master password to unlock my vault.

### Actual Result

After 2-3 minutes, although I set it up correctly, "Never" option dosen't seem to work. It's prompts me to the screen. "Verify master password" forcing me to enter once again master password.

### Screenshots or Videos

I can't screenshot it, screen goes full black after taking the shot.

### Additional Context

Android 13 

### Operating System

Android

### Operating System Version

Android 13

### Device

Xiaomi Redmi Note

### Build Version

Version: 2023.9.2 (8002)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment] 2023-11-04 20:49
Hi @alexandrubaciu9,

Thank you for your report. It seems that this report is a duplicate of this one (#2787); This matter has been addressed in version 2023.10.0.

This issue here will now be closed.

Thank you again,

**Closed by SergeantConfused** 2023-11-04 20:49 UTC
Labels: bug

**Comment by alexandrubaciu9** [comment] 2023-11-11 20:30
Thank you so much! @SergeantConfused, it worked perfectly after update!
