### ISSUE TITLE
iOS - BitWarden blocking iPhone from performing iCloud backup due to excess backup storage allocation

### ISSUE THREAD

**Issue by hannad4** [bitwarden/mobile#1251] opened 2021-02-06 16:50 UTC
## Describe the Bug
When attempting to initiate an iCloud backup on iOS, the estimated storage size that bitwarden will take up is 14TB, which results in every backup attempt to fail because of insufficient iCloud storage.  

## Steps To Reproduce

1. Go to Settings > [your name] > iCloud > Manage Storage > Backups
2. View details of backup

## Expected Result
The iCloud backup size allotted for bitwarden should be a reasonable size (under 1GB at least)

## Actual Result
The iCloud backup size allotted for bitwarden is 14TB. 

## Screenshots or Videos
This bug report is being submitted on behalf of a friend, so I am unable to attach screenshots or build version information

## Environment

- Device: iPhone 6S
- Operating system: iOS14.4
- Build Version (go to "Settings" → "About" in the app): This bug report is being submitted on behalf of a friend, so I am unable to attach screenshots or build version information
- Is this a Beta release? [NO]

## Additional Context
This bug report is being submitted on behalf of a friend, so I am unable to attach screenshots or build version information

**Comment by SergeantConfused** [comment] 2021-02-07 16:44
Hi there,

I'm unable to reproduce this on my iPhone SE 2020 running iOS 14.4. Can you please ask your friend to uninstall their Bitwarden client, reboot their device by turning it off (long press) and back on, reinstall Bitwarden on their phone, and test that again?
It's also important to note that iCloud saves the state of the Bitwarden application on your phone, not necessarily the data that's inside your Bitwarden vault. So, they can skip backing it up and reinstall Bitwarden and log into their vault instead.


Thank you in advance,

**Comment by djsmith85** [comment] 2022-03-02 11:14
Hi @hannad4, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2022-03-02 11:14 UTC
