### ISSUE TITLE
Password Character ">" Not Displayed in Password Preview

### ISSUE THREAD

**Issue by ali2key** [bitwarden/mobile#3373] opened 2024-08-05 11:04 UTC
### Production Build

- [ ] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Open the Bitwarden mobile app.
2. Navigate to a saved password entry.
3. Edit the entry and set the password to include the character ">".
4. Save the changes.
5. View the password entry.

### Expected Result

The password preview should display all characters of the password, including ">".

### Actual Result

The character ">" is missing from the password preview.

### Screenshots or Videos

![photo_5872942554499106725_y](https://github.com/user-attachments/assets/f4ded206-5da4-49cf-aa53-3fcb7e763c33)
![photo_5872942554499106726_y](https://github.com/user-attachments/assets/0bec5933-9368-4a84-8b9d-c40e55cf402a)

### Additional Context

Screenshots:

1. Edit Item View: Shows the password as "QWERTY123!<".
2. View Item View: Displays the password as "QWERTY123!" (missing ">").

Additional Information:

The issue occurs consistently regardless of the password's complexity or length.
Other special characters are displayed correctly.

Impact:
Medium - This bug affects the accuracy of password previews, which could lead to confusion and potential login issues for users relying on the displayed password.

### Operating System

Android

### Operating System Version

Android 12

### Device

OnePlus Nord 2 5G (DN2103)

### Build Version

2024.7.1 (11086)

**Comment by SergeantConfused** [comment] 2024-08-05 16:09
Hello @ali2key,

Thank you for your report. This report seems to be a duplicate of [this GitHub report](https://github.com/bitwarden/mobile/issues/3110); If there's anything you'd like to add, such as screenshots or video recordings of the screen, please feel free to add them to that existing GitHub report so that they'd be reviewed by the Bitwarden Engineering department.

This report will now be closed as a duplicate.

Thank you again,

**Closed by SergeantConfused** 2024-08-05 16:09 UTC
Labels: bug
