### ISSUE TITLE
App crash during password generation

### ISSUE THREAD

**Issue by Frivolous2** [bitwarden/mobile#2225] opened 2022-12-06 00:27 UTC
### Steps To Reproduce

1. Go to a password field in a web browser
2. Click on "Vault is locked" on your keyboard
3. Add new account
4. Press the generate password button

### Expected Result

The Generate Password sheet popping up

### Actual Result

App crashing

### Screenshots or Videos

https://user-images.githubusercontent.com/57101103/205775685-06dbef78-b5e6-4772-8508-2ef0039efbf1.mp4

### Additional Context

This crash doesn't happen when adding a new account via the app, just when launched through the keyboard button

### Operating System

Android

### Operating System Version

12; 13

### Device

Samsung Galaxy A52s

### Build Version

Version: 2022.10.0 (5247)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment] 2022-12-06 00:48
Hi @Frivolous2 and thank you for your report.

This seems to be a duplicate of https://github.com/bitwarden/mobile/issues/2149, which has already received a fix.

This should be resolved with [2022.11](https://github.com/bitwarden/mobile/releases/tag/v2022.11.0), which has been released. The rollout to your device might still take some time because of the store-review process.

I'm closing this now. If this is still an issue with 2022.11, then please report back and I'll happily re-open.

**Closed by djsmith85** 2022-12-06 00:48 UTC
Labels: bug
