### ISSUE TITLE
iOS app de

### ISSUE THREAD

**Issue by thedannymullen** [bitwarden/mobile#862] opened 2020-04-29 23:48 UTC
## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. iOS 8.1]
- Build Version (go to "Settings" → "About" in the app): [e.g. 2.3.0 (2221)]
- Is this a Beta release? [Y/N]

**Comment by thedannymullen** [comment] 2020-04-29 23:52
I add passwords on my laptop to my vault.  
On both ios12 and ios13 iPhone when I unlock my vault the new passwords are not there.  It forces me to logout and back in.  
I saw something similar in number 393 but that was related to browser linkage on the phone.  
If this is expected behavior please let me know.  

Love to have a clear cache button in the app as a possible solution if this can’t be auto mated.  
Thanks!!  Love the program it’s is working great!!

**Comment by kspearrin** [comment] 2020-04-30 02:54
Seems to be a duplicate of https://github.com/bitwarden/mobile/issues/782 https://github.com/bitwarden/mobile/issues/723

**Closed by kspearrin** 2020-04-30 02:54 UTC

**Comment by thedannymullen** [comment] 2020-04-30 15:34
Thanks will follow these issues!
