### ISSUE TITLE
Android doesn't show '<' characters in passwords (Show entry screen, with PW revealed)

### ISSUE THREAD

**Issue by valentinilk** [bitwarden/mobile#3258] opened 2024-05-24 05:13 UTC
### Steps To Reproduce

1. Open Bitwarden on an Android device
2. Create & save an entry with the following password: a<bc
3. Open the entry and reveal the password with the little eye icon

### Expected Result

The app will show the following password:
$$a{\color{red}bc}$$

### Actual Result

The actual password is expected (correctly shown in the edit mode):
$$a{\color{red}<}bc$$

### Additional Context

If you go into the edit mode, the correct a<bc password is shown again.

### Operating System

Android

### Build Version

2024.5.1 (10574)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by NovaSilentium** [comment] 2024-05-24 10:04
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by djsmith85** [comment] 2024-05-24 11:51
Duplicate of https://github.com/bitwarden/mobile/issues/3110

**Comment by djsmith85** [comment] 2024-05-24 11:51
Hi @valentinilk!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/mobile/issues/3110

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-05-24 11:51 UTC
Labels: bug
