### ISSUE TITLE
iOS: No keyboard appears to search for login

### ISSUE THREAD

**Issue by raelli** [bitwarden/mobile#1194] opened 2020-12-26 10:27 UTC
## Describe the Bug

No keyboard pops up for searching the vault.

## Steps To Reproduce

1. Open app or webpage which is not available in the vault
2. Select password field
3. Click on 'Password' above keyboard
4. Bitwardens shows vault to search
5. Tap in search field, but no keybord pops up

## Expected Result

If tapping in the search field, the keyboard shall pop up. Otherwise no search is possible.

## Actual Result

No keyboard available.

## Environment

- Device: iPhone 12
- Operating system: iOS 14.3
- Build Version 2.7.2 (401)
- Is this a Beta release? No

**Comment by SergeantConfused** [comment] 2020-12-26 13:11
Hi there,

I'm unable to reproduce this. First, please uninstall Bitwarden, reboot your device by turning it off (long press) and back on, and reinstall Bitwarden.
Please let me know if that issue persists, and we'll proceed.

Thank you in advance for your cooperation.

All the best,

**Comment by raelli** [comment] 2020-12-26 13:55
I just did a reboot of my device. The problem still occur.

See behavior in the attached video.

Just clicking on passwords, then bitwarden opens. The chrsor is set in the search field, but no keyboard pops up to type...

https://user-images.githubusercontent.com/47218792/103152641-4befd580-478a-11eb-8dd7-e2710a0e79a1.MP4

Thanks for checking!

**Comment by raelli** [comment] 2020-12-26 19:36
Second time uninstall and reinstall fixed the problem...

**Comment by raelli** [comment] 2020-12-26 22:54
Issue is back again... Reinstall seems to fix the issue only temporarly.
If selecting iCloud Key Chain for auto fill, then keyboard pops up. But not with bitwarden.
Looks like a problem in bitwarden.

**Comment by raelli** [comment] 2020-12-26 22:57
Issue is also reported by another user here:
https://community.bitwarden.com/t/autofill-problem-on-ios-keyboard-doesnt-show-up/16093

**Comment by igotyoubaby** [comment] 2020-12-28 02:19
Experienced similar problem,based on iOS 14.3, Bitwarden APP Version2.7.2(401)
No keyboard appears to unlock the Bitwarden app with password when FaceID unlock failed（Try to use autofill in other APP）

**Comment by lilchancep** [comment] 2020-12-30 17:01
I can reproduce this, the key is hitting the password auto fill for a website or app you do not have a password set for. This bug has been making Bitwarden absolutely miserable to use.

**Comment by SergeantConfused** [comment] 2021-01-05 15:51
Thank you all very much for bringing this to our attention. I will be marking this as a duplicate to consolidate this matter into a single issue, and we would be looking into this issue soon.

**Comment by SergeantConfused** [comment] 2021-01-05 15:51
Duplicate of #1114

**Closed** 2021-01-05 15:59 UTC
Labels: duplicate
