### ISSUE TITLE
App doesn't work on Android 4.4.4

### ISSUE THREAD

**Issue by rajib-raiyat** [bitwarden/mobile#722] opened 2020-02-09 18:17 UTC
#722 Bitwarden app doesn't work on 4.4.4 Android. This app works well before. But it doesn't work anymore. The 'bitwarden stoped' message shows up every time I launch the app. The app has been fixing this problem since the new update.

**Comment by reruem** [comment] 2020-04-14 11:16
I created this issue a week ago and they closed it and said it already exists yet I can not find it. I only find yours.

I haven't been able to use Bitwarden on my pixel 2xl for over a month. First it crashed every time I opened it, then I uninstalled and reinstalled and the app immediately crashes when I hit login button. 

This is infuriating, do you know how much I realy on this software and devs just close my case without any discourse or care

**Comment by tgreer-bw** [comment] 2020-04-14 13:05
@reruem  The issue is with the beta - here is the "official" issue: https://github.com/bitwarden/mobile/issues/805 - there is a link to a fixed APK, we are waiting on the new beta to hit the play store.

**Closed** 2020-10-19 14:52 UTC
