### ISSUE TITLE
iOS Autocomplete filles old/wrong password

### ISSUE THREAD

**Issue by NPadrutt** [bitwarden/mobile#980] opened 2020-06-15 07:08 UTC
## Describe the Bug
I adjusted my Hotmail Password. The password got synced to my iPhone and iPad correctly, but when I autocomplete the password in any password field it fills the wrong one. When I copy and paste it manually it works.

## Steps To Reproduce

This was how I did it. Not sure how consistent reproduceable that is
1. Change Hotmail password
2. Start bitwarden and ensure that it is synced
3. Open app who uses Hotmail login and autofill password
4. Notice that password was incorrect (in my case I could see it by that it was much shorter - or the "login failed message)
5. Open bitwarden and copy the password
6. switch back to the application and paste password
7. Login successful

## Expected Result

The correct password is filled with Autofill Password

## Actual Result
It seems the old password is used in Autofill.

## Environment

iPhone 11 Pro (iOS 13.5.1)
iPad Pro 2020 (iOS 13.5.1)
- Operating system: [e.g. iOS 8.1]
- Build Version (go to "Settings" → "About" in the app): [e.g. 2.3.0 (2221)]: 2.4.3(69)
- Is this a Beta release? [Y/N] N

**Comment by DingXiangYuanZhiXing** [comment] 2020-06-17 11:10
Exact same issue. This issue happened after the latest update on iOS.
## Environment
 * Device: [e.g. iPhone6]
    iPhone 7 plus 
 * Operating system: iOS 12.0.0
 * Build Version (go to "Settings" → "About" in the app): 2.4.3(69)
 * Is this a Beta release? [Y/N] N

**Comment by clayadams5226** [comment] 2020-06-25 06:34
@NPadrutt can you verify a couple of things for me:

1. Can you verify keychain autofill is deactivated and Bitwarden is the only application with autofill permission?

2. After you change your Hotmail password, are you first logging back into the Bitwarden application or going straight to the app extension/autofill service?

**Comment by NPadrutt** [comment] 2020-06-25 14:56
@clayadams5226 

1. that is the case
2. I did first go to the app I wanted to login in the hope / anticipation that bitwarden will sync when it opens the list with the suggestions. After that wasn't the case I went to the bitwarden app and synced manually and checked that it was correct now. Then I went back to the app and tried a gain - which failed still. I also tried to cancel the authentication or restart the app in case anything was cached but both didn't work. Funny enough, as far as I can remember I tried even to restart my iPhone and it still did autofill it incorrect. Same on my iPad for that sake.

**Comment by brenr** [comment] 2020-06-29 21:11
Yep same sort of situation here. Autofill is showing old passwords despite me deleting them and syncing vault several times.

**Comment by HelmyBD2** [comment] 2020-07-04 15:27
Same here! iPhone 7 with latest iOS and app version.

**Comment by clayadams5226** [comment] 2020-07-07 06:24
As a work around, I've found that uninstalling the app and installing it again seems to resolve this issue.

**Comment by HelmyBD2** [comment] 2020-07-07 09:36
I tried that but problem persist

Sent from my iPhone

On 7 Jul 2020, at 10:24, Clayton <notifications@github.com> wrote:

﻿

As a work around, I've found that uninstalling the app and installing it again seems to resolve this issue.

**Comment by AyaChanGX** [comment] 2020-07-09 10:38
I have the same problem on my iPhone XR  / iOS 13.5.1

Only way to make the new synced passwords show up is restart my phone.

**Comment by FL0nG** [comment] 2020-07-10 11:40
I have the same problem on my iPhone 8 / iOS 13.5.1

**Comment by stub68** [comment] 2020-07-12 23:57
Yes I have had the same issue on iPhone7 and latest iOS. I created an account and accepted the strong master password but when I try to log in using the password saved in iOS I receive a wrong password error from Bitwarden.  I emailed support and have tried deleting the app and re-installing, but the problem persists. I understand the issue is being looked into.

**Comment by MattTheDev** [comment] 2020-07-13 21:07
@NPadrutt Hi there, Nino! 

I'm working on fixing this issue for you. It's an odd one - I can get it to repro in some cases .. and not in others. A lot of the time, the resolution thats worked for me is:

1. Close all browser instances
2. Launch BW
3. Sync
4. Launch browser and restart the authentication process.

I thought I had a resolution - as seen above. But it wasn't the desired solution. I will keep you in the loop on this one. Let me know if the issue still persists as well. Thanks!

**Comment by chainsawng** [comment] 2020-07-15 18:12
Similar issue.
iOS 13.5.1 iPhone 8 Plus. Auto-fill password is Bitwarden only, but iCloud Keychain, KeePass Touch and Lass pass are installed.

Created new login entry on PC Firefox extension. Sync'd on PC. Sync'd on iPhone. Can search & find the entry in app, but not with keyboard auto-fill. Searching in the autofill can't locate the new entry by name.

Removed Keepass and Lasspass, rebooted phone. Now that entry is found.

**Comment by IhanaOlli** [comment] 2020-07-17 14:49
Same issue here. iOS 13.6, iPhone 11 Pro Max, BW 2.5.0 (193). 
I uninstalled & reinstalled BW and autofill still remembers incorrect data from earlier, before reinstallation! 

I normally use Firefox on iOS and autofill using that shows old data. However, if I access same site with Safari and tap the 🔑 button on autofill bar and then "Bitwarden..." autofill data gets updated! So there is some kind of caching, maybe by iOS? 
Tried with other password manager and it works correctly so this does not look like iOS bug.

**Comment by NPadrutt** [comment] 2020-07-20 18:17
@MattTheDev just to give you an update: I just had the same issue with a new entry for twitch. I created the entry on my laptop, closed the twitch on my iPad, synced in bitwarden, switched back to the twitch app and tried to autofill but couldn't find the entry although it was already available in the app.

**Comment by charles-curran** [comment] 2020-07-20 22:54
I also ran into this issue and I may have found the problem. 

Like everyone else I've been running into the issue of the auto-fill function of Bitwarden not working on both my iPhone (11 Pro Max @ iOS 13.6 (17G68)) and my iPad (6th Generation @ iOS 13.6 (17G68)). 

As suggested here I tried to save a new entry directly into the Bitwarden app and was not able to get it to auto-fill in Firefox (Version 27.0 (18428)), the newly added entry would not populate and searching for it did not work either. I tried closing out both Bitwarden and Firefox and trying again, that did not work. However restarting my phone did work.

With that I did a test. I replicated the issue above by adding a new entry and confirming that it was showing the cached data. I then went to Settings -> Safari -> Clear History and Website Data and this cleared the cache! 

I've now tested this on a half dozen different entries to confirm, but clearing the Safari cache works every time, at least for me, that auto-fill starts showing cached data.

Hopefully this helps! I absolutely love this tool and appreciate all the work that goes into making it as great as it is!

**Comment by NPadrutt** [comment] 2020-07-21 06:01
I can confirm that the work around of @charles-curran worked for me as well.

**Comment by btr3** [comment] 2020-07-23 15:43
I'm having this same issue. Haven't seen anyone mention Android, but I'm running Android 10 on an S10e.

Add an entry via another source and autofill on the app won't have the login information. I have to open the app, sync, and then go back to the login prompt where the auto fill option will be updated.

**Comment by stub68** [comment] 2020-07-23 23:50
In the end I deleted the accounts and started again with an externally generated strong password which I then copied to the iOS autofill. Not ideal obviously, but ok for me because the accounts were new and empty anyway.

**Comment by 104manage** [comment] 2020-08-17 21:48
I read another user emptied the trash and this solved the issue.  I tested the approach and after syncing my ios device found the PW stack no longer contained the prior passwords.  

Reference:

https://community.bitwarden.com/t/still-using-old-password-on-ios-safari/13226/8

**Comment by jebeaudet** [comment] 2020-09-06 04:18
Any updates on this one @MattTheDev ? It's really annoying! Thanks

**Comment by jebeaudet** [comment] 2020-09-06 17:37
The affected iPhone was in french and since changing it to english, I no longer get the problem. Could localization be an issue here? 

Are people on iOS affected here in a different language as well?

**Comment by ma-neu** [comment] 2020-09-06 19:12
My affected iPhone is in german.

**Comment by jebeaudet** [comment] 2020-09-06 19:29
Try switching temporaly to English to see if it resolves the issue you have!

**Comment by nokoa77** [comment] 2020-09-07 20:15
Strange, I have the problem also, and my iPhone is on French

**Comment by ewjoachim** [comment] 2020-09-13 12:00
I can’t be sure but what I understand (I’m affected by this bug too) is that there’s the bitwarden process launched by the app, and iOS maintains a separate process for the autofill features. When we change anything in the first process, the second process is not aware. The only workarounds (except not using the Autofill at all) would be whatever method that forces iOS to restart the bw autofill process (I believe it sync on startup), so changing the language (which restarts every app) is a solution, so is restarting the phone or uninstalling the app.
If there’s no simple way to control when iOS restarts the autofill process, I guess the only thing bw can do is refresh more often, or refresh on autofill.

**Comment by jebeaudet** [comment] 2020-09-13 12:25
For me, it's not a matter of restarting apps/phone, since switching to english I don't have the problem anymore. The 2 commenters below me also have an iPhone with a different than english language though sadly they didn't try to change it it seems, so I'd be interested to see others trying it out.

**Comment by prudka** [comment] 2020-09-13 13:06
I also have this issue on my iPhone's (iOS 13 and iOS 14 Beta 8). Going into Settings.app > Safari > Clear History and Website Data resolves it for me.

**Comment by Tataru-Taru** [comment] 2020-10-07 14:42
> I also have this issue on my iPhone's (iOS 13 and iOS 14 Beta 8). Going into Settings.app > Safari > Clear History and Website Data resolves it for me.
> 
> Note: This seems to affect auto-filling into all apps, not just Safari.

I can confirm this worked for me. Does this mean that Safari is actually caching the data and that's being fed to the autofill?

Doesn't that also mean that the data is exposed outside of Bitwarden and stored in Safari Data Cache?

**Closed** 2020-10-13 19:39 UTC
