### ISSUE TITLE
No Icons on Android App

### ISSUE THREAD

**Issue by mohammad-o** [bitwarden/mobile#1665] opened 2021-11-29 07:07 UTC
### Steps To Reproduce

1. Go to Vault.
2. Scroll down to Logins or Credentials.

### Expected Result

You should see each login's "Icon".

### Actual Result

Instead, nothing appears beside login's entry, just a blank space

### Operating System

Android

### Operating System Version

9.0

### Device

Samsung Galaxy S8

### Build Version

2.14.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Amenixx** [comment] 2021-11-30 02:40
Already solved https://github.com/bitwarden/mobile/issues/1640

**Comment by eliykat** [comment] 2021-12-03 04:27
Closing as a duplicate of #1640. Please check that Issue for more information. Thank you!

**Closed by eliykat** 2021-12-03 04:27 UTC
Labels: bug
