### ISSUE TITLE
Bitwarden cannot be used for passkey authentication on mobile

### ISSUE THREAD

**Issue by platnub** [bitwarden/mobile#3237] opened 2024-05-13 12:25 UTC
### Steps To Reproduce

1. Go to any website and authenticate via passkey
2. Bitwarden will not show up to authenticate passkey. Both the mobile app and browser extension don't work on mobile

### Expected Result

Bitwarden opens to authenticate passkey

### Actual Result

Either the local phone passkey authentication system open, or it straight up fails the passkey authentication immediatley

### Additional Context

I am using Firefox 125.3.0 and I have tried the Bitwarden mobile app and the extension that runs in Firefox

### Operating System

Android

### Operating System Version

13

### Device

OnePlus 9 Pro

### Build Version

2024.4.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Neonwarden** [comment] 2024-05-13 13:30
Hi there,

I am unable to reproduce this issue, but it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by platnub** [comment] 2024-05-13 13:43
> Hi there,
> 
> I am unable to reproduce this issue, but it has been escalated for further investigation. If you have more information that can help us, please add it below.
> 
> Thanks!

Hey,

As I understand the passkey authentication works for you on mobile? Do you use the app or the browser extension?
For me it always calls the passkey authentication system from the phone itself. Bitwarden has never shown up for me for this. Password autofill does work however.

I looked around and I can't see any setting for this either, so I assumed it either wasn't supported or is always enabled (and not working in my case).

**Comment by Nathanymous** [comment] 2024-05-13 20:40
I can confirm this issue.
Running the bitwarden app, and the extension in Firefox version 125.3.0.
My mobile has the same problem, it goes to the locsl phone passkey authentication system.
Phone: Samsung S23, running latest android version

**Comment by pamperer562580892423** [comment] 2024-05-13 23:10
@platnub You use Android 13 for this? That doesn't support third-party passkey management, like with Bitwarden, so it can't work for you as long as you are not on Android 14 (or higher).

And you use the mobile app 2024.4.0 which is even not providing passkey functions. (as I understand it, for Android passkey functions are still in Beta)

And using the browser extension on mobile is even not supported by Bitwarden.

**Comment by artur-braga** [comment] 2024-05-14 11:09
In chrome one need to enable the third-party password managers for passkeys as an experimental feature. No idea about other browser. As far as I know, on android, only browser authentication with passkeys works(will not work for apps).

**Comment by pamperer562580892423** [comment] 2024-05-14 11:19
> In chrome one need to enable the third-party password managers for passkeys as an experimental feature. No idea about other browser. As far as I know, on android, only browser authentication with passkeys works(will not work for apps).

@artur-braga I think it is the same for other Chromium-based browsers (and Firefox doesn't work). And app support will come with future releases... This all can be read in more detail in the help sites (especially in the tab "Android (beta)"): https://bitwarden.com/help/storing-passkeys/#using-passkeys-with-bitwarden

**Comment by pamperer562580892423** [comment] 2024-05-14 11:23
> I can confirm this issue. Running the bitwarden app, and the extension in Firefox version 125.3.0. My mobile has the same problem, it goes to the locsl phone passkey authentication system. Phone: Samsung S23, running latest android version

@Nathanymous As I now already wrote: it won't work with Firefox (for now - and that's a Firefox issue) - you have to use a Chromium-based browser for the time being. When your "latest Android" is Android 14, then you're good. When you have installed the Bitwarden mobile app BETA (2024.4.1 or above), then you're good. It won't work with the latest release (2024.4.0).

And then you have to do some manually configurations so that it can work - see here (especially in the tab "Android (beta)": https://bitwarden.com/help/storing-passkeys/#using-passkeys-with-bitwarden

**Comment by platnub** [comment] 2024-05-15 06:49
I will upgrade to Android 14 this weekend and test out the beta function. Will report back.

**Comment by micahblut** [comment] 2024-05-16 13:49
Thank you for checking out the Android beta. As others have pointed out, Android 14 or above is required to use a 3rd party passkey provider like Bitwarden. Additionally, there are known issues with Firefox not supporting passkeys on Android. I will close this issue now.

**Closed by micahblut** 2024-05-16 13:49 UTC
Labels: bug

**Comment by ronidee** [comment] 2024-05-29 22:13
I'm using Android 14, Bitwarden 2024.4.1 and Chrome. I have the same experience as described by OP.

I'm using lineage is 21 with microG 0.3.2.

**Comment by micahblut** [comment] 2024-05-30 07:29
@ronidee can you confirm that you've configured your chrome://flags to enable 3rd party passkey providers?

**Comment by ronidee** [comment] 2024-05-31 21:11
Sorry, I forgot to do so. After enabling it, I am prompted to unlock Bitwarden. After doing so, this full screen pop up appears, where I can "get started" and then select device authentication -- see screenshots. After doing so, there is a sort of toast message (not a native android toast though. No, neither a snackbar) saying "no sign-inf info in Bitwarden".
However, my Bitwarden account has a passkey for this website which I can use on other devices, e.g. firefox (deb) on Ubuntu 23.10. But Firefox on Windows 11 and on Ubuntu 24 says "There are no passkeys for this application", so yeah it only works on some of my other devices.

Screenshots:
![image](https://github.com/bitwarden/mobile/assets/22625272/40934fa7-12fa-4736-958a-708cc874eb65)
![image](https://github.com/bitwarden/mobile/assets/22625272/ce3da98a-c4be-4fe5-aa34-109c79fe3011)

**Comment by somova** [comment] 2024-06-15 13:28
Opened new issue #3299
