### ISSUE TITLE
Search results options not working

### ISSUE THREAD

**Issue by Controllr1** [bitwarden/mobile#2468] opened 2023-04-10 13:57 UTC
### Steps To Reproduce

1. Go to Search
2. Enter valid search term(s)
3. Click on '...' on any returned search record

### Expected Result

Used to display option to copy username, password, etc., when clicking on '...'.

### Actual Result

Nothing happens on click.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/50551266/230915293-859c347c-b4d3-4996-8aad-62a73ffe5f4a.png)

### Operating System

iOS

### Operating System Version

16.3.1

### Device

iPhone 14 Pro Max, iPad Mini (latest)

### Build Version

2023.3.2 (3195)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Racle** [comment] 2023-04-11 10:54
Same issue here. And long press doesn't work either.

**Device**
Samsung Fold3

**Build Version**
2023.3.2 (6098)

**Comment by djsmith85** [comment] 2023-04-11 11:13
Hi @Controllr1 and @Racle ,

Thank you for your report, it seems like it is a duplicate of this (https://github.com/bitwarden/mobile/issues/2446).

This issue will now be closed.

Thank you.

**Closed by djsmith85** 2023-04-11 11:13 UTC
Labels: bug
