### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by catfluoride** [bitwarden/mobile#2216] opened 2022-12-02 09:03 UTC
### Steps To Reproduce

Try to install/update Bitwarden latest version (2022.10.1) from F-Droid.

Install fails with a notification about the integrity of the app, which can't be checked see the attached screenshot).

This happens with different F-Droid clients and also after uninstalling the old version.

Installing through Aurora Store work fine.

### Expected Result

App install/update without issue.

### Actual Result

App can't be installed/updated

### Screenshots or Videos

![photo_2022-12-02_09-51-26](https://user-images.githubusercontent.com/25054477/205253731-535e982c-a283-4d2a-9c02-6f213e4fdecb.jpg)

### Operating System

Android

### Operating System Version

LineageOS 19.1

### Device

Poco X3 NFC

### Build Version

2022.10.1

### Beta

- [ ] Using a pre-release version of the application.
-

**Comment by catfluoride** [comment] 2022-12-02 11:30
Sorry, the title is incomplete. It had to be "can't install from F-Droid repository".

**Comment by djsmith85** [comment] 2022-12-04 15:53
Duplicate of https://github.com/bitwarden/mobile/issues/2187

@catfluoride: This issue seems to have been previously reported.

Closing this now.

**Closed by djsmith85** 2022-12-04 15:53 UTC
Labels: bug
