### ISSUE TITLE
Unable to click on three horizontal dots in search results

### ISSUE THREAD

**Issue by dongeerts** [bitwarden/mobile#2475] opened 2023-04-14 09:44 UTC
### Steps To Reproduce

1. Open Bitwarden
2. Click on search icon
3. Enter query
4. Click on the three horizontal dots (action menu button)

### Expected Result

Upon clicking on the three horizontal dots of a search result, the menu of available actions is triggered and displayed.

### Actual Result

Upon clicking on the three horizontal dots of a search result, nothing happens.

### Additional Context

This issue seems to be specific to the search function.

### Operating System

Android

### Operating System Version

2032.3.2

### Device

Google Pixel 6A

### Build Version

TQ2A.230305.008.E1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment] 2023-04-14 09:55
Hi @dongeerts,

Thank you for your report, it seems like it is a duplicate of this (https://github.com/bitwarden/mobile/issues/2446).

This issue will now be closed.

**Closed by djsmith85** 2023-04-14 09:55 UTC
Labels: bug
