### ISSUE TITLE
Unable to switch between multiple Bitwarden accounts

### ISSUE THREAD

**Issue by velanmech** [bitwarden/mobile#3389] opened 2024-09-17 16:27 UTC
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Go to 'my vault'
2. Click on 'profile picture'

### Expected Result

A drop down list of the accounts added which I am able to choose from.

### Actual Result

“My vault” and search bar overlap the drop down list of accounts.

### Screenshots or Videos

![IMG_0317](https://github.com/user-attachments/assets/69dc357c-d0ee-466b-9004-d595f7db0008)

### Operating System

iOS

### Operating System Version

18.0

### Device

iPhone 12 Mini

### Build Version

2024.8.1 (1025)

**Comment by cbbit** [comment] 2024-09-17 16:48
Hi there!

Thank you for your report, it seems like it is a duplicate of an issue that was reported internally. Furthermore, the engineering team is aware of this issue, and a fix is being addressed here: https://github.com/bitwarden/ios/pull/926

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by cbbit** 2024-09-17 16:48 UTC
Labels: bug
