### ISSUE TITLE
iOS Keyboard not presented on first attempt when searching in Mobile Safari

### ISSUE THREAD

**Issue by ToGitOrNotToGit** [bitwarden/mobile#1483] opened 2021-08-01 17:42 UTC
iOS Keyboard not presented on first attempt when searching Bitwarden popup in Mobile Safari

## Describe the Bug

iOS Keyboard not presented on first attempt when searching Bitwarden popup in Mobile Safari

## Steps To Reproduce

1. Go to Google.com for example. 
2. Click on sign in
3. Scroll down to enter password field
4. Click on Key icon in upper right above iOS keyboard.
5. Tap on 'Bitwarden...'
6. Tap on search (magnifying glass icon) in upper right.
7. Tap into 'Search' field.

## Expected Result

Ability to type search term with iOS keyboard

## Actual Result

User is not presented a keyboard. No ability to type search terms as there's no keyboard to type with.
## Screenshots or Videos

<img width="430" alt="Screen Shot 2021-08-01 at 10 41 06 AM" src="https://user-images.githubusercontent.com/68088552/127780438-2637b6d3-ef1e-490f-87ee-ac51caae2759.png">
<img width="377" alt="Screen Shot 2021-08-01 at 10 41 25 AM" src="https://user-images.githubusercontent.com/68088552/127780439-8d942f6f-fae7-45d0-b933-890a111ba844.png">
<img width="414" alt="Screen Shot 2021-08-01 at 10 41 35 AM" src="https://user-images.githubusercontent.com/68088552/127780440-007b4e0f-dc21-4c7f-b3a5-b6d3bf823936.png">

## Environment

- Device: iPhone 11 Pro
- Operating system: iOS 14.7.1
- Build Version Version: 2.11.1 (704)
- Is this a Beta release? N

## Additional Context
Recent bug, possibly appeared with 14.7.0 or 14.7.1 not sure.

**Comment by eliykat** [comment] 2021-08-02 02:18
Duplicate of #1114, which I'll rename so it's more easily searchable in the future. I'll close this, but please add any additional reports in #1114.

**Closed by eliykat** 2021-08-02 02:18 UTC
