### ISSUE TITLE
the vault timeout option is ignored when the app restarted 

### ISSUE THREAD

**Issue by MeteorsLiu** [bitwarden/mobile#2801] opened 2023-09-28 03:36 UTC
### Steps To Reproduce

1. I set the option of the vault timeout to forever
2. the app was killed by MIUI 13
3. when i am restarted the bitwarden app, the vault locked.

### Expected Result

the vault shouldn't be locked.
because the forever option means no timeout 

### Actual Result

the vault locked even though i tried to reset the option of vault timeout to forever.

### Operating System

Android

### Operating System Version

Android 12 (MIUI 13)

### Device

Redmi K50

### Build Version

2023.9.0-9.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by MeteorsLiu** [comment] 2023-09-28 03:38
Version 2023.8.0 is OK.
However, the 2023.9.0-9.1 version ignored the timeout option.

**Comment by atjbramley** [comment] 2023-09-28 07:29
Hi @MeteorsLiu !

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/mobile/issues/2787 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by atjbramley** 2023-09-28 07:29 UTC
Labels: bug
