### ISSUE TITLE
There is a problem connecting to the server - Self-signed Cert - Android

### ISSUE THREAD

**Issue by Joshndroid** [bitwarden/mobile#346] opened 2018-07-26 10:26 UTC
So finally got myself up and running today.
Self-hosted windows docker on windows server 2016.
Utilised the self-signed cert option during install.

Have smtp settings finally sorted.
Can connect locally from pc web browser and using the firefox extention. All is good.

Install the android app from the store, configure it up the same as the firefox extension, cannot connect to the server.

Pulled the certificate.crt from bwdata from device placed on android sd card and add to certificates for both 'VPN and apps' and 'wifi' still no connection. I have checked permissions and granted the app everything (only storage and camera listed on android oreo 8.1

I'm at a loss at what could be causing this?

I've googled and read both here and reddit and can't seem to find an answer.

I have read that you may not have an answer, can i somehow force a new cert using let's encrypt? or am i going to have to hard delete bwdata and re-install it again?

Cheers.

**Comment by kspearrin** [comment] 2018-07-26 12:21
There was a bug with the generated self-signed cert that was fixed in the upcoming version here: https://github.com/bitwarden/core/pull/327

You could try generating a new self-signed cert of your own, replacing what was generated in ./bwdata/ssl

**Comment by Joshndroid** [comment] 2018-07-27 07:16
Thank you for your reply!

So i followed your advice... 
Using ubuntu machine generated a new set of certificat.crt and private.key... 

i transferred them into the certificate location in bwdata/ssl/self/bitwardendoman/

The browser recognized a new certificate not yet trusted (so i know it worked).

I added the new certificate.crt to /sdcard of android device
navigated to security -> encryption&credentials -> install from storage
From there found certificate and added it twice (once for VPN & apps & another for Wifi - just in case).

The app configured with my local domain and port...... No dice. still no connection to the server
Navigate using firefox browser to the local domain, instant connection && no requirement to trust a new certificate (as it would appear that the device has now trusted it).

Still not sure what the heck is going on.
Any ideas for me to try literally everything else is working just fine just cant connect from the most valuable aspect of the whole thing... the android app :(

**Comment by kspearrin** [comment] 2018-07-27 11:18
Android app has some additional cert trust requirements. Are you able to check your website here:
https://www.digicert.com/help/

**Comment by Joshndroid** [comment] 2018-07-28 01:51
I have tried again remade my entire bitwarden instance with a new installation ID
Browsers & browser extensions work.

Android app does not, even when trusted.

I am only running the instance in a local IP address.

There needs to be a check box or an option to decrease the harsh certificate requirements for the android app specifically. I see others are having a similar issue that seem to be similar #209

**Comment by kspearrin** [comment] 2018-07-31 18:32
I am not sure. Only thing I can suggest is to purchase a trusted cert, or use let's encrypt to get a free trusted one.

**Comment by Crocmagnon** [comment] 2018-08-01 12:17
I don't think LE can provide you with a valid cert for an IP address 😕

**Comment by MrLuje** [comment] 2018-08-30 17:05
@Joshndroid I got the android app working with a manually generated certificate :
- generate a first certificate that you will use as root CA
- generate another certificate **from the previous root CA** and use this new cert in bwdata/ssl/self/
- on your computer/android, add the root CA (not the bwdata/ssl/self/) to your trusted store (you can quickly check that it works for android by opening the web portal from any browser)

**Comment by marksarnold** [comment] 2018-09-04 06:32
Joshndroid - check out https://community.bitwarden.com/t/password-for-identity-pfx-in-self-hosted-mode/2114
I think that should work for you. Create your own self-signed certificate, and instead of entering a FQDN, enter your local IP. Worked for me.

**Comment by dNetGuru** [comment] 2018-12-01 04:33
I have a working installation of bitwarden_rs with an SSL certificate from my own self-signed CA which worked perfectly with the Bitwarden Android app.

However, my android app stopped working a couple of days ago and I checked and rechecked the entire CA chain, and every certificate and verified using various tools that the correct chain is being presented to the client. I also added the entire intermediate chain to my phone's trust store with no luck!

I noticed that there was a new version released (1.20.0) around the same time things stopped working, so I tried downgrading back to 1.19.0 and everything seems to work now.

Was something changed in terms of the requirement for the SSL certificate in this new version?

**Comment by kspearrin** [comment] 2018-12-01 06:03
Nothing was changed directly. We did update some libraries, which may have changed something with HTTP. I am not sure.

**Comment by Clever-Data** [comment] 2018-12-01 06:17
Hi i can confirm the bug as well, after the app recently updated android app attempting to login using a trusted self signed cert you now get "An error has occurred". you can attempt to add the trusted signing authority, or add the crt as trusted... still no difference.
This was working a when last tested a few weeks ago (maybe 2 weeks).

Thanks!

**Comment by dNetGuru** [comment] 2018-12-01 08:41
@kspearrin Alright, I'm going to install VS+Xamarin and try to find out what's going on then.

@Clever-Data are you using `bitwarden_rs` as well or the official containers?
I'm wondering since the error message is very generic and might not necessarily mean the certificate validation fails.

**Closed** 2018-12-02 13:56 UTC

**Comment by poldueta** [comment] 2018-12-11 14:57
@kspearrin Faced with the same issue in Play Store version. With beta build 1621 issue resolved. Waiting for release.

**Comment by dg10a** [comment] 2018-12-20 20:11
Not sure if this should be a separate issue/feature request.

I'm still seeing this error when testing on the latest version in Play Store. My site is using client certificate authentication and the client certificates are installed in system certificate store.

**Comment by thismachinechills** [comment] 2019-06-08 22:28
This is still an issue with the latest version of Bitwarden on Android 9.0.

**Comment by djusHa** [comment] 2019-07-31 23:22
@thismachinechills:
try this:
https://community.bitwarden.com/t/self-signed-certificate-on-local-network-works-with-chrome-iphone-and-android/2676

works for me on firefox and Android App

**Comment by Sp1l** [comment] 2021-05-22 12:43
Just figured out why I got the 'Certificate Chain Validation Error' in the Android client.

**OCSP stapling must be configured properly on the webserver.**

My webserver jail has no outbound connectivity by default. After fixing OCSP stapling, the Android App works just fine!
