### ISSUE TITLE
iOS: 2024.4.2+ cannot autofill

### ISSUE THREAD

**Issue by LittleTurtle2333** [bitwarden/mobile#3268] opened 2024-05-30 17:53 UTC
### Steps To Reproduce

![AA4897B5-5CD9-4F55-898D-66F986CED676](https://github.com/bitwarden/mobile/assets/32336368/0eb50445-a787-463f-a4f6-39b0db1688b9)

### Expected Result

auto fill

### Actual Result

not working

### Additional Context

it didn’t work on 2024.4.2 or 2024.5.1.
I downgraded to 2024.4.0 and it was fine.

### Operating System

iOS

### Operating System Version

iOS 16.3.1

### Device

iPhone 13Pro

### Build Version

2024.5.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment] 2024-05-31 02:43
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/mobile/issues/3225

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-05-31 02:43 UTC
Labels: bug
